--***********************************************************
--**                    THE INDIE STONE                    **
--***********************************************************

MapSymbolDefinitions.getInstance():addTexture("ArrowEast", "media/ui/LootableMaps/map_arroweast.png")
MapSymbolDefinitions.getInstance():addTexture("ArrowNorth", "media/ui/LootableMaps/map_arrownorth.png")
MapSymbolDefinitions.getInstance():addTexture("ArrowSouth", "media/ui/LootableMaps/map_arrowsouth.png")
MapSymbolDefinitions.getInstance():addTexture("ArrowWest", "media/ui/LootableMaps/map_arrowwest.png")
MapSymbolDefinitions.getInstance():addTexture("ArrowNorthWest", "media/ui/LootableMaps/map_arrownorthwest.png")
MapSymbolDefinitions.getInstance():addTexture("ArrowNorthEast", "media/ui/LootableMaps/map_arrownortheast.png")
MapSymbolDefinitions.getInstance():addTexture("ArrowSouthWest", "media/ui/LootableMaps/map_arrowsouthwest.png")
MapSymbolDefinitions.getInstance():addTexture("ArrowSouthEast", "media/ui/LootableMaps/map_arrowsoutheast.png")
MapSymbolDefinitions.getInstance():addTexture("Apple", "media/ui/LootableMaps/map_apple.png")
MapSymbolDefinitions.getInstance():addTexture("Asterisk", "media/ui/LootableMaps/map_asterisk.png")
MapSymbolDefinitions.getInstance():addTexture("Axe", "media/ui/LootableMaps/map_axe.png")
MapSymbolDefinitions.getInstance():addTexture("Boat", "media/ui/LootableMaps/map_boat.png")
MapSymbolDefinitions.getInstance():addTexture("Burger", "media/ui/LootableMaps/map_burger.png")
MapSymbolDefinitions.getInstance():addTexture("Checkmark", "media/ui/LootableMaps/map_checkmark.png")
MapSymbolDefinitions.getInstance():addTexture("Club", "media/ui/LootableMaps/map_club.png")
MapSymbolDefinitions.getInstance():addTexture("Cross", "media/ui/LootableMaps/map_cross.png")
MapSymbolDefinitions.getInstance():addTexture("Diamond", "media/ui/LootableMaps/map_diamond.png")
MapSymbolDefinitions.getInstance():addTexture("DollarSign", "media/ui/LootableMaps/map_dollarsign.png")
MapSymbolDefinitions.getInstance():addTexture("Exclamation", "media/ui/LootableMaps/map_exclamation.png")
MapSymbolDefinitions.getInstance():addTexture("FaceDead", "media/ui/LootableMaps/map_facedead.png")
MapSymbolDefinitions.getInstance():addTexture("FaceHappy", "media/ui/LootableMaps/map_facehappy.png")
MapSymbolDefinitions.getInstance():addTexture("FaceSad", "media/ui/LootableMaps/map_facesad.png")
MapSymbolDefinitions.getInstance():addTexture("Fire", "media/ui/LootableMaps/map_firet.png")
MapSymbolDefinitions.getInstance():addTexture("Fish", "media/ui/LootableMaps/map_fish.png")
MapSymbolDefinitions.getInstance():addTexture("Garbage", "media/ui/LootableMaps/map_garbage.png")
MapSymbolDefinitions.getInstance():addTexture("Gears", "media/ui/LootableMaps/map_gears.png")
MapSymbolDefinitions.getInstance():addTexture("Gun", "media/ui/LootableMaps/map_gun.png")
MapSymbolDefinitions.getInstance():addTexture("Heart", "media/ui/LootableMaps/map_heart.png")
MapSymbolDefinitions.getInstance():addTexture("House", "media/ui/LootableMaps/map_house.png")
MapSymbolDefinitions.getInstance():addTexture("KnifeFork", "media/ui/LootableMaps/map_knifefork.png")
MapSymbolDefinitions.getInstance():addTexture("Leaf", "media/ui/LootableMaps/map_leaf.png")
MapSymbolDefinitions.getInstance():addTexture("Lightning", "media/ui/LootableMaps/map_lightning.png")
MapSymbolDefinitions.getInstance():addTexture("Lock", "media/ui/LootableMaps/map_lock.png")
MapSymbolDefinitions.getInstance():addTexture("MedCross", "media/ui/LootableMaps/map_medcross.png")
MapSymbolDefinitions.getInstance():addTexture("Moon", "media/ui/LootableMaps/map_moon.png")
MapSymbolDefinitions.getInstance():addTexture("Circle", "media/ui/LootableMaps/map_o.png")
MapSymbolDefinitions.getInstance():addTexture("Pill", "media/ui/LootableMaps/map_pill.png")
MapSymbolDefinitions.getInstance():addTexture("Question", "media/ui/LootableMaps/map_question.png")
MapSymbolDefinitions.getInstance():addTexture("Radiation", "media/ui/LootableMaps/map_radiation.png")
MapSymbolDefinitions.getInstance():addTexture("Skull", "media/ui/LootableMaps/map_skull.png")
MapSymbolDefinitions.getInstance():addTexture("Spade", "media/ui/LootableMaps/map_spade.png")
MapSymbolDefinitions.getInstance():addTexture("Star", "media/ui/LootableMaps/map_star.png")
MapSymbolDefinitions.getInstance():addTexture("Sun", "media/ui/LootableMaps/map_sun.png")
MapSymbolDefinitions.getInstance():addTexture("Target", "media/ui/LootableMaps/map_target.png")
MapSymbolDefinitions.getInstance():addTexture("Tent", "media/ui/LootableMaps/map_tent.png")
MapSymbolDefinitions.getInstance():addTexture("Trap", "media/ui/LootableMaps/map_trap.png")
MapSymbolDefinitions.getInstance():addTexture("Waves", "media/ui/LootableMaps/map_waves.png")
MapSymbolDefinitions.getInstance():addTexture("Wrench", "media/ui/LootableMaps/map_wrench.png")
MapSymbolDefinitions.getInstance():addTexture("X", "media/ui/LootableMaps/map_x.png")
MapSymbolDefinitions.getInstance():addTexture("Z", "media/ui/LootableMaps/map_z.png")

