local generic_plant = {
    main = {
        "d_generic_1_0",
        "d_generic_1_1",
        "d_generic_1_2",
        "d_generic_1_3",
        "d_generic_1_4",
        "d_generic_1_5",
        "d_generic_1_6",
        "d_generic_1_7",
        "d_generic_1_8",
        "d_generic_1_9",
        "d_generic_1_10",
        "d_generic_1_11",
        "d_generic_1_12",
        "d_generic_1_13",
        "d_generic_1_14",
        "d_generic_1_15",

        "d_generic_1_16",
        "d_generic_1_17",
        "d_generic_1_18",
        "d_generic_1_19",
        "d_generic_1_20",
        "d_generic_1_21",
        "d_generic_1_22",
        "d_generic_1_23",
        "d_generic_1_24",
        "d_generic_1_25",
        "d_generic_1_26",
        "d_generic_1_27",
        "d_generic_1_28",
        "d_generic_1_29",
        "d_generic_1_30",
        "d_generic_1_31",

        --"d_generic_1_32",
        --"d_generic_1_33",
        --"d_generic_1_34",
        --"d_generic_1_35",
        --"d_generic_1_36",
        --"d_generic_1_37",
        --"d_generic_1_38",
        --"d_generic_1_39",
        --"d_generic_1_40",
        --"d_generic_1_41",
        --"d_generic_1_42",
        --"d_generic_1_43",
        --"d_generic_1_44",
        --"d_generic_1_45",
        --"d_generic_1_46",
        --"d_generic_1_47",
    }
}
worldgen.features.PLANT["generic_plant"] = generic_plant