local grass_high = {
    main = {
        "e_newgrass_1_8",
        "e_newgrass_1_9",
        "e_newgrass_1_10",
        "e_newgrass_1_11",
        "e_newgrass_1_12",
        "e_newgrass_1_13",
        "e_newgrass_1_8",
        "e_newgrass_1_9",
        "e_newgrass_1_10",
        "e_newgrass_1_11",
        "e_newgrass_1_12",
        "e_newgrass_1_13",
        "e_newgrass_1_8",
        "e_newgrass_1_9",
        "e_newgrass_1_10",
        "e_newgrass_1_11",
        "e_newgrass_1_12",
        "e_newgrass_1_13",
        "e_newgrass_1_16",
        "e_newgrass_1_17",
        "e_newgrass_1_18",
        "e_newgrass_1_19",
        "e_newgrass_1_20",
        "e_newgrass_1_21",
        "e_newgrass_1_0",
        "e_newgrass_1_1",
        "e_newgrass_1_2",
        "e_newgrass_1_3",
        "e_newgrass_1_4",
        "e_newgrass_1_5",
    
    }
}
worldgen.features.PLANT["grass_high"] = grass_high