---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RJ.
--- DateTime: 11/18/2024 10:46 AM
---

ISAnimalZoneFirstInfo = ISPanel:derive("ISAnimalZoneFirstInfo");

local FONT_HGT_SMALL = getTextManager():getFontHeight(UIFont.NewSmall)
local FONT_HGT_MEDIUM = getTextManager():getFontHeight(UIFont.NewMedium)
local UI_BORDER_SPACING = 10
local BUTTON_HGT = FONT_HGT_SMALL + 15

function ISAnimalZoneFirstInfo:initialise()
    ISPanel.initialise(self);
    local btnWid = 150

    self.okBtn = ISButton:new(self:getWidth() / 2 - (btnWid / 2), self:getHeight() - UI_BORDER_SPACING - BUTTON_HGT, btnWid, BUTTON_HGT, getText("UI_Ok"), self, ISAnimalZoneFirstInfo.onClickOk);
    self.okBtn.anchorTop = false
    self.okBtn.anchorBottom = true
    self.okBtn:initialise();
    self.okBtn:instantiate();
    self:addChild(self.okBtn);

    self.rich = ISRichTextPanel:new(5, 10, self.width - 10, self.height - 40);
    self.rich.anchorLeft = true;
    self.rich.anchorRight = true;
    self.rich.marginLeft = 0
    self.rich.marginRight = 0
    self.rich:initialise();
    self.rich:instantiate();
    self.rich:noBackground();
    self.rich.backgroundColor = {r=0, g=0, b=0, a=0.3};
    self.rich.borderColor = {r=1, g=1, b=1, a=0.1};
    self:addChild(self.rich)
end

function ISAnimalZoneFirstInfo:prerender()
    self:drawRect(0, 0, self.width, self.height, self.backgroundColor.a, self.backgroundColor.r, self.backgroundColor.g, self.backgroundColor.b);
    self:drawRectBorder(0, 0, self.width, self.height, self.borderColor.a, self.borderColor.r, self.borderColor.g, self.borderColor.b);
end

function ISAnimalZoneFirstInfo:render()

    self.rich.text = getText("IGUI_Animal_ZoneFirstInfo");
    self.rich:paginate()
end

function ISAnimalZoneFirstInfo:onClickOk()
    getCore():setOptionShowFirstAnimalZoneInfo(false);
    getCore():saveOptions();

    self:setVisible(false);
    self:removeFromUIManager();
end

ISAnimalZoneFirstInfo.showUI = function(force)
    if force or getCore():getOptionShowFirstAnimalZoneInfo() then
        local ui = ISAnimalZoneFirstInfo:new(0,0);
        ui:initialise();
        ui:addToUIManager();
    end
end

function ISAnimalZoneFirstInfo:new(x, y)
    local width = 700;
    local height = 500;

    local o = {}
    o = ISPanel:new(x, y, width, height);
    setmetatable(o, self)
    self.__index = self
    if y == 0 then
        o.y = getCore():getScreenHeight() / 2 - (height / 2)
        o:setY(o.y)
    end
    if x == 0 then
        o.x = getCore():getScreenWidth() / 2 - (width / 2)
        o:setX(o.x)
    end
    o.borderColor = {r=0.4, g=0.4, b=0.4, a=1};
    o.backgroundColor = {r=0, g=0, b=0, a=0.8};

    return o;
end