---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RJ.
--- DateTime: 9/19/2024 10:39 AM
---

require "ISUI/ISCollapsableWindow"

local FONT_HGT_SMALL = getTextManager():getFontHeight(UIFont.NewSmall)
local FONT_HGT_MEDIUM = getTextManager():getFontHeight(UIFont.Medium)

ISButcheringDebugUI = ISCollapsableWindow:derive("ISButcheringDebugUI");

function ISButcheringDebugUI:prerender()
    ISCollapsableWindow.prerender(self)
end

function ISButcheringDebugUI:render()
    ISCollapsableWindow.render(self);

    self:drawText(self.carcass:getCustomName(), 15, 20, 1,1,1,1, UIFont.Medium);

    self:drawText(self.butcherText, 15, 45, 1,1,1,1, UIFont.Small);
end

function ISButcheringDebugUI:initialise()
    ISCollapsableWindow.initialise(self);
    self:create();
end

function ISButcheringDebugUI:create()
    local btnWid = 70
    local btnHgt = FONT_HGT_SMALL + 5;

    self.butcherBtn = ISButton:new(10,self:getHeight() - 10 - btnHgt, btnWid, btnHgt, "Butcher " .. self.carcass:getCustomName(), self, ISButcheringDebugUI.butcher);
    self.butcherBtn:initialise();
    self.butcherBtn:instantiate();
    self.butcherBtn.borderColor = {r=1, g=1, b=1, a=0.1};
    self.butcherBtn:setVisible(true);
    self:addChild(self.butcherBtn);
end

function ISButcheringDebugUI:butcher()
    self.butcherText = ButcheringUtil.butcherAnimalFromGround(self.carcass, self.chr, true);
end

function ISButcheringDebugUI:new(x, y, width, height, carcass, player)
    local o = {};
    o = ISCollapsableWindow:new(x, y, width, height);
    --    o:noBackground();
    setmetatable(o, self);
    self.__index = self;
    o.carcass = carcass;
    o.chr = player;
    o.butcherText = "";
    o.playerNum = player:getPlayerNum();
    o.refreshNeeded = true
    o.borderColor = {r=0.4, g=0.4, b=0.4, a=1};
    o.backgroundColor = {r=0, g=0, b=0, a=0.8};
    return o;
end
