require("WorldGen/WorldGen")

worldgen["similar"] = {
    floors_burnt_01_8 = worldgen.features.GROUND.burnt.main,
    floors_burnt_01_13 = worldgen.features.GROUND.burnt.main,
    floors_burnt_01_14 = worldgen.features.GROUND.burnt.main,
    floors_burnt_01_15 = worldgen.features.GROUND.burnt.main,
    blends_natural_01_16 = worldgen.features.GROUND.dark_grass.main,
    blends_natural_01_21 = worldgen.features.GROUND.dark_grass.main,
    blends_natural_01_22 = worldgen.features.GROUND.dark_grass.main,
    blends_natural_01_23 = worldgen.features.GROUND.dark_grass.main,
    blends_natural_01_64 = worldgen.features.GROUND.dirt.main,
    blends_natural_01_69 = worldgen.features.GROUND.dirt.main,
    blends_natural_01_70 = worldgen.features.GROUND.dirt.main,
    blends_natural_01_71 = worldgen.features.GROUND.dirt.main,
    blends_natural_01_80 = worldgen.features.GROUND.dirt_grass.main,
    blends_natural_01_85 = worldgen.features.GROUND.dirt_grass.main,
    blends_natural_01_86 = worldgen.features.GROUND.dirt_grass.main,
    blends_natural_01_87 = worldgen.features.GROUND.dirt_grass.main,
    blends_natural_01_48 = worldgen.features.GROUND.light_grass.main,
    blends_natural_01_53 = worldgen.features.GROUND.light_grass.main,
    blends_natural_01_54 = worldgen.features.GROUND.light_grass.main,
    blends_natural_01_55 = worldgen.features.GROUND.light_grass.main,
    blends_natural_01_32 = worldgen.features.GROUND.medium_grass.main,
    blends_natural_01_37 = worldgen.features.GROUND.medium_grass.main,
    blends_natural_01_38 = worldgen.features.GROUND.medium_grass.main,
    blends_natural_01_39 = worldgen.features.GROUND.medium_grass.main,
    blends_natural_01_0 = worldgen.features.GROUND.sand.main,
    blends_natural_01_5 = worldgen.features.GROUND.sand.main,
    blends_natural_01_6 = worldgen.features.GROUND.sand.main,
    blends_natural_01_7 = worldgen.features.GROUND.sand.main,
    blends_natural_02_0 = worldgen.features.GROUND.water.main,
    blends_natural_02_5 = worldgen.features.GROUND.water.main,
    blends_natural_02_6 = worldgen.features.GROUND.water.main,
    blends_natural_02_7 = worldgen.features.GROUND.water.main
}