ClutterTables = ClutterTables or {}

ClutterTables.SeatFrontItems = {
	"Base.LouisvilleMap1", 0.01,
	"Base.LouisvilleMap2", 0.01,
	"Base.LouisvilleMap3", 0.01,
	"Base.LouisvilleMap4", 0.01,
	"Base.LouisvilleMap5", 0.01,
	"Base.LouisvilleMap6", 0.01,
	"Base.LouisvilleMap7", 0.01,
	"Base.LouisvilleMap8", 0.01,
	"Base.LouisvilleMap9", 0.01,
	"Base.MarchRidgeMap", 0.4,
	"Base.MuldraughMap", 0.4,
	"Base.RiversideMap", 0.4,
	"Base.RosewoodMap", 0.4,
	"Base.WestpointMap", 0.4,
	"BluePen", 8,
	"Brochure", 1,
	"CDplayer", 2,
	"Cigar", 0.1,
	"CigarettePack", 8,
	"CigaretteRollingPapers", 0.05,
	"Cigarillo", 2,
	"CorpseFemale", 0.001,
	"CorpseMale", 0.001,
	"Disc_Retail", 2,
	"Flier", 1,
	"Glasses", 0.1,
	"Glasses_Aviators", 0.05,
	"Glasses_CatsEye_Sun", 0.1,
	"Glasses_JackieO", 0.001,
	"Glasses_Macho", 0.005,
	"Glasses_Normal_HornRimmed", 0.1,
	"Glasses_Round_Shades", 0.001,
	"Glasses_Sun", 0.1,
	"Glasses_SunCheap", 0.5,
	"Handbag", 0.5,
	"LighterDisposable", 4,
	"Lipstick", 6,
	"Magazine", 5,
	"Magazine_Popular", 5,
	"MakeupEyeshadow", 6,
	"MakeupFoundation", 6,
	"Matches", 8,
	"Mirror", 4,
	"Notebook", 4,
	"Notepad", 10,
	"Paperclip", 4,
	"PaperNapkins2", 8,
	"Pen", 8,
	"Pencil", 10,
	"PopBottleEmpty", 1,
	"PopEmpty", 4,
	"Purse", 0.5,
	"Razor", 4,
	"RedPen", 8,
	"RubberBand", 6,
	"Scotchtape", 8,
	"Tissue", 10,
	"TobaccoChewing", 0.05,
	"TobaccoLoose", 0.05,
	"Twine", 0.1,
	"WalkieTalkie2", 2,
	"WalkieTalkie3", 1,
	"Wallet", 4,
	"WaterBottle", 1,
}

ClutterTables.SeatFrontJunk = {
	rolls = 1,
	ignoreZombieDensity = true,
	items = ClutterTables.SeatFrontItems,
}

ClutterTables.SeatRearItems = {
	"Base.LouisvilleMap1", 0.01,
	"Base.LouisvilleMap2", 0.01,
	"Base.LouisvilleMap3", 0.01,
	"Base.LouisvilleMap4", 0.01,
	"Base.LouisvilleMap5", 0.01,
	"Base.LouisvilleMap6", 0.01,
	"Base.LouisvilleMap7", 0.01,
	"Base.LouisvilleMap8", 0.01,
	"Base.LouisvilleMap9", 0.01,
	"Base.MarchRidgeMap", 0.4,
	"Base.MuldraughMap", 0.4,
	"Base.RiversideMap", 0.4,
	"Base.RosewoodMap", 0.4,
	"Base.WestpointMap", 0.4,
	"BluePen", 8,
	"Brochure", 1,
	"CDplayer", 2,
	"CorpseFemale", 0.001,
	"CorpseMale", 0.001,
	"Disc_Retail", 2,
	"DuctTape", 4,
	"Flier", 1,
	"FountainCup", 4,
	"Handbag", 0.5,
	"Magazine", 5,
	"Magazine_Popular", 5,
	"Matches", 8,
	"Mirror", 4,
	"Notebook", 4,
	"Notepad", 10,
	"Paperclip", 4,
	"PaperNapkins2", 8,
	"Pen", 8,
	"Pencil", 10,
	"Plasticbag_Bags", 8,
	"PopBottleEmpty", 1,
	"PopEmpty", 4,
	"Purse", 0.5,
	"RecipeClipping", 0.1,
	"RedPen", 8,
	"RubberBand", 6,
	"Scotchtape", 8,
	"Straw2", 4,
	"Tissue", 10,
	"ToiletPaper", 4,
	"Tote_Bags", 4,
	"TVMagazine", 1,
	"Twine", 0.1,
	"WalkieTalkie2", 2,
	"WalkieTalkie3", 1,
	"WaterBottle", 1,
}

ClutterTables.SeatRearJunk = {
	rolls = 1,
	ignoreZombieDensity = true,
	items = ClutterTables.SeatRearItems,
}