ClutterTables = ClutterTables or {}

ClutterTables.CounterItems = {
	"BluePen", 8,
	"BusinessCard", 1,
	"Calculator", 4,
	"Clipboard", 8,
	"Doodle", 1,
	"Eraser", 8,
	"Glue", 2,
	"GreenPen", 4,
	"HolePuncher", 4,
	"MagazineCrossword", 2,
	"MagazineWordsearch", 2,
	"Magazine_Popular", 2,
	"MarkerBlack", 1,
	"MarkerBlue", 0.5,
	"MarkerGreen", 0.5,
	"MarkerRed", 0.5,
	"Notebook", 4,
	"Notepad", 8,
	"Paperclip", 10,
	"PaperclipBox", 1,
	"Pen", 8,
	"Pencil", 10,
	"Phonebook", 10,
	"RadioBlack", 1,
	"RadioRed", 1,
	"RedPen", 8,
	"RubberBand", 1,
	"Scissors", 2,
	"ScissorsBlunt", 2,
	"Scotchtape", 4,
	"SheetPaper2", 10,
	"Stapler", 4,
	"Staples", 10,
	"TissueBox", 0.5,
	"TVMagazine", 4,
	"Twine", 1,
}

ClutterTables.CounterJunk = {
	rolls = 1,
	ignoreZombieDensity = true,
	items = ClutterTables.CounterItems,
}