ClutterTables = ClutterTables or {}

-- 'Junk' might be considered a misnomer for these. This is a standardized 'filler' table for desks of all types.
-- These items may spawn in addition to themed desk contents to give a more well-rounded office appearance.
ClutterTables.DeskItems = {
	-- Pens/Pencils/Markers
	"BluePen", 4,
	"MarkerBlack", 0.5,
	"MarkerBlue", 0.5,
	"MarkerGreen", 0.1,
	"MarkerRed", 0.5,
	"Pen", 4,
	"Pencil", 8,
	"PenFancy", 0.5,
	"RedPen", 4,
	-- Stationery
	"Calculator", 4,
	"Clipboard", 8,
	"CorrectionFluid", 4,
	"Eraser", 8,
	"Glue", 2,
	"HolePuncher", 4,
	"LetterHandwritten", 2,
	"LetterOpener", 0.5,
	"MagnifyingGlass", 0.1,
	"Paperclip", 10,
	"PaperclipBox", 1,
	"RubberBand", 1,
	"RubberBand", 8,
	"Scissors", 2,
	"ScissorsBlunt", 2,
	"Scotchtape", 4,
	"SheetPaper2", 10,
	"Stapler", 4,
	"Staples", 10,
	"Tsquare", 1,
	"Twine", 1,
	-- Literature (Readable/Junk)
	"Brochure", 2,
	"BusinessCard", 1,
	"Catalog", 4,
	"Doodle", 1,
	"Flier", 2,
	"GenericMail", 2,
	"Magazine", 2,
	"MagazineCrossword", 1,
	"MagazineWordsearch", 1,
	"Magazine_Popular", 2,
	"MenuCard", 1,
	"Newspaper", 2,
	"Newspaper_Recent", 2,
	"Note", 20,
	"Note", 10,
	"Notebook", 4,
	"Notepad", 8,
	"Receipt", 10,
	"TVMagazine", 4,
	-- Cosmetic/Hygiene
	"Cologne", 1,
	"Comb", 2,
	"Lipstick", 1,
	"MakeupEyeshadow", 1,
	"MakeupFoundation", 1,
	"Mirror", 1,
	"Perfume", 1,
	"Toothbrush", 1,
	-- Misc.
	"CardDeck", 1,
	"CDplayer", 2,
	"CigarettePack", 4,
	"CreditCard", 4,
	"Disc_Retail", 2,
	"LighterDisposable", 2,
	"Matches", 4,
	"Money", 4,
	"RadioBlack", 2,
	"RadioRed", 1,
	-- Watches
	"WristWatch_Left_ClassicBlack", 0.5,
	"WristWatch_Left_ClassicBrown", 0.5,
	"WristWatch_Left_ClassicGold", 0.1,
	"WristWatch_Left_DigitalDress", 0.1,
	"WristWatch_Left_Expensive", 0.01,
	-- Bags/Containers
	"Briefcase", 1,
	"Handbag", 0.5,
	"Lunchbag", 1,
	"Lunchbox", 1,
	"Lunchbox2", 0.01,
	"Purse", 0.5,
	-- Special
	"BobPic", 0.001,
	"CaseyPic", 0.001,
	"ChrisPic", 0.001,
	"CortmanPic", 0.001,
	"HankPic", 0.001,
	"JamesPic", 0.001,
	"KatePic", 0.001,
	"MariannePic", 0.001,
}

ClutterTables.DeskJunk = {
	rolls = 1,
	ignoreZombieDensity = true,
	items = ClutterTables.DeskItems,
}