SpecialLootSpawns = SpecialLootSpawns or {}

SpecialLootSpawns.Magazines = {
    "AirandSpaceNews",
    "AltF4",
    "AmericanCyclist",
    "AmericanHobbies",
    "AmericanHobbies",
    "AmericanPoet",
    "Andborg",
    "FireSafetyNews",
    "ArtAmerica",
    "AuNaturel",
    "AutomobilesMonthly",
    "Backroad",
    "Bassline",
    "Beauty",
    "Belief",
    "BigBiceps",
    "BlockoMagazine",
    "BluesnJazz",
    "Boink",
    "Brash",
    "Brief",
    "CabinFever",
    "CardGames",
    "Charm",
    "Checkmate",
    "ChristiansTogether",
    "CigarsCaviar",
    "ClassicBattles",
    "CodeWorld",
    "Collecting",
    "CompressedBooks",
    "CompressedBooks",
    "CongressWatcher",
    "CustodialOperator",
    "DarkTales",
    "DigitalAdventurePower",
    "DragKings",
    "Economy",
    "Electron",
    "Elegant",
    "Elegant",
    "ElegantGirl",
    "EverydayMotorist",
    "ExecutiveLounge",
    "Extinguish",
    "FamilyCaring",
    "Figary",
    "Figary",
    "Fine",
    "FineWine",
    "FlyingSaucerJournal",
    "FootballFrenzy",
    "Forces",
    "Fore",
    "ForeverLiving",
    "FowlIntentions",
    "Freewheelin",
    "FuturePaleontology",
    "GameZ",
    "GhostlyHauntings",
    "Greens",
    "GruesomeCrimeScenes",
    "HeySir",
    "HighFlyer",
    "HikingFootwear",
    "HollywoodNews",
    "HomeRun",
    "HospitalTechnology",
    "HouseholdFinances",
    "ImproveYourHouse",
    "ImproveYourHouse",
    "IncredibleHeroes",
    "InFocus",
    "Inquire",
    "Inquire",
    "JokesJokes",
    "Jump",
    "KentuckyDriver",
    "KentuckyHorseRacing",
    "KentuckyLiberal",
    "KentuckyObserver",
    "KentuckyObserver",
    "KimsTanksandArmorMonthly",
    "KirrusComputing",
    "KoolKids",
    "Labyrinths",
    "LatestForensics",
    "Lifestyle",
    "Lifestyle",
    "LouisvilleBusinessReview",
    "LouisvilleLaughter",
    "MajesticBigGame",
    "MalpracticeInsuranceMonthly",
    "MansHealth",
    "MansHealth",
    "MarketsMonthly",
    "Me",
    "Merc",
    "ModernDance",
    "ModernTrains",
    "MonstrousTrucks",
    "MossyRock",
    "MossyRock",
    "MotorcycleEnthusiast",
    "MoviesWeekly",
    "NationalCelebs",
    "NationalCelebs",
    "NatureFacts",
    "Newsday",
    "Newsday",
    "Newton",
    "Newton",
    "Numisatics",
    "OldWestLife",
    "OpenMind",
    "OSCCInsider",
    "PaleGnome",
    "Parentage",
    "Paws",
    "PhilatelyLately",
    "Photospread",
    "Piledriver",
    "PoliceFiles",
    "Proletariat",
    "ReadingsMonthly",
    "ReadingsMonthly",
    "RealEstateInvestment",
    "ReelinginandGear",
    "Revelations",
    "RockOut",
    "RunningLife",
    "RunningnGunning",
    "Scoped",
    "ScreenShriek",
    "SecondAmendment",
    "ShortsIllustrated",
    "SilverScreen",
    "Sixteen",
    "Skeptical",
    "SongandDance",
    "Sorbes",
    "SouthernLiteraryReview",
    "SportsStats",
    "Sprinter",
    "StandYourGround",
    "StockTrends",
    "StPatricksJournal",
    "Style",
    "StyleLife",
    "SuspectsandWitnesses",
    "TakeaLife",
    "Telltale",
    "Telltale",
    "TheBiclops",
    "TheBigApple",
    "TheForeignReview",
    "TheNationalist",
    "TheWallStreetPost",
    "TheWorldWars",
    "Thresher",
    "TodaysBuilder",
    "TPower",
    "Trailbeaters",
    "TruckingHeaven",
    "TrueCrimeStories",
    "TrueSerialKillings",
    "TTRPG",
    "TwitchingWeekly",
    "UnpopularElectronics",
    "UnsoldStories",
    "UpperCrust",
    "UptoEleven",
    "Veteran",
    "VHSEnthusiast",
    "VitimaniaRx",
    "WatercraftandBikes",
    "WorldGeograph",
    "WorldGeograph",
    "WorldMusic",
    "WorldTrade",
    "WorldTrade",
    "WWCInsider",
    "Y",
    "Y",
    "YourInvestmentGuide",
}
SpecialLootSpawns.MagazineSubjects = {}

SpecialLootSpawns.MagazineSubjects.Art = {
    "ArtAmerica",
    "InFocus",
    "ModernDance",
    "Photospread",
}

SpecialLootSpawns.MagazineSubjects.Business = {
    "Economy",
    "LouisvilleBusinessReview",
    "MarketsMonthly",
    "RealEstateInvestment",
    "Sorbes",
    "StockTrends",
    "TheWallStreetPost",
    "WorldTrade",
    "WorldTrade",
    "YourInvestmentGuide",
}

SpecialLootSpawns.MagazineSubjects.Cars = {
    "AutomobilesMonthly",
    "DragKings",
    "EverydayMotorist",
    "KentuckyDriver",
    "MonstrousTrucks",
    "MotorcycleEnthusiast",
    "OSCCInsider",
    "TruckingHeaven",
    "WatercraftandBikes",
}

SpecialLootSpawns.MagazineSubjects.Childs = {
    "BlockoMagazine",
    "FuturePaleontology",
    "GameZ",
    "IncredibleHeroes",
    "KoolKids",
    "NatureFacts",
    "Paws",
}

SpecialLootSpawns.MagazineSubjects.Cinema = {
    "HollywoodNews",
    "MoviesWeekly",
    "SilverScreen",
    "VHSEnthusiast",
}

SpecialLootSpawns.MagazineSubjects.Crime = {
	"GruesomeCrimeScenes",
    "LatestForensics",
    "PoliceFiles",
    "TakeaLife",
    "TrueCrimeStories",
    "TrueSerialKillings",
}

SpecialLootSpawns.MagazineSubjects.Fashion = {
    "Beauty",
    "Brash",
    "Charm",
    "Elegant",
    "Elegant",
    "ShortsIllustrated",
    "Style",
}

SpecialLootSpawns.MagazineSubjects.Firearm = {
    "RunningnGunning",
    "Scoped",
    "SecondAmendment",
    "StandYourGround",
}

SpecialLootSpawns.MagazineSubjects.Gaming = {
    "GameZ",
    "Labyrinths",
    "PaleGnome",
    "TheBiclops",
    "TTRPG",
}

SpecialLootSpawns.MagazineSubjects.Golf = {
    "Fore",
    "Greens",
    "TPower",
}

SpecialLootSpawns.MagazineSubjects.Health = {
    "BigBiceps",
    "ForeverLiving",
    "MansHealth",
    "MansHealth",
    "RunningLife",
    "Sprinter",
    "VitimaniaRx",
}

SpecialLootSpawns.MagazineSubjects.Hobby = {
    "AmericanHobbies",
    "AmericanHobbies",
    "Andborg",
    "CardGames",
    "Checkmate",
    "Collecting",
    "DigitalAdventurePower",
    "GameZ",
    "Labyrinths",
    "PaleGnome",
    "TheBiclops",
    "TTRPG",
    "TwitchingWeekly",
    "UnpopularElectronics",
}

SpecialLootSpawns.MagazineSubjects.Horror = {
    "DarkTales",
    "FlyingSaucerJournal",
    "GhostlyHauntings",
    "GruesomeCrimeScenes",
    "ScreenShriek",
    "TrueSerialKillings",
}

SpecialLootSpawns.MagazineSubjects.Humor = {
    "Boink",
    "Figary",
    "Figary",
    "JokesJokes",
    "LouisvilleLaughter",
}

SpecialLootSpawns.MagazineSubjects.Military = {
    "AirandSpaceNews",
    "ClassicBattles",
    "IncredibleHeroes",
    "KimsTanksandArmorMonthly",
    "Merc",
    "TheWorldWars",
    "Veteran",
}

SpecialLootSpawns.MagazineSubjects.Music = {
    "Bassline",
    "BluesnJazz",
    "MossyRock",
    "MossyRock",
    "RockOut",
    "SongandDance",
    "UptoEleven",
    "WorldMusic",
}

SpecialLootSpawns.MagazineSubjects.Outdoors = {
    "AuNaturel",
    "Backroad",
    "CabinFever",
    "FowlIntentions",
    "HikingFootwear",
    "MajesticBigGame",
    "ReelinginandGear",
    "Trailbeaters",
    "WatercraftandBikes",
}

SpecialLootSpawns.MagazineSubjects.Police = {
    "FireSafetyNews",
    "CustodialOperator",
    "LatestForensics",
    "PoliceFiles",
    "SuspectsandWitnesses",
}

SpecialLootSpawns.MagazineSubjects.Popular = {
    "AmericanHobbies",
    "CompressedBooks",
    "Elegant",
    "Figary",
    "ImproveYourHouse",
    "Inquire",
    "KentuckyObserver",
    "Lifestyle",
    "MansHealth",
    "MossyRock",
    "NationalCelebs",
    "Newsday",
    "Newton",
    "ReadingsMonthly",
    "Telltale",
    "WorldGeograph",
    "WorldTrade",
    "Y",
}

SpecialLootSpawns.MagazineSubjects.Rich = {
    "CigarsCaviar",
    "ExecutiveLounge",
    "FineWine",
    "Fore",
    "Greens",
    "HighFlyer",
    "MalpracticeInsuranceMonthly",
    "RealEstateInvestment",
    "TPower",
    "UpperCrust",
}

SpecialLootSpawns.MagazineSubjects.Science = {
    "Andborg",
    "Electron",
    "FuturePaleontology",
    "Newton",
    "Newton",
    "OpenMind",
    "Skeptical",
}

SpecialLootSpawns.MagazineSubjects.Sports = {
    "AmericanCyclist",
    "FootballFrenzy",
    "Fore",
    "Freewheelin",
    "Greens",
    "HomeRun",
    "KentuckyHorseRacing",
    "OSCCInsider",
    "Piledriver",
    "SportsStats",
    "Thresher",
    "TPower",
    "WWCInsider",
}

SpecialLootSpawns.MagazineSubjects.Tech = {
    "AltF4",
    "Andborg",
    "CodeWorld",
    "DigitalAdventurePower",
    "GameZ",
    "KirrusComputing",
    "UnpopularElectronics",
}

SpecialLootSpawns.MagazineSubjects.Teens = {
    "DigitalAdventurePower",
    "ElegantGirl",
    "Freewheelin",
    "GameZ",
    "Jump",
    "MonstrousTrucks",
    "Piledriver",
    "RockOut",
    "Sixteen",
    "Thresher",
    "WWCInsider",
}

SpecialLootSpawns.MagazineDetails = {
    AirandSpaceNews= { firstYear = 1950 },
    AltF4= { firstYear = 1988 },
    AmericanCyclist= { firstYear = 1892 },
    AmericanHobbies= { firstYear = 1902 },
    Andborg= { firstYear = 1935 },
    FireSafetyNews= { firstYear = 1981 },
    ArtAmerica= { firstYear = 1926 },
    AuNaturel= { firstYear = 1904 },
    AutomobilesMonthly= { firstYear = 1927 },
    Backroad= { firstYear = 1922 },
    Bassline= { firstYear = 1954 },
    Beauty= { firstYear = 1967 },
    Belief= { firstYear = 1982 },
    BigBiceps= { firstYear = 1984 },
    BlockoMagazine= { firstYear = 1987 },
    BluesnJazz= { firstYear = 1922 },
    Boink= { firstYear = 1925 },
    Brash= { firstYear = 1978 },
    Brief= { firstYear = 1928 },
    CabinFever= { firstYear = 1973 },
    CardGames= { firstYear = 1908 },
    Charm= { firstYear = 1961 },
    Checkmate= { firstYear = 1966 },
    ChristiansTogether= { firstYear = 1870 },
    CigarsCaviar= { firstYear = 1921 },
    ClassicBattles= { firstYear = 1944 },
    CodeWorld= { firstYear = 1979 },
    Collecting= { firstYear = 1921 },
    CompressedBooks= { firstYear = 1922 },
    CongressWatcher= { firstYear = 1972 },
    CustodialOperator= { firstYear = 1992 },
    DarkTales= { firstYear = 1923 },
    DigitalAdventurePower= { firstYear = 1983 },
    DragKings= { firstYear = 1978 },
    Economy= { firstYear = 1971 },
    Electron= { firstYear = 1960 },
    Elegant= { firstYear = 1954 },
    ElegantGirl= { firstYear = 1960 },
    EverydayMotorist= { firstYear = 1949 },
    ExecutiveLounge= { firstYear = 1957 },
    Extinguish= { firstYear = 1991 },
    FamilyCaring= { firstYear = 1990 },
    Figary= { firstYear = 1990 },
    Fine= { firstYear = 1969 },
    FineWine= { firstYear = 1989 },
    FlyingSaucerJournal= { firstYear = 1947 },
    FootballFrenzy= { firstYear = 1983 },
    Forces= { firstYear = 1968 },
    Fore= { firstYear = 1982 },
    ForeverLiving= { firstYear = 1989 },
    FowlIntentions= { firstYear = 1958 },
    Freewheelin= { firstYear = 1986 },
    FuturePaleontology= { firstYear = 1987 },
    GameZ= { firstYear = 1989 },
    GhostlyHauntings= { firstYear = 1991 },
    Greens= { firstYear = 1987 },
    GruesomeCrimeScenes= { firstYear = 1931 },
    HeySir= { firstYear = 1990 },
    HighFlyer= { firstYear = 1942 },
    HikingFootwear= { firstYear = 1987 },
    HollywoodNews= { firstYear = 1962 },
    HomeRun= { firstYear = 1955 },
    HospitalTechnology= { firstYear = 1982 },
    HouseholdFinances= { firstYear = 1986 },
    ImproveYourHouse= { firstYear = 1980 },
    IncredibleHeroes= { firstYear = 1911 },
    InFocus= { firstYear = 1971 },
    Inquire= { firstYear = 1933 },
    JokesJokes= { firstYear = 1967 },
    Jump= { firstYear = 1979 },
    KentuckyDriver= { firstYear = 1933 },
    KentuckyHorseRacing= { firstYear = 1899 },
    KentuckyLiberal= { firstYear = 1940 },
    KentuckyObserver= { firstYear = 1959 },
    KimsTanksandArmorMonthly= { firstYear = 1956 },
    KirrusComputing= { firstYear = 1990 },
    KoolKids= { firstYear = 1989 },
    Labyrinths= { firstYear = 1991 },
    LatestForensics= { firstYear = 1992 },
    Lifestyle= { firstYear = 1990 },
    SouthernLiteraryReview = { firstYear = 1911 },
    LouisvilleBusinessReview= { firstYear = 1919 },
    LouisvilleLaughter= { firstYear = 1939 },
    MajesticBigGame= { firstYear = 1923 },
    MalpracticeInsuranceMonthly= { firstYear = 1990 },
    MansHealth= { firstYear = 1986 },
    MarketsMonthly= { firstYear = 1958 },
    Me= { firstYear = 1989 },
    Merc= { firstYear = 1984 },
    ModernDance= { firstYear = 1990 },
    ModernTrains= { firstYear = 1925 },
    MonstrousTrucks= { firstYear = 1975 },
    MossyRock= { firstYear = 1967 },
    MotorcycleEnthusiast= { firstYear = 1950 },
    MoviesWeekly= { firstYear = 1934 },
    NationalCelebs= { firstYear = 1948 },
    NatureFacts= { firstYear = 1930 },
    Newsday= { firstYear = 1989 },
    Newton= { firstYear = 1956 },
    Numisatics= { firstYear = 1967 },
    OldWestLife= { firstYear = 1911 },
    OpenMind= { firstYear = 1953 },
    OSCCInsider= { firstYear = 1951 },
    PaleGnome= { firstYear = 1990 },
    Parentage= { firstYear = 1989 },
    Paws= { firstYear = 1988 },
    PhilatelyLately= { firstYear = 1990 },
    Photospread= { firstYear = 1986 },
    Piledriver= { firstYear = 1989 },
    AmericanPoet= { firstYear = 1905 },
    PoliceFiles= { firstYear = 1940 },
    Proletariat= { firstYear = 1917 },
    ReadingsMonthly= { firstYear = 1920 },
    RealEstateInvestment= { firstYear = 1982 },
    ReelinginandGear= { firstYear = 1979 },
    Revelations= { firstYear = 1970 },
    RockOut= { firstYear = 1980 },
    RunningLife= { firstYear = 1986 },
    RunningnGunning= { firstYear = 1978 },
    Scoped= { firstYear = 1977 },
    ScreenShriek= { firstYear = 1963 },
    SecondAmendment= { firstYear = 1990 },
    ShortsIllustrated= { firstYear = 1954 },
    SilverScreen= { firstYear = 1937 },
    Sixteen= { firstYear = 1944 },
    Skeptical= { firstYear = 1976 },
    SongandDance= { firstYear = 1921 },
    Sorbes= { firstYear = 1916 },
    SportsStats= { firstYear = 1900 },
    Sprinter= { firstYear = 1986 },
    StPatricksJournal= { firstYear = 1903 },
    StandYourGround= { firstYear = 1988 },
    StockTrends= { firstYear = 1983 },
    Style= { firstYear = 1957 },
    StyleLife= { firstYear = 1963 },
    SuspectsandWitnesses= { firstYear = 1929 },
    TakeaLife= { firstYear = 1990 },
    Telltale= { firstYear = 1989 },
    TheBiclops= { firstYear = 1984 },
    TheBigApple= { firstYear = 1925 },
    TheForeignReview= { firstYear = 1914 },
    TheNationalist= { firstYear = 1955 },
    TheWallStreetPost= { firstYear = 1923 },
    TheWorldWars= { firstYear = 1948 },
    Thresher= { firstYear = 1966 },
    TodaysBuilder= { firstYear = 1979 },
    TPower= { firstYear = 1985 },
    Trailbeaters= { firstYear = 1972 },
    TruckingHeaven= { firstYear = 1975 },
    TrueCrimeStories= { firstYear = 1954 },
    TrueSerialKillings= { firstYear = 1970 },
    TTRPG= { firstYear = 1987 },
    TwitchingWeekly= { firstYear = 1944 },
    UnpopularElectronics= { firstYear = 1954 },
    UnsoldStories= { firstYear = 1989 },
    UpperCrust= { firstYear = 1987 },
    UptoEleven= { firstYear = 1988 },
    Veteran= { firstYear = 1970 },
    VHSEnthusiast= { firstYear = 1988 },
    VitimaniaRx= { firstYear = 1966 },
    WatercraftandBikes= { firstYear = 1984 },
    WorldGeograph= { firstYear = 1888 },
    WorldMusic= { firstYear = 1909 },
    WorldTrade= { firstYear = 1920 },
    WWCInsider= { firstYear = 1987 },
    Y= { firstYear = 1990 },
    YourInvestmentGuide= { firstYear = 1986 },
}