SpecialLootSpawns = SpecialLootSpawns or {}
SpecialLootSpawns.ComicBooks = {
    "100BillionBC",
    "AbsoluteHooey",
    "AtomLizardAwakes",
    "AtomLizardAwakesAgain",
    "AtomLizardDestroysCities",
    "AtomLizardFarFutureStories",
    "AtomLizardTheDragonKingMedievalMayhem",
    "AtommanMiniatureMayhem",
    "BlastForce",
    "BlastForceUnleashed",
    "BlindmansBluff",
    "BloodyAxeofKarntheSlayer",
    "BratPensHouseofIdeas",
    "BravelyIntoPeril",
    "Bricklayer",
    "BrideOfTheCactus",
    "Bruiser",
    "Bruisers",
    "CactusETERNAL",
    "CaptainWoofCaninePilot",
    "ChildDetectiveTales",
    "Chuckle",
    "CommandoRaid",
    "Corpsebound",
    "CrimesoftheCentury",
    "CryptofInsanity",
    "CurseRyder",
    "DamselsDangers",
    "DangerHorse",
    "DarkdrivetheSorcererCar",
    "DeathoftheNightporter",
    "DenseAlloy",
    "DinoTrapper",
    "DinoTrapperVSAtomLizard",
    "DrApeJrGangExploresSpace",
    "DrApeScienceVigilante",
    "DrApeBattlesAtomLizard",
    "DrWerewolf",
    "DrWerewolfDrApeTechnologyHospitalShowdown",
    "DrWerewolfFullMoon",
    "DrWerewolfReturns",
    "DraculaHunters",
    "DraculaHuntersAgainstAtomLizard",
    "DraculaHuntersvsQueenVampire",
    "DrakeSteeleEscapeFromDracula",
    "DrakeSteeleEscapeFromTheDraculaHunters",
    "DrakeSteeleVampireDetective",
    "EncounterCritical",
    "EscapeFromPeril",
    "FalloftheSteelman",
    "FantasiesOfPower",
    "Farrago",
    "FasterThanLightspeed",
    "ForbiddenExperiments",
    "FrankenLad",
    "FrankenLadFrankenMutt",
    "FreedomEnforcers",
    "FromOutoftheShriekingMortuary",
    "FuriousFiveandScorpman",
    "FuriousFiveMeltdown",
    "Futurelords",
    "GammaRadiationChild",
    "GhostKids",
    "GladiatorAdventures",
    "GoreRide",
    "GorillaTrucker",
    "GorillaTruckers",
    "GreasyBikerStories",
    "GreenHawk",
    "GrossOut",
    "HeFrankenstein",
    "HeavyWater",
    "HisayosanDeathisLife",
    "HistoryUnbelieved",
    "HolyWitch",
    "Horseshoecrab",
    "Humanman",
    "HumanmanMeetsHumanwoman",
    "Humanwoman",
    "Iceblaze",
    "IckyTales",
    "Imbroglio",
    "JackieJayeTruthseeker",
    "JohnSpiralNuclearKerfuffle",
    "JohnSpiralSpyatLarge",
    "JohnSpiralTorpedoTubeTales",
    "JungleAdventure",
    "Kazusa",
    "KentuckyMutants",
    "KingRedwood",
    "KingRedwoodvsAtomLizard",
    "KitSequoiasTwoFists",
    "KitSequoiasMeetsKingRedwood",
    "KarntheDefeater",
    "KarnRelentless",
    "KarnTheSavageSorcererSlayingSpecial",
    "KarnvsMerlin",
    "LassoLady",
    "LassoLadyandNightporter",
    "LassoLadyandSteelman",
    "LassoLadyvsCthulhu",
    "LassoLadyFighttotheDeath",
    "MaidenCanada",
    "MayorAcademy",
    "MetalSpearQuest",
    "MonsterPresidents",
    "MillipedeKid",
    "Needleface",
    "Nightporter2020",
    "NightporterJr",
    "NightportervsSteelman",
    "NightporterYearZero",
    "NinjaAttack",
    "OilyRevenger",
    "OmegaDepartmentHauntedHargrave",
    "OmegaDepartmentMysteriousMantell",
    "Peacedrivers",
    "ThePincushion",
    "PTimeHunter",
    "PlasmaTeam",
    "PlasmaWoman",
    "PlutoMan",
    "ProfessorIdiot",
    "ProfessorIdiotBunglesAgain",
    "PUTRID",
    "QueenThunoraofLemuria",
    "QueenVampire",
    "ReanimatedGreenBerets",
    "ReturnoftheNightporter",
    "RevengeoftheStockbroker",
    "Rikoto",
    "RIPScorpman",
    "Robobattles",
    "RobotUnit",
    "SantasSecretAdventures",
    "SaucerSorcery",
    "ScorpmanandBlindman",
    "ScorpmanandtheZPeople",
    "ScorpmanDangerville",
    "ScorpmanTheDeathofDeeDerry",
    "SheFrankenstein",
    "SheFrankensteinSheNeanderthalTeamUp",
    "ShikokuMonogatari",
    "ShoggothsAttack",
    "ShoggothsAttackTheFinalWar",
    "ShoggothsAttackTheShoggothWar",
    "Shonen",
    "ShootingIrons",
    "SidekickAdventures",
    "SidekickAvengers",
    "SidekickCemetery",
    "SolarCalculator",
    "Soldierman",
    "SpaceWarlock",
    "StarAvengers",
	"SteelgrannyStories",
    "Steellady",
    "SteelladyGoestoMars",
    "SteelmanReturns",
    "SteelmanvsScorpmanvsTheNightporter",
    "SteelmanvsTheNightporter",
    "SteelmanForgedinFire",
    "SteelmanTheImpossibleSun",
    "Steelwedding",
    "StipulatorvsTerminatrix",
    "SwordsFireballs",
    "TheSwordfightingNurse",
    "TalesofMisfortune",
    "TalesofTheJewelThrone",
    "Tanktaur",
    "TechnologyHospital",
    "TeenSteelman",
    "TeenSurgeons",
    "TerminatrixVSAtomLizard",
    "TheBeePeople",
    "TheCactus",
    "TheCeresInvasion",
    "TheCryptofPain",
    "TheCurtain",
    "TheCrimefightingDogs",
    "TheDarkestNightporter",
    "TheFlummoxer",
    "TheForeman",
    "TheFuriousFive",
    "TheGhostBrawlers",
    "TheHyena",
    "TheImpossibleSteelman",
    "TheIncredibleScorpman",
    "TheLeopardToothyTales",
	"TheMagicHoodie",                
	"TheModerators",
    "TheModeratorsBeyondtheIcePalace",
    "TheModeratorsOldworldsNewWorld",
    "TheNewRisqueAdventuresofMerlin",
    "TheNewScorpman",
    "TheOmegaDepartmentArchive",
    "TheScavenger",
    "TheSevenSuns",
    "TheShortchanger",
    "TheSpitfightinDames",
    "TheStipulator",
    "TheStockbrokerDeadCatBounce",
    "TheStockbrokerNewInvestments",
    "TheTerminatrix",
    "TheChurl",
    "TheThompsonsHerbsNewCar",
    "TheThompsonsLesterGetsInTrouble",
    "TheThompsonsMarieTheTrainDriver",
    "TheUncouthSquad",
    "TheWarlockhammerOfTanglewood",
    "ThrillingDinosaurStories",
    "ThunoratheSheNeanderthal",
    "ToddlerPolice",
    "ToiletHumor",
    "TrueHauntings",
    "TrueMercenary",
    "TrueNinjaHistory",
    "Zpeople",
    "ZpeopleAttheNorthPole",
    "ZpeopleOutofTime",
    "ZpeopleTheLeopard",
    "Zoinks",
    "ZoinksAfterHoursUnabashed",
    "UMLAUT",
}
SpecialLootSpawns.ComicBookDetails = {
    ["100BillionBC"] = { issues  = 201, inPrint = true, },
    AbsoluteHooey = { issues  = 237, inPrint = false, },
    AtomLizardAwakes = { issues  = 3, inPrint = false, },
    AtomLizardAwakesAgain = { issues  = 6, inPrint = false, },
    AtomLizardDestroysCities = { issues  = 9, inPrint = false, },
    AtomLizardFarFutureStories = { issues  = 12, inPrint = true, },
    AtomLizardTheDragonKingMedievalMayhem = { issues  = 12, inPrint = true, },
    AtommanMiniatureMayhem = { issues  = 269, inPrint = true, },
    BlastForce = { issues  = 169, inPrint = false, },
    BlastForceUnleashed = { issues  = 59, inPrint = true, },
    BlindmansBluff = { issues  = 53, inPrint = false, },
    BloodyAxeofKarntheSlayer = { issues  = 132, inPrint = true, },
    BratPensHouseofIdeas = { issues  = 513, inPrint = false, },
    BravelyIntoPeril = { issues  = 174, inPrint = false, },
    Bricklayer = { issues  = 187, inPrint = false, },
    BrideOfTheCactus = { issues  = 13, inPrint = false, },
    Bruiser = { issues  = 216, inPrint = false, },
    Bruisers = { issues  = 32, inPrint = true, },
    CactusETERNAL = { issues  = 0, inPrint = false, },
    CaptainWoofCaninePilot = { issues  = 362, inPrint = true, },
    ChildDetectiveTales = { issues  = 317, inPrint = false, },
    Chuckle = { issues  = 534, inPrint = true, },
    CommandoRaid = { issues  = 212, inPrint = false, },
    Corpsebound = { issues  = 57, inPrint = true, },
    CrimesoftheCentury = { issues  = 100, inPrint = false, },
    CryptofInsanity = { issues  = 135, inPrint = false, },
    CurseRyder = { issues  = 116, inPrint = true, },
    DamselsDangers = { issues  = 72, inPrint = true, },
    DangerHorse = { issues  = 11, inPrint = true, },
    DarkdrivetheSorcererCar = { issues  = 120, inPrint = false, },
    DeathoftheNightporter = { issues  = 0, inPrint = false, },
    DenseAlloy = { issues  = 257, inPrint = true, },
    DinoTrapper = { issues  = 193, inPrint = false, },
    DinoTrapperVSAtomLizard = { issues  = 3, inPrint = true, },
    DrApeJrGangExploresSpace = { issues  = 35, inPrint = false, },
    DrApeScienceVigilante = { issues  = 358, inPrint = false, },
    DrApeBattlesAtomLizard = { issues  = 2, inPrint = false, },
    DrWerewolf = { issues  = 146, inPrint = false, },
    DrWerewolfDrApeTechnologyHospitalShowdown = { issues  = 0, inPrint = true, },
    DrWerewolfFullMoon = { issues  = 0, inPrint = true, },
    DrWerewolfReturns = { issues  = 26, inPrint = true, },
    DraculaHunters = { issues  = 42, inPrint = true, },
    DraculaHuntersAgainstAtomLizard = { issues  = 0, inPrint = true, },
    DraculaHuntersvsQueenVampire = { issues  = 2, inPrint = false, },
    DrakeSteeleEscapeFromDracula = { issues  = 3, inPrint = false, },
    DrakeSteeleEscapeFromTheDraculaHunters = { issues  = 2, inPrint = false, },
    DrakeSteeleVampireDetective = { issues  = 168, inPrint = true, },
    EncounterCritical = { issues  = 17, inPrint = false, },
    EscapeFromPeril = { issues  = 5, inPrint = false, },
    FalloftheSteelman = { issues  = 0, inPrint = false, },
    FantasiesOfPower = { issues  = 5, inPrint = false, },
    Farrago = { issues  = 127, inPrint = true, },
    FasterThanLightspeed = { issues  = 37, inPrint = true },
    ForbiddenExperiments = { issues  = 157, inPrint = false, },
    FrankenLad = { issues  = 53, inPrint = false, },
    FrankenLadFrankenMutt = { issues  = 11, inPrint = true, },
    FreedomEnforcers = { issues  = 53, inPrint = true, },
    FromOutoftheShriekingMortuary = { issues  = 382, inPrint = false, },
    FuriousFiveandScorpman = { issues  = 50, inPrint = true, },
    FuriousFiveMeltdown = { issues  = 6, inPrint = false, },
    Futurelords = { issues  = 23, inPrint = true, },
    GammaRadiationChild = { issues  = 173, inPrint = false, },
    GhostKids = { issues  = 428, inPrint = false, },
    GladiatorAdventures = { issues  = 195, inPrint = false, },
    GoreRide = { issues  = 32, inPrint = true, },
    GorillaTrucker = { issues  = 201, inPrint = true, },
    GorillaTruckers = { issues  = 84, inPrint = true, },
    GreasyBikerStories = { issues  = 315, inPrint = true, },
    GreenHawk = { issues  = 294, inPrint = true, },
    GrossOut = { issues  = 86, inPrint = true, },
    HeFrankenstein = { issues  = 26, inPrint = false, },
    HeavyWater = { issues  = 278, inPrint = true, },
    HisayosanDeathisLife = { issues  = 58, inPrint = false, },
    HistoryUnbelieved = { issues  = 284, inPrint = true, },
    HolyWitch = { issues  = 135, inPrint = true, },
    Horseshoecrab = { issues  = 17, inPrint = true, },
    Humanman = { issues  = 78, inPrint = false, },
    HumanmanMeetsHumanwoman = { issues  = 5, inPrint = true, },
    Humanwoman = { issues  = 315, inPrint = false, },
    Iceblaze = { issues  = 65, inPrint = true, },
    IckyTales = { issues  = 216, inPrint = false, },
    Imbroglio = { issues  = 61, inPrint = true, },
    JackieJayeTruthseeker = { issues  = 3, inPrint = false, },
    JohnSpiralNuclearKerfuffle = { issues  = 3, inPrint = false, },
    JohnSpiralSpyatLarge = { issues  = 158, inPrint = true, },
    JohnSpiralTorpedoTubeTales = { issues  = 3, inPrint = false, },
    JungleAdventure = { issues  = 236, inPrint = false, },
    Kazusa = { issues  = 32, inPrint = false, },
    KentuckyMutants = { issues  = 56, inPrint = true, },
    KingRedwood = { issues  = 144, inPrint = false, },
    KingRedwoodvsAtomLizard = { issues  = 0, inPrint = false, },
    KitSequoiasTwoFists = { issues  = 184, inPrint = false, },
    KitSequoiasMeetsKingRedwood = { issues  = 4, inPrint = true, },
    KarntheDefeater = { issues  = 267, inPrint = true, },
    KarnRelentless = { issues  = 53, inPrint = false, },
    KarnTheSavageSorcererSlayingSpecial = { issues  = 6, inPrint = false, },
    KarnvsMerlin = { issues  = 0, inPrint = false, },
    LassoLady = { issues  = 350, inPrint = true, },
    LassoLadyandNightporter = { issues  = 121, inPrint = true, },
    LassoLadyandSteelman = { issues  = 133, inPrint = true, },
    LassoLadyvsCthulhu = { issues  = 0, inPrint = false, },
    LassoLadyFighttotheDeath = { issues  = 12, inPrint = false, },
    MaidenCanada = { issues  = 235, inPrint = true, },
    MayorAcademy = { issues  = 92, inPrint = true, },
    MetalSpearQuest = { issues  = 108, inPrint = true, },
    MonsterPresidents = { issues  = 7, inPrint = true, },
    MillipedeKid = { issues  = 345, inPrint = false, },
    Needleface = { issues  = 41, inPrint = true, },
    Nightporter2020 = { issues  = 6, inPrint = false, },
    NightporterJr = { issues  = 16, inPrint = true, },
    NightportervsSteelman = { issues  = 3, inPrint = false, },
    NightporterYearZero = { issues  = 6, inPrint = false, },
    NinjaAttack = { issues  = 87, inPrint = true, },
    OilyRevenger = { issues  = 131, inPrint = true, },
    OmegaDepartmentHauntedHargrave = { issues  = 3, inPrint = false, },
    OmegaDepartmentMysteriousMantell = { issues  = 3, inPrint = false, },
    Peacedrivers = { issues  = 25, inPrint = true, },
    ThePincushion = { issues  = 213, inPrint = false, },
    PTimeHunter = { issues  = 33, inPrint = true, },
    PlasmaTeam = { issues  = 16, inPrint = false, },
    PlasmaWoman = { issues  = 139, inPrint = true, },
    PlutoMan = { issues  = 86, inPrint = false, },
    ProfessorIdiot = { issues  = 384, inPrint = false, },
    ProfessorIdiotBunglesAgain = { issues  = 8, inPrint = true, },
    PUTRID = { issues  = 65, inPrint = true, },
    QueenThunoraofLemuria = { issues  = 99, inPrint = true, },
    QueenVampire = { issues  = 167, inPrint = false, },
    ReanimatedGreenBerets = { issues  = 18, inPrint = true, },
    ReturnoftheNightporter = { issues  = 3, inPrint = false, },
    RevengeoftheStockbroker = { issues  = 0, inPrint = false, },
    Rikoto = { issues  = 0, inPrint = false, },
    RIPScorpman = { issues  = 6, inPrint = false, },
    Robobattles = { issues  = 38, inPrint = true, },
    RobotUnit = { issues  = 217, inPrint = true, },
    SantasSecretAdventures = { issues  = 75, inPrint = false, },
    SaucerSorcery = { issues  = 0, inPrint = false, },
    ScorpmanandBlindman = { issues  = 8, inPrint = false, },
    ScorpmanandtheZPeople = { issues  = 23, inPrint = true, },
    ScorpmanDangerville = { issues  = 6, inPrint = false, },
    ScorpmanTheDeathofDeeDerry = { issues  = 3, inPrint = false, },
    SheFrankenstein = { issues  = 301, inPrint = true, },
    SheFrankensteinSheNeanderthalTeamUp = { issues  = 0, inPrint = false, },
    ShikokuMonogatari = { issues  = 013, inPrint = false, },
    ShoggothsAttack = { issues  = 0, inPrint = false, },
    ShoggothsAttackTheFinalWar = { issues  = 6, inPrint = true, },
    ShoggothsAttackTheShoggothWar = { issues  = 3, inPrint = false, },
    Shonen = { issues  = 153, inPrint = false, },
    ShootingIrons = { issues  = 138, inPrint = false, },
    SidekickAdventures = { issues  = 85, inPrint = false, },
    SidekickAvengers = { issues  = 12, inPrint = false, },
    SidekickCemetery = { issues  = 0, inPrint = false, },
    SolarCalculator = { issues  = 46, inPrint = true, },
    Soldierman = { issues  = 350, inPrint = true, },
    SpaceWarlock = { issues  = 139, inPrint = true, },
    StarAvengers = { issues  = 0, inPrint = false, },
	SteelgrannyStories = { issues  = 50, inPrint = false, },
    Steellady = { issues  = 200, inPrint = true, },
    SteelladyGoestoMars = { issues  = 20, inPrint = false, },
    SteelmanReturns = { issues  = 12, inPrint = false, },
    SteelmanvsScorpmanvsTheNightporter = { issues  = 3, inPrint = false, },
    SteelmanvsTheNightporter = { issues  = 3, inPrint = false, },
    SteelmanForgedinFire = { issues  = 0, inPrint = false, },
    SteelmanTheImpossibleSun = { issues  = 12, inPrint = false, },
    Steelwedding = { issues  = 3, inPrint = false, },
    StipulatorvsTerminatrix = { issues  = 3, inPrint = false, },
    SwordsFireballs = { issues  = 83, inPrint = true, },
    TheSwordfightingNurse = { issues  = 54, inPrint = false, },
    TalesofMisfortune = { issues  = 184, inPrint = false, },
    TalesofTheJewelThrone = { issues  = 4, inPrint = false, },
    Tanktaur = { issues  = 25, inPrint = true, },
    TechnologyHospital = { issues  = 109, inPrint = false, },
    TeenSteelman = { issues  = 82, inPrint = true, },
    TeenSurgeons = { issues  = 158, inPrint = false, },
    TerminatrixVSAtomLizard = { issues  = 0, inPrint = false, },
    TheBeePeople = { issues  = 0, inPrint = false, },
    TheCactus = { issues  = 174, inPrint = false, },
    TheCeresInvasion = { issues  = 8, inPrint = false, },
    TheCryptofPain = { issues  = 294, inPrint = false, },
    TheCurtain = { issues  = 32, inPrint = true, },
    TheCrimefightingDogs = { issues  = 175, inPrint = false, },
    TheDarkestNightporter = { issues  = 0, inPrint = false, },
    TheFlummoxer = { issues  = 53, inPrint = true, },
    TheForeman = { issues  = 165, inPrint = false, },
    TheFuriousFive = { issues  = 184, inPrint = true, },
    TheGhostBrawlers = { issues  = 71, inPrint = true, },
    TheHyena = { issues  = 46, inPrint = true, },
    TheImpossibleSteelman = { issues  = 398, inPrint = true, },
    TheIncredibleScorpman = { issues  = 206, inPrint = true, },
    TheLeopardToothyTales = { issues  = 165, inPrint = true, },
	TheMagicHoodie = { issues  = 0, inPrint = false, },                
	TheModerators = { issues  = 165, inPrint = true, },
    TheModeratorsBeyondtheIcePalace = { issues  = 3, inPrint = false, },
    TheModeratorsOldworldsNewWorld = { issues  = 12, inPrint = false, },
    TheNewRisqueAdventuresofMerlin = { issues  = 21, inPrint = false, },
    TheNewScorpman = { issues  = 15, inPrint = false, },
    TheOmegaDepartmentArchive = { issues  = 78, inPrint = true, },
    TheScavenger = { issues  = 150, inPrint = true, },
    TheSevenSuns = { issues  = 77, inPrint = false, },
    TheShortchanger = { issues  = 37, inPrint = true, },
    TheSpitfightinDames = { issues  = 184, inPrint = true, },
    TheStipulator = { issues  = 130, inPrint = true, },
    TheStockbrokerDeadCatBounce = { issues  = 3, inPrint = false, },
    TheStockbrokerNewInvestments = { issues  = 12, inPrint = false, },
    TheTerminatrix = { issues  = 83, inPrint = true, },
    TheChurl = { issues  = 30, inPrint = false, },
    TheThompsonsHerbsNewCar = { issues  = 0, inPrint = false, },
    TheThompsonsLesterGetsInTrouble = { issues  = 0, inPrint = false, },
    TheThompsonsMarieTheTrainDriver = { issues  = 0, inPrint = false, },
    TheUncouthSquad = { issues  = 40, inPrint = true, },
    TheWarlockhammerOfTanglewood = { issues  = 33, inPrint = false, },
    ThrillingDinosaurStories = { issues  = 204, inPrint = false, },
    ThunoratheSheNeanderthal = { issues  = 267, inPrint = false, },
    ToddlerPolice = { issues  = 38, inPrint = true, },
    ToiletHumor = { issues  = 214, inPrint = true, },
    TrueHauntings = { issues  = 157, inPrint = true, },
    TrueMercenary = { issues  = 193, inPrint = true, },
    TrueNinjaHistory = { issues  = 45, inPrint = false, },
    Zpeople = { issues  = 216, inPrint = true, },
    ZpeopleAttheNorthPole = { issues  = 6, inPrint = false, },
    ZpeopleOutofTime = { issues  = 6, inPrint = false, },
    ZpeopleTheLeopard = { issues  = 3, inPrint = false, },
    Zoinks = { issues  = 315, inPrint = true, },
    ZoinksAfterHoursUnabashed = { issues  = 0, inPrint = false, },
    UMLAUT = { issues  = 138, inPrint = true, },
}