---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RJ.
--- DateTime: 10/5/2023 9:44 AM
---

CAnimals_Interact = {};

-- look to pet the nearest animal by pressing the context key
-- if an item is equipped and can be used on an animal (shear to shear a sheep, bucket to milk a cow..) do that instead
CAnimals_Interact.onKeyPress = function(key)
    if not getCore():isKey("Interact", key) then return end
    local player = getSpecificPlayer(0)
    if player:getVehicle() then return end
    if not player:isAiming() then return end
    if player:hasTimedActions() then return end
    local dir = player:getDir()
    -- local index = player:getPlayerNum()
    local adjSquare = player:getSquare():getAdjacentSquare(dir)
    if not adjSquare:getCanSee(player:getPlayerNum()) then return end
    -- get the animals present on the player's sq first, if nothing is found, look for animals on the square he's looking
    local animals = player:getSquare():getAnimals();
    if animals:isEmpty() then
        animals = adjSquare:getAnimals();
    end
    if animals:isEmpty() then return; end
    local animal = animals:get(0);
    local sq = getSquare(animal:getX(), animal:getY(), animal:getZ());
    if not luautils.walkAdj(player, sq) then return; end
    local item = player:getPrimaryHandItem()

    local milk = item and item:hasTag("BucketEmpty") and animal:readyToBeMilked();
    local shear = item and item:hasTag("Shear") and animal:readyToBeSheared();
    local pet = animal:canBePet();

    player:setIsAiming(false);

    if milk then
        AnimalContextMenu.onMilkAnimal(animal, player, item);
        return;
    end

    if shear then
        if instanceof(shear, "DrainableComboItem") and shear:getCurrentUsesFloat() <= 0 then
            return;
        end
        AnimalContextMenu.onShearAnimal(animal, player, item);
        return;
    end

    if pet then
        AnimalContextMenu.onPetAnimal(animal, player);
        return;
    end
end

Events.OnKeyPressed.Add(CAnimals_Interact.onKeyPress);