---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RJ.
--- DateTime: 10/5/2023 9:44 AM
---

CButcherHook_Interact = {};

CButcherHook_Interact.onKeyPress = function(key)
    if not getCore():isKey("Interact", key) then return end
    local player = getSpecificPlayer(0)
    if player:getVehicle() then return end
    if player:hasTimedActions() then return end
    local dir = player:getDir()
    -- local index = player:getPlayerNum()
    local adjSquare = player:getSquare():getAdjacentSquare(dir)
    if not adjSquare:getCanSee(player:getPlayerNum()) then return end
    -- get the hook present on the player's sq first, if nothing is found, look for animals on the square he's looking
    local hook = player:getSquare():getButcherHook();
    if not hook then
        hook = adjSquare:getButcherHook();
    end
    if not hook then return; end
    local sq = getSquare(hook:getX(), hook:getY(), hook:getZ());
    if not luautils.walkAdj(player, sq) then return; end

    ISTimedActionQueue.add(ISOpenButcherHookUI:new(player, hook));
end

Events.OnKeyPressed.Add(CButcherHook_Interact.onKeyPress);