---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RJ.
--- DateTime: 10/5/2023 9:44 AM
---

CHutch_Interact = {};

-- look to pet the nearest animal by pressing the context key
-- if an item is equipped and can be used on an animal (shear to shear a sheep, bucket to milk a cow..) do that instead
CHutch_Interact.onKeyPress = function(key)
    if not getCore():isKey("Interact", key) then return end
    local player = getSpecificPlayer(0)
    local shiftPressed = isKeyDown(Keyboard.KEY_LSHIFT);
    if player:getVehicle() then return end
    if player:hasTimedActions() then return end
    local dir = player:getDir()
    -- local index = player:getPlayerNum()
    local adjSquare = player:getSquare():getAdjacentSquare(dir)
    if not adjSquare and not adjSquare:getCanSee(player:getPlayerNum()) then return end

    -- i'm gonna try to get the hutch around the player, to its left & right dir too

    local hutch = IsoHutch.getHutch(player:getSquare():getX(), player:getSquare():getY(), player:getSquare():getZ())
    if not hutch then
        hutch = IsoHutch.getHutch(adjSquare:getX(), adjSquare:getY(), adjSquare:getZ())
    end

    if not hutch then
        local dirLeft = dir:RotLeft();
        adjSquare = player:getSquare():getAdjacentSquare(dirLeft)
        if not adjSquare and not adjSquare:getCanSee(player:getPlayerNum()) then return end
        hutch = IsoHutch.getHutch(adjSquare:getX(), adjSquare:getY(), adjSquare:getZ())
    end

    if not hutch then
        local dirRight = dir:RotRight();
        adjSquare = player:getSquare():getAdjacentSquare(dirRight)
        if not adjSquare and not adjSquare:getCanSee(player:getPlayerNum()) then return end
        hutch = IsoHutch.getHutch(adjSquare:getX(), adjSquare:getY(), adjSquare:getZ())
    end

    if hutch then
        hutch = hutch:getHutch();
        if shiftPressed then
            player:setIsAiming(false);
            ISTimedActionQueue.add(ISGetHutchInfo:new(player, hutch))
        else
            player:setIsAiming(false);
            ISTimedActionQueue.add(ISToggleHutchDoor:new(player, hutch))
        end
    end
end

Events.OnKeyPressed.Add(CHutch_Interact.onKeyPress);