biome_map_config = {
    { pixel = 0, zone = "Water" },
    --{ pixel = 34, zone = "Water" },
    { pixel = 45, zone = "WaterNoFish" },
    { pixel = 64, zone = "ForagingNav" },
    { pixel = 102, zone = "TrailerPark" },
    { pixel = 115, biome = "townhouse", zone = "TownZone" },
    { pixel = 128, zone = "Farm" },
    { pixel = 141, zone = "FarmLand" },
    { pixel = 171, biome = "vegitation", zone = "Vegitation" },
    { pixel = 153, biome = "ph_forest", zone = "Forest" },
    { pixel = 166, biome = "phmix_forest", ore = "map_forest", zone = "Forest" },
    { pixel = 179, biome = "pr_forest", ore = "map_forest", zone = "Forest" },
    { pixel = 192, biome = "farmmix_forest", ore = "map_forest", zone = "Forest" },
    { pixel = 204, biome = "farm_forest", zone = "Forest" },
    { pixel = 217, biome = "birch_forest", ore = "map_forest", zone = "Forest" },
    { pixel = 230, biome = "birchmix_forest", ore = "map_forest", zone = "Forest" },
    { pixel = 243, biome = "organic_forest", ore = "map_forest", zone = "Forest" },
    { pixel = 255, biome = "primary_forest", ore = "map_deep_forest", zone = "DeepForest" },
}