---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zacco.
--- DateTime: 5/08/2025 1:21 pm
---

LuaTableUtil = {};

function LuaTableUtil:insertUnique(list, element)
    if LuaTableUtil:contains(list, element) then
        return list
    end

    table.insert(list, element)

    return list;
end

function LuaTableUtil:contains(list, element)
    if not list then
        return false
    end

    for i=1, #list do
        local e = list[i];
        if e == element then
            return true
        end
    end

    return false
end