--[[---------------------------------------------
-------------------------------------------------
--
-- generateInsectsDefs
--
-- eris
--
-------------------------------------------------
--]]---------------------------------------------

require "Foraging/forageDefinitions";

local function generateInsectsDefs()
	local insects = {
		Cricket = {
			type = "Base.Cricket",
			skill = 0,
			xp = 5,
			rainChance = 50,
			snowChance = -100,
			nightChance = 100,
			categories = { "Insects", "FishBait" },
			zones = {
				Forest      = 10,
				DeepForest  = 10,
				Vegitation  = 10,
				FarmLand    = 10,
				Farm        = 10,
				TrailerPark = 10,
				TownZone    = 10,
				ForagingNav = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			malusMonths = { 3, 4 },
			forceOutside = false,
			canBeAboveFloor = true,
		},
		Grasshopper = {
			type = "Base.Grasshopper",
			skill = 0,
			xp = 5,
			rainChance = 20,
			snowChance = -100,
			dayChance = 100,
			categories = { "Insects", "FishBait" },
			zones = {
				Forest      = 10,
				DeepForest  = 10,
				Vegitation  = 10,
				FarmLand    = 10,
				Farm        = 10,
				TrailerPark = 10,
				TownZone    = 10,
				ForagingNav = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 6, 7, 8 },
			malusMonths = { 3, 4 },
			forceOutside = false,
			canBeAboveFloor = true,
		},
		Cockroach = {
			type = "Base.Cockroach",
			skill = 0,
			xp = 5,
			rainChance = 10,
			snowChance = -20,
			nightChance = 100,
			categories = { "Insects", "FishBait" },
			zones = {
				Forest      = 10,
				DeepForest  = 10,
				Vegitation  = 10,
				FarmLand    = 10,
				Farm        = 10,
				TrailerPark = 10,
				TownZone    = 10,
				ForagingNav = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			malusMonths = { 3, 4 },
			forceOutside = false,
			canBeAboveFloor = true,
		},
		Pillbug = {
			type = "Base.Pillbug",
			skill = 0,
			xp = 5,
			rainChance = 10,
			snowChance = -20,
			nightChance = 100,
			categories = { "Insects", "FishBait" },
			zones = {
				Forest      = 3,
				DeepForest  = 3,
				Vegitation  = 3,
				FarmLand    = 3,
				Farm        = 3,
				TrailerPark = 3,
				TownZone    = 3,
				ForagingNav = 3,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			malusMonths = { 3, 4 },
			forceOutside = false,
			canBeAboveFloor = true,
		},
		Centipede = {
			type = "Base.Centipede",
			skill = 0,
			xp = 5,
			rainChance = 10,
			snowChance = -20,
			nightChance = 100,
			categories = { "Insects", "FishBait" },
			zones = {
				Forest      = 3,
				DeepForest  = 3,
				Vegitation  = 3,
				FarmLand    = 3,
				Farm        = 3,
				TrailerPark = 3,
				TownZone    = 3,
				ForagingNav = 3,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			malusMonths = { 3, 4 },
			forceOutside = false,
			canBeAboveFloor = true,
		},
		Centipede2 = {
			type = "Base.Centipede2",
			skill = 0,
			xp = 5,
			rainChance = 10,
			snowChance = -20,
			nightChance = 100,
			categories = { "Insects", "FishBait" },
			zones = {
				Forest      = 3,
				DeepForest  = 3,
				Vegitation  = 3,
				FarmLand    = 3,
				Farm        = 3,
				TrailerPark = 3,
				TownZone    = 3,
				ForagingNav = 3,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			malusMonths = { 3, 4 },
			forceOutside = false,
			canBeAboveFloor = true,
		},
		Millipede = {
			type = "Base.Millipede",
			skill = 0,
			xp = 5,
			rainChance = 10,
			snowChance = -20,
			nightChance = 100,
			categories = { "Insects", "FishBait" },
			zones = {
				Forest      = 3,
				DeepForest  = 3,
				Vegitation  = 3,
				FarmLand    = 3,
				Farm        = 3,
				TrailerPark = 3,
				TownZone    = 3,
				ForagingNav = 3,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			malusMonths = { 3, 4 },
			forceOutside = false,
			canBeAboveFloor = true,
		},
		Millipede2 = {
			type = "Base.Millipede2",
			skill = 0,
			xp = 5,
			rainChance = 10,
			snowChance = -20,
			nightChance = 100,
			categories = { "Insects", "FishBait" },
			zones = {
				Forest      = 3,
				DeepForest  = 3,
				Vegitation  = 3,
				FarmLand    = 3,
				Farm        = 3,
				TrailerPark = 3,
				TownZone    = 3,
				ForagingNav = 3,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			malusMonths = { 3, 4 },
			forceOutside = false,
			canBeAboveFloor = true,
		},
		AmericanLadyCaterpillar = {
			type = "Base.AmericanLadyCaterpillar",
			skill = 0,
			xp = 5,
			rainChance = 10,
			snowChance = -20,
			nightChance = 100,
			categories = { "Insects", "FishBait" },
			zones = {
				Forest      = 3,
				DeepForest  = 3,
				Vegitation  = 3,
				FarmLand    = 3,
				Farm        = 3,
				TrailerPark = 3,
				TownZone    = 3,
				ForagingNav = 3,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			malusMonths = { 3, 4 },
			forceOutside = false,
			canBeAboveFloor = true,
		},
		BandedWoolyBearCaterpillar = {
			type = "Base.BandedWoolyBearCaterpillar",
			skill = 0,
			xp = 5,
			rainChance = 10,
			snowChance = -20,
			nightChance = 100,
			categories = { "Insects", "FishBait" },
			zones = {
				Forest      = 3,
				DeepForest  = 3,
				Vegitation  = 3,
				FarmLand    = 3,
				Farm        = 3,
				TrailerPark = 3,
				TownZone    = 3,
				ForagingNav = 3,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			malusMonths = { 3, 4 },
			forceOutside = false,
			canBeAboveFloor = true,
		},
		MonarchCaterpillar = {
			type = "Base.MonarchCaterpillar",
			skill = 0,
			xp = 5,
			rainChance = 10,
			snowChance = -20,
			nightChance = 100,
			categories = { "Insects", "FishBait" },
			zones = {
				Forest      = 3,
				DeepForest  = 3,
				Vegitation  = 3,
				FarmLand    = 3,
				Farm        = 3,
				TrailerPark = 3,
				TownZone    = 3,
				ForagingNav = 3,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			malusMonths = { 3, 4 },
			forceOutside = false,
			canBeAboveFloor = true,
		},
		SilkMothCaterpillar = {
			type = "Base.SilkMothCaterpillar",
			skill = 0,
			xp = 5,
			rainChance = 10,
			snowChance = -20,
			nightChance = 100,
			categories = { "Insects", "FishBait" },
			zones = {
				Forest      = 3,
				DeepForest  = 3,
				Vegitation  = 3,
				FarmLand    = 3,
				Farm        = 3,
				TrailerPark = 3,
				TownZone    = 3,
				ForagingNav = 3,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			malusMonths = { 3, 4 },
			forceOutside = false,
			canBeAboveFloor = true,
		},
		SwallowtailCaterpillar = {
			type = "Base.SwallowtailCaterpillar",
			skill = 0,
			xp = 5,
			rainChance = 10,
			snowChance = -20,
			nightChance = 100,
			categories = { "Insects", "FishBait" },
			zones = {
				Forest      = 3,
				DeepForest  = 3,
				Vegitation  = 3,
				FarmLand    = 3,
				Farm        = 3,
				TrailerPark = 3,
				TownZone    = 3,
				ForagingNav = 3,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			malusMonths = { 3, 4 },
			forceOutside = false,
			canBeAboveFloor = true,
		},
		Termites = {
			type = "Base.Termites",
			skill = 0,
			xp = 5,
			rainChance = 10,
			snowChance = -20,
			nightChance = 100,
			categories = { "Insects", "FishBait" },
			zones = {
				Forest      = 3,
				DeepForest  = 3,
				Vegitation  = 3,
				FarmLand    = 3,
				Farm        = 3,
				TrailerPark = 3,
				TownZone    = 3,
				ForagingNav = 3,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			malusMonths = { 3, 4 },
			forceOutside = false,
			canBeAboveFloor = true,
		},
		SawflyLarva = {
			type = "Base.SawflyLarva",
			skill = 0,
			xp = 5,
			rainChance = 10,
			snowChance = -20,
			nightChance = 100,
			categories = { "Insects", "FishBait" },
			zones = {
				Forest      = 3,
				DeepForest  = 3,
				Vegitation  = 3,
				FarmLand    = 3,
				Farm        = 3,
				TrailerPark = 3,
				TownZone    = 3,
				ForagingNav = 3,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			malusMonths = { 3, 4 },
			forceOutside = false,
			canBeAboveFloor = true,
		},
	};
	for itemName, itemDef in pairs(insects) do
		forageDefs[itemName] = itemDef;
	end;
end

generateInsectsDefs();