--[[---------------------------------------------
-------------------------------------------------
--
-- generateJunkDefs
--
-- eris
--
-------------------------------------------------
--]]---------------------------------------------

require "Foraging/forageDefinitions";
require "Foraging/forageSystem";

local function generateJunkDefs()
	--this category contains some of the very rare and/or interesting items other survivors have lost or thrown away
	--see also: Trash.lua
	local junkItems = {
		common = {
			chance = 50,
			xp = 2,
			categories = { "Junk", "Trash" },
			items = {
				Battery                 = "Base.Battery",
				Book                    = "Base.Book",
				Bowl                    = "Base.Bowl",
				BurlapPiece             = "Base.BurlapPiece",
				CleaningLiquid2        	= "Base.CleaningLiquid2",
				Clipboard         		= "Base.Clipboard",
				ComicBook               = "Base.ComicBook",
				Hinge                   = "Base.Hinge",
				MagazineCrossword       = "Base.MagazineCrossword",
				MagazineWordsearch      = "Base.MagazineWordsearch",
				Paperclip               = "Base.Paperclip",
				PaperclipBox            = "Base.PaperclipBox",
				Pot                     = "Base.Pot",
				ScrewsBox               = "Base.ScrewsBox",
				SheetMetal              = "Base.SheetMetal",
				SmallSheetMetal         = "Base.SmallSheetMetal",
				TVMagazine     			= "Base.TVMagazine",
				Crayons                 = "Base.Crayons",
				Journal                 = "Base.Journal",
				Magazine                = "Base.Magazine",
				Nails                   = "Base.Nails",
				Notebook                = "Base.Notebook",
			},
		},
		uncommon = {
			chance = 30,
			xp = 5,
			categories = { "Junk", "Trash" },
			items = {
				Bag_Satchel             = "Base.Bag_Satchel",
				BlowTorch               = "Base.BlowTorch",
				Calculator              = "Base.Calculator",
				Candle                  = "Base.Candle",
				Cooler                  = "Base.Cooler",
				EmptySandbag            = "Base.EmptySandbag",
				Eraser                  = "Base.Eraser",
				FirstAidKit             = "Base.FirstAidKit",
				FishingNet              = "Base.FishingNet",
				Handbag                 = "Base.Handbag",
				Lunchbox                = "Base.Lunchbox",
				Lunchbox2               = "Base.Lunchbox2",
				Purse                   = "Base.Purse",
				Saw                     = "Base.Saw",
				Soap2                 	= "Base.Soap2",
				Suitcase                = "Base.Suitcase",
				Toolbox                 = "Base.Toolbox",
				Tote                    = "Base.Tote",
				Twine      				= "Base.Twine",
			},
		},
		unlikely = {
			chance = 10,
			xp = 10,
			categories = { "Junk" , "Trash" },
			items = {
				ArmorMag1               = "Base.ArmorMag1",
				ArmorMag1               = "Base.ArmorMag2",
				ArmorMag1               = "Base.ArmorMag3",
				ArmorMag1               = "Base.ArmorMag4",
				ArmorMag1               = "Base.ArmorMag5",
				ArmorMag1               = "Base.ArmorMag6",
				ArmorMag1               = "Base.ArmorMag7",
				Bag_BowlingBallBag      = "Base.Bag_BowlingBallBag",
				Bag_GolfBag             = "Base.Bag_GolfBag",
				Bag_Schoolbag           = "Base.Bag_Schoolbag",
				CigaretteSingle			= "Base.CigaretteSingle",
				CookingMag1             = "Base.CookingMag1",
				CookingMag2             = "Base.CookingMag2",
				CookingMag3             = "Base.CookingMag3",
				CookingMag4             = "Base.CookingMag4",
				CookingMag5             = "Base.CookingMag5",
				CookingMag6             = "Base.CookingMag6",
				ElectronicsMag1         = "Base.ElectronicsMag1",
				ElectronicsMag2         = "Base.ElectronicsMag2",
				ElectronicsMag3         = "Base.ElectronicsMag3",
				ElectronicsMag4         = "Base.ElectronicsMag4",
				ElectronicsMag5         = "Base.ElectronicsMag5",
				EngineerMagazine1       = "Base.EngineerMagazine1",
				EngineerMagazine2       = "Base.EngineerMagazine2",
				FarmingMag1             = "Base.FarmingMag1",
				FarmingMag2             = "Base.FarmingMag2",
				FarmingMag4             = "Base.FarmingMag4",
				FishingLine             = "Base.FishingLine",
				FishingMag1             = "Base.FishingMag1",
				FishingMag2             = "Base.FishingMag2",
				Flightcase              = "Base.Flightcase",
				Guitarcase              = "Base.Guitarcase",
				HuntingMag1             = "Base.HuntingMag1",
				HuntingMag2             = "Base.HuntingMag2",
				HuntingMag3             = "Base.HuntingMag3",
				LightBulb          		= "Base.LightBulb",
				LightBulbBlue          	= "Base.LightBulbBlue",
				LightBulbCyan          	= "Base.LightBulbCyan",
				LightBulbGreen          = "Base.LightBulbGreen",
				LightBulbMagenta        = "Base.LightBulbMagenta",
				LightBulbOrange        	= "Base.LightBulbOrange",
				LightBulbPink        	= "Base.LightBulbPink",
				LightBulbPurple        	= "Base.LightBulbPurple",
				LightBulbRed        	= "Base.LightBulbRed",
				LightBulbYellow        	= "Base.LightBulbYellow",
				MarchRidgeMap           = "Base.MarchRidgeMap",
				MetalworkMag1           = "Base.MetalworkMag1",
				MetalworkMag2           = "Base.MetalworkMag2",
				MetalworkMag3           = "Base.MetalworkMag3",
				MetalworkMag4           = "Base.MetalworkMag4",
				MuldraughMap            = "Base.MuldraughMap",
	            PrimitiveToolMag1       = "Base.PrimitiveToolMag1",
	            PrimitiveToolMag2       = "Base.PrimitiveToolMag2",
				RailroadSpike           = "Base.RailroadSpike",
				RailroadTrack      		= "Base.RailroadTrack",
				RailroadTrackPiece 		= "Base.RailroadTrackPiece",
				RiversideMap            = "Base.RiversideMap",
				RosewoodMap             = "Base.RosewoodMap",
				SewingKit               = "Base.SewingKit",
				SmithingMag1            = "Base.SmithingMag1",
				SmithingMag2            = "Base.SmithingMag2",
				SmithingMag3            = "Base.SmithingMag3",
				SmithingMag4            = "Base.SmithingMag4",
				SmithingMag5            = "Base.SmithingMag5",
				SmithingMag6            = "Base.SmithingMag6",
				SmithingMag7            = "Base.SmithingMag7",
				SmithingMag8            = "Base.SmithingMag8",
				SmithingMag9            = "Base.SmithingMag9",
				SmithingMag10           = "Base.SmithingMag10",
				SmithingMag11           = "Base.SmithingMag11",
				TongueDepressor        	= "Base.TongueDepressor",
				Tsquare        			= "Base.Tsquare",
				UmbrellaBlack           = "Base.UmbrellaBlack",
				UmbrellaBlue            = "Base.UmbrellaBlue",
				UmbrellaRed             = "Base.UmbrellaRed",
				UmbrellaWhite           = "Base.UmbrellaWhite",
				WeaponMag1              = "Base.WeaponMag1",
				WeaponMag2              = "Base.WeaponMag2",
				WeaponMag3              = "Base.WeaponMag3",
				WeaponMag4              = "Base.WeaponMag4",
				WeaponMag5              = "Base.WeaponMag5",
				WeaponMag6              = "Base.WeaponMag6",
				WestpointMap            = "Base.WestpointMap",
			},
		},
		rare = {
			chance = 7,
			xp = 20,
			categories = { "Junk" },
			items = {
				BBQStarterFluid			= "Base.BBQStarterFluid",
				BakingPan				= "Base.BakingPan",
				BakingTray				= "Base.BakingTray",
				BarbedWire				= "Base.BarbedWire",
				BastingBrush			= "Base.BastingBrush",
				BoltCutters				= "Base.BoltCutters",
				BottleOpener			= "Base.BottleOpener",
				BottleOpener_Keychain	= "Base.BottleOpener_Keychain",
				Charcoal                = "Base.Charcoal",
				Cigar             		= "Base.Cigar",
				CigarettePack	  		= "Base.CigarettePack",
				CigaretteRolled	  		= "Base.CigaretteRolled",
				CigaretteRollingPapers	= "Base.CigaretteRollingPapers",
				Cigarillo				= "Base.Cigarillo",
				CordlessPhone			= "Base.CordlessPhone",
				Cork					= "Base.Cork",
				EngineParts             = "Base.EngineParts",
				Extinguisher            = "Base.Extinguisher",
				Handle       			= "Base.Handle",
				Ladle       			= "Base.Ladle",
				Laser       			= "Base.Laser",
				LighterFluid       		= "Base.LighterFluid",
				Lipstick       			= "Base.Lipstick",
				Loupe       			= "Base.Loupe",
				LugWrench       		= "Base.LugWrench",
				Lunchbag       			= "Base.Lunchbag",
				MarkerBlack				= "Base.MarkerBlack",
				MarkerBlue				= "Base.MarkerBlue",
				MarkerGreen				= "Base.MarkerGreen",
				MarkerRed				= "Base.MarkerRed",
				Matchbox				= "Base.Matchbox",
				MeasuringTape			= "Base.MeasuringTape",
				MenuCard				= "Base.MenuCard",
				PetrolCan               = "Base.PetrolCan",
				PlasterPowder       	= "Base.PlasterPowder",
				Pliers       			= "Base.Pliers",
				Pocketwatch       		= "Base.Pocketwatch",
				PokerChips       		= "Base.PokerChips",
				PoolBall       			= "Base.PoolBall",
				PropaneTank				= "Base.PropaneTank",
				Ratchet       			= "Base.Ratchet",
				Razor       			= "Base.Razor",
				Saxophone       		= "Base.Saxophone",
				Speaker       			= "Base.Speaker",
				Sponge					= "Base.Sponge",
				Spork					= "Base.Spork",
				Stapler					= "Base.Stapler",
				Staples					= "Base.Staples",
				SteelWool				= "Base.SteelWool",
				Strainer       			= "Base.Strainer",
				String       			= "Base.String",
				Tissue       			= "Base.Tissue",
				Tongs       			= "Base.Tongs",
				Toothpaste       		= "Base.Toothpaste",
				Wallet       			= "Base.Wallet",
				WateredCan				= "Base.WateredCan",
				Whisk       			= "Base.Whisk",
				Wrench		       		= "Base.Wrench",
			},
		},
		epic = {
			chance = 3,
			xp = 30,
			categories = { "Junk" },
			items = {
				AlarmClock2				= "Base.AlarmClock2",
				AlarmClock2				= "Base.AlarmClock2",
				Amplifier				= "Base.Amplifier",
				Bellows					= "Base.Bellows",
				BookBlacksmith1			= "Base.BookBlacksmith1",
				BookBlacksmith2			= "Base.BookBlacksmith2",
				BookBlacksmith3			= "Base.BookBlacksmith3",
				BookBlacksmith4			= "Base.BookBlacksmith4",
				BookBlacksmith5			= "Base.BookBlacksmith5",
				BookCarpentry1			= "Base.BookCarpentry1",
				BookCarpentry2			= "Base.BookCarpentry2",
				BookCarpentry3			= "Base.BookCarpentry3",
				BookCarpentry4			= "Base.BookCarpentry4",
				BookCarpentry5			= "Base.BookCarpentry5",
				BookCarving1			= "Base.BookCarving1",
				BookCarving2			= "Base.BookCarving2",
				BookCarving3			= "Base.BookCarving3",
				BookCarving4			= "Base.BookCarving4",
				BookCarving5			= "Base.BookCarving5",
				BookCooking1			= "Base.BookCooking1",
				BookCooking2			= "Base.BookCooking2",
				BookCooking3			= "Base.BookCooking3",
				BookCooking4			= "Base.BookCooking4",
				BookCooking5			= "Base.BookCooking5",
				BookCooking5			= "Base.BookCooking5",
				BookElectrician1		= "Base.BookElectrician1",
				BookElectrician2		= "Base.BookElectrician2",
				BookElectrician3		= "Base.BookElectrician3",
				BookElectrician4		= "Base.BookElectrician4",
				BookElectrician5		= "Base.BookElectrician5",
				BookFarming1			= "Base.BookFarming1",
				BookFarming2			= "Base.BookFarming2",
				BookFarming3			= "Base.BookFarming3",
				BookFarming4			= "Base.BookFarming4",
				BookFarming5			= "Base.BookFarming5",
				BookFirstAid1			= "Base.BookFirstAid1",
				BookFirstAid2			= "Base.BookFirstAid2",
				BookFirstAid3			= "Base.BookFirstAid3",
				BookFirstAid4			= "Base.BookFirstAid4",
				BookFirstAid5			= "Base.BookFirstAid5",
				BookFishing1			= "Base.BookFishing1",
				BookFishing2			= "Base.BookFishing2",
				BookFishing3			= "Base.BookFishing3",
				BookFishing4			= "Base.BookFishing4",
				BookFishing5			= "Base.BookFishing5",
				BookForaging1			= "Base.BookForaging1",
				BookForaging2			= "Base.BookForaging2",
				BookForaging3			= "Base.BookForaging3",
				BookForaging4			= "Base.BookForaging4",
				BookForaging5			= "Base.BookForaging5",
				BookMechanic1			= "Base.BookMechanic1",
				BookMechanic2			= "Base.BookMechanic2",
				BookMechanic3			= "Base.BookMechanic3",
				BookMechanic4			= "Base.BookMechanic4",
				BookMechanic5			= "Base.BookMechanic5",
				BookMetalWelding1		= "Base.BookMetalWelding1",
				BookMetalWelding2		= "Base.BookMetalWelding2",
				BookMetalWelding3		= "Base.BookMetalWelding3",
				BookMetalWelding4		= "Base.BookMetalWelding4",
				BookMetalWelding5		= "Base.BookMetalWelding5",
				BookTailoring1			= "Base.BookTailoring1",
				BookTailoring2			= "Base.BookTailoring2",
				BookTailoring3			= "Base.BookTailoring3",
				BookTailoring4			= "Base.BookTailoring4",
				BookTailoring5			= "Base.BookTailoring5",
				BookTrapping1			= "Base.BookTrapping1",
				BookTrapping2			= "Base.BookTrapping2",
				BookTrapping3			= "Base.BookTrapping3",
				BookTrapping4			= "Base.BookTrapping4",
				BookTrapping5			= "Base.BookTrapping5",
				CDplayer				= "Base.CDplayer",
				CarBatteryCharger		= "Base.CarBatteryCharger",
				CarvingFork2			= "Base.CarvingFork2",
				CompassGeometry			= "Base.CompassGeometry",
				CompostBag				= "Base.CompostBag",
				ConcretePowder			= "Base.ConcretePowder",
				ElectricWire			= "Base.ElectricWire",
				HamRadio1				= "Base.HamRadio1",
				HamRadio2				= "Base.HamRadio2",
				HamRadioMakeShift		= "Base.HamRadioMakeShift",
				MechanicMag1			= "Base.MechanicMag1",
				MechanicMag2			= "Base.MechanicMag2",
				MechanicMag3			= "Base.MechanicMag3",
				RadioBlack				= "Base.RadioBlack",
				RadioMag1				= "Base.RadioMag1",
				RadioMag2				= "Base.RadioMag2",
				RadioMag3				= "Base.RadioMag3",
				RadioMakeShift			= "Base.RadioMakeShift",
				RadioReceiver			= "Base.RadioReceiver",
				RadioRed				= "Base.RadioRed",
				RadioTransmitter		= "Base.RadioTransmitter",
				ScannerModule			= "Base.ScannerModule",
				StockCertificate		= "Base.StockCertificate",
				Timer					= "Base.Timer",
				TimerCrafted			= "Base.TimerCrafted",
				TinOpener				= "Base.TinOpener",
				TireIron				= "Base.TireIron",
				TirePump				= "Base.TirePump",
				TobaccoChewing			= "Base.TobaccoChewing",
				WalkieTalkie1			= "Base.WalkieTalkie1",
				WalkieTalkie2			= "Base.WalkieTalkie2",
				WalkieTalkie3			= "Base.WalkieTalkie3",
				WalkieTalkie4			= "Base.WalkieTalkie4",
				WalkieTalkie5			= "Base.WalkieTalkie5",
				WalkieTalkieMakeShift	= "Base.WalkieTalkieMakeShift",
				Yarn					= "Base.Yarn",
				Zipties					= "Base.Zipties",
			},
		},
		legendary = {
			chance = 1,
			xp = 50,
			categories = { "Junk" },
			items = {
				Aerosolbomb          	= "Base.Aerosolbomb",
				AerosolbombRemote     	= "Base.AerosolbombRemote",
				AerosolbombSensorV1    	= "Base.AerosolbombSensorV1",
				AerosolbombSensorV2   	= "Base.AerosolbombSensorV2",
				AerosolbombSensorV3    	= "Base.AerosolbombSensorV3",
				AerosolbombTriggered   	= "Base.AerosolbombTriggered",
				BoxOfJars            	= "Base.BoxOfJars",
				ChokeTubeFull           = "Base.ChokeTubeFull",
				ChokeTubeImproved       = "Base.ChokeTubeImproved",
				FlameTrap      			= "Base.FlameTrap",
				FlameTrapRemote      	= "Base.FlameTrapRemote",
				FlameTrapSensorV1      	= "Base.FlameTrapSensorV1",
				FlameTrapSensorV2      	= "Base.FlameTrapSensorV2",
				FlameTrapSensorV3      	= "Base.FlameTrapSensorV3",
				FlameTrapTriggered     	= "Base.FlameTrapTriggered",
				HerbalistMag            = "Base.HerbalistMag",
				LargeMeteorite          = "Base.LargeMeteorite",
				Molotov			        = "Base.Molotov",
				PipeBomb                = "Base.PipeBomb",
				PipeBombRemote          = "Base.PipeBombRemote",
				PipeBombSensorV1        = "Base.PipeBombSensorV1",
				PipeBombSensorV2        = "Base.PipeBombSensorV2",
				PipeBombSensorV3        = "Base.PipeBombSensorV3",
				PipeBombTriggered       = "Base.PipeBombTriggered",
				SmokeBomb               = "Base.SmokeBomb",
				SmokeBombRemote         = "Base.SmokeBombRemote",
				SmokeBombSensorV1       = "Base.SmokeBombSensorV1",
				SmokeBombSensorV2       = "Base.SmokeBombSensorV2",
				SmokeBombSensorV3       = "Base.SmokeBombSensorV3",
				SmokeBombTriggered      = "Base.SmokeBombTriggered",
				x2Scope                 = "Base.x2Scope",
				x4Scope                 = "Base.x4Scope",
				x8Scope                 = "Base.x8Scope",
			},
		},
	};
	for _, spawnTable in pairs(junkItems) do
		for itemName, itemFullName in pairs(spawnTable.items) do
			forageSystem.addForageDef(
				itemName,
				{
					type = itemFullName,
					skill = 0,
					xp = spawnTable.xp,
					categories = spawnTable.categories,
					zones = {
						Forest = spawnTable.chance,
						DeepForest = spawnTable.chance,
						PHForest = spawnTable.chance,
						PRForest = spawnTable.chance,
						BirchForest = spawnTable.chance,
						OrganicForest = spawnTable.chance,
						Vegitation = spawnTable.chance,
						FarmLand = spawnTable.chance,
						TrailerPark = spawnTable.chance,
						TownZone = spawnTable.chance,
						ForagingNav = spawnTable.chance,
					},
					spawnFuncs = { forageSystem.doGenericItemSpawn },
					forceOutside = false,
					canBeAboveFloor = true,
					itemSizeModifier = 0.5,
					isItemOverrideSize = true,
				}
			);
		end;
	end;
end

generateJunkDefs();