--[[---------------------------------------------
-------------------------------------------------
--
-- generateTrashDefs
--
-- eris
--
-------------------------------------------------
--]]---------------------------------------------

require "Foraging/forageDefinitions";
require "Foraging/forageSystem";

local function generateTrashDefs()
	--this category contains some of the very rare and/or interesting items other survivors have lost or thrown away
	--see also: Junk.lua
	local trashItems = {
		normal = {
			chance = 100,
			xp = 1,
			categories = { "Junk", "Trash" },
			items = {
				BeerCanEmpty        = "Base.BeerCanEmpty",
				BeerEmpty           = "Base.BeerEmpty",
				Garbagebag          = "Base.Garbagebag",
				Newspaper           = "Base.Newspaper",
				Plasticbag          = "Base.Plasticbag",
				Pop2Empty           = "Base.Pop2Empty",
				Pop3Empty           = "Base.Pop3Empty",
				PopEmpty            = "Base.PopEmpty",
				FountainCup         = "Base.FountainCup",
				SheetPaper2         = "Base.SheetPaper2",
				SmashedBottle       = "Base.SmashedBottle",
				TinCanEmpty         = "Base.TinCanEmpty",
				UnusableMetal       = "Base.UnusableMetal",
				UnusableWood        = "Base.UnusableWood",
				ScrapMetal          = "Base.ScrapMetal",
				Screws              = "Base.Screws",
				PaperBag            = "Base.PaperBag",
				PaperNapkins2       = "Base.PaperNapkins2",
				Paperbag_Jays       = "Base.Paperbag_Jays",
				Paperbag_Spiffos    = "Base.Paperbag_Spiffos",
			},
		},
		uncommon = {
			chance = 30,
			xp = 3,
			categories = { "Junk", "Trash" },
			items = {
				Aluminum           = "Base.Aluminum",
				BackgammonBoard    = "Base.BackgammonBoard",
				Baseball           = "Base.Baseball",
				Basketball         = "Base.Basketball",
				Bell               = "Base.Bell",
				Bricktoys          = "Base.Bricktoys",
				BrokenFishingNet   = "Base.BrokenFishingNet",
				CatFoodBag         = "Base.CatFoodBag",
				CatToy             = "Base.CatToy",
				Chopsticks         = "Base.Chopsticks",
				Coldpack           = "Base.Coldpack",
				Cologne            = "Base.Cologne",
				Comb               = "Base.Comb",
				Corkscrew          = "Base.Corkscrew",
				DenimStripsDirty   = "Base.DenimStripsDirty",
				Dirtbag            = "Base.Dirtbag",
				DishCloth          = "Base.DishCloth",
				DogFoodBag         = "Base.DogFoodBag",
				DogfoodOpen        = "Base.DogfoodOpen",
				DuctTape           = "Base.DuctTape",
				GlassTumbler       = "Base.GlassTumbler",
				GlassWine          = "Base.GlassWine",
				Glue               = "Base.Glue",
				GrillBrush         = "Base.GrillBrush",
				Hairgel            = "Base.Hairgel",
				KitchenTongs	   = "Base.KitchenTongs",
				LeatherStripsDirty = "Base.LeatherStripsDirty",
				Money              = "Base.Money",
				MuffinTray         = "Base.MuffinTray",
				OvenMitt           = "Base.OvenMitt",
				PaintbucketEmpty   = "Base.PaintbucketEmpty",
				Paperwork          = "Base.Paperwork",
				PlasticCup         = "Base.PlasticCup",
				PlasticTray        = "Base.PlasticTray",
				Plate              = "Base.Plate",
				Scotchtape         = "Base.Scotchtape",
				Spatula            = "Base.Spatula",
				Teacup             = "Base.Teacup",
				WeldingRods        = "Base.WeldingRods",
				WoodGlue           = "Base.Woodglue",
			},
		},
		rare = {
			chance = 10,
			xp = 5,
			categories = { "Junk", "Trash"},
			items = {
				Bobber			 = "Base.Bobber",
				Camera           = "Base.Camera",
				CameraDisposable = "Base.CameraDisposable",
				CameraExpensive  = "Base.CameraExpensive",
				CameraFilm       = "Base.CameraFilm",
				CandleBox		 = "Base.CandleBox",
				CardDeck         = "Base.CardDeck",
				Card_Birthday    = "Base.Card_Birthday",
				Card_Christmas   = "Base.Card_Christmas",
				Card_Easter      = "Base.Card_Easter",
				Card_Halloween   = "Base.Card_Halloween",
				Card_Hanukkah    = "Base.Card_Hanukkah",
				Card_LunarYear   = "Base.Card_LunarYear",
				Card_StPatrick   = "Base.Card_StPatrick",
				Card_Sympathy    = "Base.Card_Sympathy",
				Card_Valentine   = "Base.Card_Valentine",
				CreditCard       = "Base.CreditCard",
				Cube             = "Base.Cube",
				Dart             = "Base.Dart",
				DenimStrips      = "Base.DenimStrips",
				DenimStrips      = "Base.DenimStrips",
				Dice             = "Base.Dice",
				DogChew          = "Base.DogChew",
				Doll             = "Base.Doll",
				Drawer           = "Base.Drawer",
				DryerLint        = "Base.DryerLint",
				DumbBell         = "Base.DumbBell",
				Earbuds          = "Base.Earbuds",
				ElectronicsScrap = "Base.ElectronicsScrap",
				FireplacePoker   = "Base.FireplacePoker",
				Football         = "Base.Football",
				GolfBall         = "Base.GolfBall",
				GunPowder        = "Base.GunPowder",
				Hairspray        = "Base.Hairspray2",
				HandTorch        = "Base.HandTorch",
				Headphones       = "Base.Headphones",
				KatePic          = "Base.KatePic",
				KnittingNeedles  = "Base.KnittingNeedles",
				Leash            = "Base.Leash",
				LeatherStrips    = "Base.LeatherStrips",
				Lighter          = "Base.Lighter",
				LighterDisposable= "Base.LighterDisposable",
				Locket           = "Base.Locket",
				Matches          = "Base.Matches",
				Mirror           = "Base.Mirror",
				Padlock          = "Base.Padlock",
				PaintBlack       = "Base.PaintBlack",
				PaintBlue        = "Base.PaintBlue",
				PaintBrown       = "Base.PaintBrown",
				PaintCyan        = "Base.PaintCyan",
				PaintGreen       = "Base.PaintGreen",
				PaintGrey        = "Base.PaintGrey",
				PaintLightBlue   = "Base.PaintLightBlue",
				PaintLightBrown  = "Base.PaintLightBrown",
				PaintOrange      = "Base.PaintOrange",
				PaintPink        = "Base.PaintPink",
				PaintPurple      = "Base.PaintPurple",
				PaintRed         = "Base.PaintRed",
				PaintTurquoise   = "Base.PaintTurquoise",
				PaintWhite       = "Base.PaintWhite",
				Paintbrush       = "Base.Paintbrush",
				Paperback        = "Base.Paperback",
				Perfume          = "Base.Perfume",
				Pipe             = "Base.Pipe",
				RubberBand       = "Base.RubberBand",
				Rubberducky      = "Base.Rubberducky",
				SoccerBall       = "Base.SoccerBall",
				Sparklers        = "Base.Sparklers",
				TennisBall       = "Base.TennisBall",
				ToiletPaper      = "Base.ToiletPaper",
				Toothbrush       = "Base.Toothbrush",
				Torch            = "Base.Torch",
				ToyBear          = "Base.ToyBear",
				ToyCar           = "Base.ToyCar",
				Whistle          = "Base.Whistle",
				Yoyo             = "Base.Yoyo",
			},
		},
		epic = {
			chance = 3,
			xp = 10,
			categories = { "Junk", "Trash" },
			items = {
				BorisBadger		= "Base.BorisBadger",
				Bucket			= "Base.Bucket",
				Fertilizer		= "Base.Fertilizer",
				FluffyfootBunny	= "Base.FluffyfootBunny",
				FreddyFox		= "Base.FreddyFox",
				FurbertSquirrel	= "Base.FurbertSquirrel",
				GardenSaw		= "Base.GardenSaw",
				HairDryer       = "Base.HairDryer",
				Jack            = "Base.Jack",
				JacquesBeaver	= "Base.JacquesBeaver",
				Kettle			= "Base.Kettle",
				MoleyMole		= "Base.MoleyMole",
				MortarPestle	= "Base.MortarPestle",
				Mugl			= "Base.Mugl",
				NailsBox		= "Base.NailsBox",
				Needle			= "Base.Needle",
				PancakeHedgehog	= "Base.PancakeHedgehog",
				PanchoDog	    = "Base.PanchoDog",
				Plushabug   	= "Base.Plushabug",
				RoastingPan		= "Base.RoastingPan",
				Rope			= "Base.Rope",
				Spiffo			= "Base.Spiffo",
				TarotCardDeck	= "Base.TarotCardDeck",
				Wire			= "Base.Wire",
			},
		},
		legendary = {
			chance = 1,
			xp = 25,
			categories = { "Junk", "Trash" },
			items = {
				EmptyJar       		= "Base.EmptyJar",
				Key_Blank       	= "Base.Key_Blank",
				JarLid         		= "Base.JarLid",
				MugSpiffo      		= "Base.MugSpiffo",
				SpiffoBig      		= "Base.SpiffoBig",
				SpiffoSuit     		= "Base.SpiffoSuit",
				SpiffoTail     		= "Base.SpiffoTail",
			},
		},
	};
	for _, spawnTable in pairs(trashItems) do
		for itemName, itemFullName in pairs(spawnTable.items) do
			forageSystem.addForageDef(
				itemName,
				{
					type = itemFullName,
					xp = spawnTable.xp,
					categories = spawnTable.categories,
					zones = {
						Forest = spawnTable.chance,
						DeepForest = spawnTable.chance,
						PHForest = spawnTable.chance,
						PRForest = spawnTable.chance,
						BirchForest = spawnTable.chance,
						OrganicForest = spawnTable.chance,
						Vegitation = spawnTable.chance,
						FarmLand = spawnTable.chance,
						TrailerPark = spawnTable.chance,
						TownZone = spawnTable.chance,
						ForagingNav = spawnTable.chance,
					},
					spawnFuncs = { forageSystem.doGenericItemSpawn },
					forceOutside = false,
					canBeAboveFloor = true,
					itemSizeModifier = 0.5,
					isItemOverrideSize = true,
				}
			);
		end;
	end;
end

generateTrashDefs();