require "Foraging/forageDefinitions";
require "Foraging/forageSystem";

local function generateVegetablesDefs()
	local itemDefs = {
		Onion = {
			type = "Base.Onion",
			skill = 3,
			xp = 5,
			snowChance = -10,
			categories = { "Vegetables" },
			zones = {
				Forest      = 10,
				DeepForest  = 10,
				Vegitation  = 5,
				FarmLand    = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 9 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
		Lettuce = {
			type = "Base.Lettuce",
			skill = 7,
			xp = 5,
			snowChance = -30,
			categories = { "Vegetables" },
			zones = {
				Vegitation  = 1,
				FarmLand    = 4,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.vines,
		},
		Cucumber = {
			type = "Base.Cucumber",
			skill = 7,
			xp = 5,
			snowChance = -30,
			categories = { "Vegetables" },
			zones = {
				Vegitation  = 1,
				FarmLand    = 4,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.vines,
		},
		BellPepper = {
			type = "Base.BellPepper",
			skill = 7,
			xp = 5,
			snowChance = -20,
			categories = { "Vegetables" },
			zones = {
				FarmLand    = 5,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.smallTrees,
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		Avocado = {
			type = "Base.Avocado",
			skill = 8,
			xp = 15,
			snowChance = -50,
			categories = { "Vegetables" },
			zones = {
				FarmLand    = 5,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			altWorldTexture = forageSystem.worldSprites.smallTrees,
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		Zucchini = {
			type = "Base.Zucchini",
			skill = 8,
			xp = 15,
			snowChance = -30,
			categories = { "Vegetables" },
			zones = {
				FarmLand    = 5,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.shrubs,
		},
		Corn = {
			type = "Base.Corn",
			skill = 8,
			xp = 15,
			snowChance = -30,
			categories = { "Vegetables" },
			zones = {
				Vegitation  = 1,
				FarmLand    = 5,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = getTexture("media/textures/Foraging/worldSprites/corn_worldSprite.png"),
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		Eggplant = {
			type = "Base.Eggplant",
			skill = 8,
			xp = 15,
			snowChance = -50,
			categories = { "Vegetables" },
			zones = {
				FarmLand    = 3,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			altWorldTexture = forageSystem.worldSprites.shrubs,
		},
		Leek = {
			type = "Base.Leek",
			skill = 2,
			xp = 15,
			snowChance = -30,
			categories = { "Vegetables" },
			zones = {
				Forest      = 10,
				DeepForest  = 10,
				Vegitation  = 10,
				FarmLand    = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 9 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
		--======== CROPS  ========--
		Carrots = {
			type = "Base.Carrots",
			skill = 2,
			xp = 5,
			snowChance = -30,
			categories = { "Crops" },
			zones = {
				Forest      = 7,
				Vegitation  = 7,
				FarmLand    = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = { getTexture("media/textures/Foraging/worldSprites/wildcarrot_worldSprite.png") },
		},
		Broccoli = {
			type = "Base.Broccoli",
			skill = 2,
			xp = 5,
			snowChance = -30,
			categories = { "Crops" },
			zones = {
				Forest      = 7,
				Vegitation  = 7,
				FarmLand    = 10,
			},
			months = { 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 6, 7, 8 },
			malusMonths = { 5, 11 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.shrubs,
		},
		Potato = {
			type = "Base.Potato",
			skill = 2,
			xp = 5,
			snowChance = -30,
			categories = { "Crops" },
			zones = {
				Forest      = 7,
				Vegitation  = 7,
				FarmLand    = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = getTexture("media/textures/Foraging/worldSprites/wildpotato_worldSprite.png"),
		},
		Cabbage = {
			type = "Base.Cabbage",
			skill = 2,
			xp = 5,
			snowChance = -10,
			categories = { "Crops" },
			zones = {
				Forest      = 3,
				Vegitation  = 3,
				FarmLand    = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = getTexture("media/textures/Foraging/worldSprites/wildcabbage_worldSprite.png"),
		},
		Tomato = {
			type = "Base.Tomato",
			skill = 2,
			xp = 5,
			snowChance = -10,
			categories = { "Crops" },
			zones = {
				Forest      = 3,
				Vegitation  = 3,
				FarmLand    = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = getTexture("media/textures/Foraging/worldSprites/wildtomato_worldSprite.png"),
		},
		RedRadish = {
			type = "Base.RedRadish",
			skill = 2,
			xp = 5,
			snowChance = -10,
			categories = { "Crops" },
			zones = {
				Forest      = 3,
				Vegitation  = 3,
				FarmLand    = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
		Daikon = {
			type = "Base.Daikon",
			skill = 5,
			xp = 10,
			snowChance = -10,
			categories = { "Vegetables" },
			zones = {
				Vegitation  = 1,
				FarmLand    = 5,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
		Peanuts = {
			type = "Base.Peanuts",
			skill = 7,
			xp = 15,
			snowChance = -30,
			categories = { "Vegetables" },
			zones = {
				Forest      = 3,
				DeepForest  = 3,
				Vegitation  = 3,
				FarmLand    = 3,
			},
			months = { 9, 10, 11 },
			bonusMonths = { 10 },
			malusMonths = { 11 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
		Pumpkin = {
			type = "Base.Pumpkin",
			skill = 7,
			xp = 15,
			snowChance = -30,
			categories = { "Vegetables" },
			zones = {
				Forest      = 1,
				DeepForest  = 1,
				Vegitation  = 1,
				FarmLand    = 1,
			},
			months = { 9, 10, 11 },
			bonusMonths = { 10 },
			malusMonths = { 11 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
		Cauliflower = {
			type = "Base.Cauliflower",
			skill = 7,
			xp = 15,
			snowChance = -30,
			categories = { "Vegetables" },
			zones = {
				Forest      = 3,
				Vegitation  = 3,
				FarmLand    = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 10 },
			malusMonths = { 11 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
		SugarBeet = {
			type = "Base.SugarBeet",
			skill = 7,
			xp = 15,
			snowChance = -30,
			categories = { "Vegetables" },
			zones = {
				Forest      = 3,
				Vegitation  = 3,
				FarmLand    = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 10 },
			malusMonths = { 11 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
		SweetPotato = {
			type = "Base.SweetPotato",
			skill = 7,
			xp = 15,
			snowChance = -30,
			categories = { "Vegetables" },
			zones = {
				Forest      = 3,
				DeepForest  = 3,
				Vegitation  = 3,
				FarmLand    = 5,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 10 },
			malusMonths = { 11 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
		Turnip = {
			type = "Base.Turnip",
			skill = 7,
			xp = 15,
			snowChance = -30,
			categories = { "Vegetables" },
			zones = {
				Forest      = 3,
				DeepForest  = 3,
				Vegitation  = 3,
				FarmLand    = 5,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 10 },
			malusMonths = { 11 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
		Soybeans = {
			type = "Base.Soybeans",
			skill = 7,
			xp = 15,
			snowChance = -30,
			categories = { "Vegetables" },
			zones = {
				Forest      = 3,
				DeepForest  = 3,
				Vegitation  = 3,
				FarmLand    = 5,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 10 },
			malusMonths = { 11 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
		Spinach = {
			type = "Base.Spinach",
			skill = 7,
			xp = 15,
			snowChance = -30,
			categories = { "Vegetables" },
			zones = {
				Forest      = 3,
				DeepForest  = 3,
				Vegitation  = 3,
				FarmLand    = 5,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 10 },
			malusMonths = { 11 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
		Kale = {
			type = "Base.Kale",
			skill = 7,
			xp = 15,
			snowChance = -30,
			categories = { "Vegetables" },
			zones = {
				Forest      = 3,
				DeepForest  = 3,
				Vegitation  = 3,
				FarmLand    = 5,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 10 },
			malusMonths = { 11 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
		Garlic = {
			type = "Base.Garlic",
			skill = 7,
			xp = 15,
			snowChance = -30,
			categories = { "Vegetables" },
			zones = {
				Forest      = 1,
				DeepForest  = 1,
				Vegitation  = 1,
				FarmLand    = 1,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 10 },
			malusMonths = { 11 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
		Greenpeas = {
			type = "Base.Greenpeas",
			skill = 7,
			xp = 15,
			snowChance = -30,
			categories = { "Vegetables" },
			zones = {
				Forest      = 1,
				DeepForest  = 1,
				Vegitation  = 1,
				FarmLand    = 1,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 10 },
			malusMonths = { 11 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn, forageSystem.doWildCropSpawn },
			altWorldTexture = forageSystem.worldSprites.wildPlants,
		},
	};
	for itemName, itemDef in pairs(itemDefs) do
		forageSystem.addForageDef(itemName, itemDef);
	end;
end

generateVegetablesDefs();
