--[[---------------------------------------------
-------------------------------------------------
--
-- generateWildPlantsDefs
--
-- eris
--
-------------------------------------------------
--]]---------------------------------------------

require "Foraging/forageDefinitions";

local function generateWildPlantsDefs()
	local itemDefs = {
		Violets = {
			type = "Base.Violets",
			minCount = 3,
			maxCount = 6,
			xp = 5,
			categories = { "WildPlants" },
			zones = {
				Forest      = 10,
				DeepForest  = 10,
				Vegitation  = 10,
				FarmLand    = 10,
				Farm        = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			altWorldTexture = { {"d_plants_1_40"}, {"d_plants_1_41"}, {"d_plants_1_44"} },
			doIsoMarkerObject = true,
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		SunflowerSeeds = {
			type = "Base.SunflowerSeeds",
			minCount = 3,
			maxCount = 6,
			xp = 5,
			rainChance = -50,
			snowChance = -100,
			nightChance = -100,
			categories = { "WildPlants" },
			zones = {
				Forest      = 10,
				DeepForest  = 10,
				Vegitation  = 10,
				FarmLand    = 10,
				Farm        = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			altWorldTexture = { {"d_plants_1_18", "d_plants_1_26"} },
			doIsoMarkerObject = true,
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		GrapeLeaves = {
			type = "Base.GrapeLeaves",
			minCount = 3,
			maxCount = 6,
			skill = 2,
			xp = 5,
			categories = { "WildPlants" },
			zones = {
				Forest      = 10,
				DeepForest  = 10,
				Vegitation  = 10,
				FarmLand    = 10,
				Farm        = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			altWorldTexture = forageSystem.worldSprites.vines,
		},
		Rosehips = {
			type = "Base.Rosehips",
			minCount = 3,
			maxCount = 6,
			skill = 4,
			xp = 5,
			rainChance = 20,
			snowChance = -100,
			categories = { "WildPlants" },
			zones = {
				Forest      = 10,
				DeepForest  = 10,
				Vegitation  = 10,
				FarmLand    = 10,
				Farm        = 10,
			},
			months = { 1, 2, 5, 6, 7, 8, 9, 10, 11, 12, },
			bonusMonths = { 9, 10, 11 },
			malusMonths = { 5, 6 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			altWorldTexture = forageSystem.worldSprites.shrubs,
		},
		Acorn = {
			type = "Base.Acorn",
			minCount = 3,
			maxCount = 6,
			xp = 5,
			categories = { "WildPlants" },
			zones = {
				Forest      = 10,
				DeepForest  = 10,
				Vegitation  = 10,
				FarmLand    = 10,
				Farm        = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		Dandelions = {
			type = "Base.Dandelions",
			minCount = 3,
			maxCount = 6,
			xp = 5,
			categories = { "WildPlants" },
			zones = {
				Forest      = 10,
				DeepForest  = 10,
				Vegitation  = 10,
				FarmLand    = 10,
				Farm        = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		Nettles = {
			type = "Base.Nettles",
			minCount = 3,
			maxCount = 6,
			xp = 5,
			categories = { "WildPlants" },
			zones = {
				Forest      = 10,
				DeepForest  = 10,
				Vegitation  = 10,
				FarmLand    = 10,
				Farm        = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		GingerRoot = {
			type = "Base.GingerRoot",
			minCount = 1,
			maxCount = 3,
			xp = 15,
			categories = { "WildPlants" },
			zones = {
				Forest      = 1,
				DeepForest  = 1,
				Vegitation  = 1,
				FarmLand    = 1,
				Farm        = 1,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
		Thistle = {
			type = "Base.Thistle",
			minCount = 3,
			maxCount = 6,
			xp = 5,
			categories = { "WildPlants" },
			zones = {
				Forest      = 10,
				DeepForest  = 10,
				Vegitation  = 10,
				FarmLand    = 10,
				Farm        = 10,
			},
			months = { 3, 4, 5, 6, 7, 8, 9, 10, 11 },
			bonusMonths = { 5, 6, 7 },
			malusMonths = { 3, 4 },
			spawnFuncs = { forageSystem.doWildFoodSpawn, forageSystem.doRandomAgeSpawn },
			itemSizeModifier = 1.0,
			isItemOverrideSize = true,
		},
	};
	for itemName, itemDef in pairs(itemDefs) do
		forageDefs[itemName] = itemDef;
	end;
end

generateWildPlantsDefs();