---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by RJ.
--- DateTime: 11/19/2024 8:54 AM
---

ISVersionWaterMark = {};

WaterMarkUI = ISPanel:derive("WaterMarkUI");
local FONT_HGT_MEDIUM = getTextManager():getFontHeight(UIFont.Medium)

ISVersionWaterMark.doMsg = function()
    local width = getTextManager():MeasureStringX(UIFont.Medium, getCore():getVersion())

    local panel = WaterMarkUI:new(getCore():getScreenWidth() - width - 20, getCore():getScreenHeight() - 40, width + 10, FONT_HGT_MEDIUM + 5);
    --local panel = WaterMarkUI:new(300, 300, width + 10, 300 + 5);
    panel:initialise();
    panel:addToUIManager();
    panel:setVisible(true);
end

function WaterMarkUI:render()
    ISPanel.render(self);

    local width = getTextManager():MeasureStringX(UIFont.Medium, getCore():getVersion());
    self:setX(getCore():getScreenWidth() - width - 20);
    self:setY(getCore():getScreenHeight() - 40);
    self:drawText(getCore():getVersion(), 0, 0, 1,1,1,0.5,UIFont.Medium);
end

function WaterMarkUI:initialise()
    ISPanel.initialise(self);
end

function WaterMarkUI:new(x, y, width, height)
    local o = {};
    o = ISPanel:new(x, y, width, height);
    setmetatable(o, self);
    self.__index = self;
    o.refreshNeeded = true
    o.borderColor = {r=0, g=0, b=0, a=0};
    o.backgroundColor = {r=0, g=0, b=0, a=0};
    return o;
end


Events.OnGameStart.Add(ISVersionWaterMark.doMsg);