--***********************************************************
--**                    ROBERT JOHNSON                     **
--***********************************************************

-- key bindings always:
    -- start with bind = {}
    -- end with table.insert(keyBinding, bind)
--this way, it should be easy to tell where one keybind ends and the next begins.

keyBinding = {};

local bind = {};
bind.value = "[Player Control]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "Forward";
bind.key = Keyboard.KEY_W --17;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Backward";
bind.key = Keyboard.KEY_S --31;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Left";
bind.key = Keyboard.KEY_A --30;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Right";
bind.key = Keyboard.KEY_D --32;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Run";
bind.key = Keyboard.KEY_LSHIFT --42;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Interact";
bind.key = Keyboard.KEY_E -- 18;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Sprint";
bind.key = isSystemMacOS() and Keyboard.KEY_LMETA or Keyboard.KEY_LMENU;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Rotate building";
bind.key = Keyboard.KEY_R;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle mode";
bind.key = Keyboard.KEY_TAB;
table.insert(keyBinding, bind);
bind = {};
bind.value = "CancelAction";
bind.key = Keyboard.KEY_ESCAPE;
table.insert(keyBinding, bind);
bind = {};
bind.value = "WalkTo";
bind.key = Keyboard.KEY_Y;
table.insert(keyBinding, bind);
bind = {};
bind.value = "ReleaseRope";
bind.key = Keyboard.KEY_NONE;
table.insert(keyBinding, bind);
bind = {};
bind.value = "[Combat]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "Attack/Click";
bind.key = Mouse.LMB; -- or Mouse.BTN_0
table.insert(keyBinding, bind);
bind = {};
bind.value = "Crouch";
bind.key = Keyboard.KEY_C;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Aim";
bind.key = Keyboard.KEY_LCONTROL;
bind.alt = Mouse.RMB; -- or Mouse.BTN_1
table.insert(keyBinding, bind);
bind = {};
bind.value = "Melee";
bind.key = Keyboard.KEY_SPACE;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Rack Firearm";
bind.key = Keyboard.KEY_X;
table.insert(keyBinding, bind);
bind = {};
bind.value = "ReloadWeapon";
bind.key = Keyboard.KEY_R;
table.insert(keyBinding, bind);
bind = {};
bind.value = "ManualFloorAtk";
bind.key = Keyboard.KEY_LMENU;
table.insert(keyBinding, bind);
bind = {};
bind.value = "[Vehicle]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "StartVehicleEngine";
bind.key = Keyboard.KEY_N;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Brake";
bind.key = Keyboard.KEY_SPACE;
table.insert(keyBinding, bind);
bind = {};
bind.value = "CruiseControl";
bind.key = Keyboard.KEY_LSHIFT;
table.insert(keyBinding, bind);
bind = {};
bind.value = "ToggleVehicleHeadlights";
bind.key = Keyboard.KEY_F;
table.insert(keyBinding, bind);
bind = {};
bind.value = "VehicleHeater";
bind.key = Keyboard.KEY_O;
table.insert(keyBinding, bind);
bind = {};
bind.value = "VehicleMechanics";
bind.key = Keyboard.KEY_U;
table.insert(keyBinding, bind);
bind = {};
bind.value = "VehicleHorn";
bind.key = Keyboard.KEY_Q;
table.insert(keyBinding, bind);
bind = {};
bind.value = "VehicleRadialMenu";
bind.key = Keyboard.KEY_V;
table.insert(keyBinding, bind);
bind = {};
bind.value = "VehicleSwitchSeat";
bind.key = Keyboard.KEY_Z;
table.insert(keyBinding, bind);
bind = {};
bind.value = "[UI]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle UI";
bind.key = Keyboard.KEY_NONE -- 0;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Crafting UI";
bind.key = Keyboard.KEY_B -- 48;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Building UI";
bind.key = Keyboard.KEY_NONE; -- not bound
table.insert(keyBinding, bind);
bind = {};
bind.value = "Main Menu";
bind.key = Keyboard.KEY_ESCAPE;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Inventory";
bind.key = Keyboard.KEY_I -- 23;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Skill Panel";
bind.key = Keyboard.KEY_L;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Health Panel";
bind.key = Keyboard.KEY_H;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Info Panel";
bind.key = Keyboard.KEY_J;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Clothing Protection Panel";
bind.key = Keyboard.KEY_P;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Moveable Panel Mode";
bind.key = Keyboard.KEY_RBRACKET --27;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Map";
bind.key = Keyboard.KEY_M;
table.insert(keyBinding, bind);
bind = {};
bind.value = "AnimalRadialMenu";
bind.key = Keyboard.KEY_V;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Take screenshot";
bind.key = Keyboard.KEY_F10 -- 68;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Survival Guide";
bind.key = Keyboard.KEY_F1 -- 59;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Display FPS";
bind.key = 37;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Pause";
bind.key = Keyboard.KEY_F2 -- 60;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Normal Speed";
bind.key = Keyboard.KEY_F3 -- 61;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Fast Forward x1";
bind.key = Keyboard.KEY_F4 -- 62;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Fast Forward x2";
bind.key = Keyboard.KEY_F5 -- 63;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Fast Forward x3";
bind.key = Keyboard.KEY_F6 -- 64;
table.insert(keyBinding, bind);
bind = {};
bind.value = "PanCamera";
bind.key = Keyboard.KEY_NONE; -- not bound
table.insert(keyBinding, bind);
bind = {};
bind.value = "Zoom in";
bind.key = Keyboard.KEY_EQUALS -- 13;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Zoom out";
bind.key = Keyboard.KEY_MINUS -- 12;
table.insert(keyBinding, bind);
bind = {};
bind.value = "[Hotkeys]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "Hotbar 1";
bind.key = Keyboard.KEY_1;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Hotbar 2";
bind.key = Keyboard.KEY_2;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Hotbar 3";
bind.key = Keyboard.KEY_3;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Hotbar 4";
bind.key = Keyboard.KEY_4;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Hotbar 5";
bind.key = Keyboard.KEY_5;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Hotbar 6";
bind.key = Keyboard.KEY_6;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Hotbar 7";
bind.key = Keyboard.KEY_7;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Hotbar 8";
bind.key = Keyboard.KEY_8;
table.insert(keyBinding, bind);
--bind = {};
--bind.value = "Equip/Unequip Handweapon";
--bind.key = 2;
--table.insert(keyBinding, bind);
--bind = {};
--bind.value = "Equip/Unequip Firearm";
--bind.key = 3;
--table.insert(keyBinding, bind);
--bind = {};
--bind.value = "Equip/Unequip Stab weapon";
--bind.key = 4;
--table.insert(keyBinding, bind);
bind = {};
bind.value = "Equip/Turn On/Off Light Source";
bind.key = Keyboard.KEY_F --33;
table.insert(keyBinding, bind);
bind = {};
bind.value = "DropBothHeldItems";
bind.key = Keyboard.KEY_NONE; -- not bound
table.insert(keyBinding, bind);
bind = {};
bind.value = "DropPrimaryHeldItem";
bind.key = Keyboard.KEY_NONE; -- not bound
table.insert(keyBinding, bind);
bind = {};
bind.value = "DropSecondaryHeldItem";
bind.key = Keyboard.KEY_NONE; -- not bound
table.insert(keyBinding, bind);
bind = {};
bind.value = "DropWornBag";
bind.key = Keyboard.KEY_NONE; -- not bound
table.insert(keyBinding, bind);
bind = {};
bind.value = "DropBothHeldItemsAndWornBag";
bind.key = Keyboard.KEY_NONE; -- not bound
table.insert(keyBinding, bind);
bind = {};
bind.value = "GrabCorpse";
bind.key = Keyboard.KEY_NONE; -- not bound
table.insert(keyBinding, bind);
bind = {};
bind.value = "[Multiplayer]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Safety";
bind.key = Keyboard.KEY_G;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle chat";
bind.key = Keyboard.KEY_T -- 20;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Alt toggle chat"; -- TODO: remove? (redundant)
bind.key = Keyboard.KEY_RETURN -- 28;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Switch chat stream";
bind.key = Keyboard.KEY_TAB -- 15;
table.insert(keyBinding, bind);
bind = {};
bind.value = "[Voice]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "Enable voice transmit";
bind.key = Keyboard.KEY_LMENU -- 56;
table.insert(keyBinding, bind);
bind = {};
bind.value = "[NPC Interaction]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "Shout";
bind.key = Keyboard.KEY_Q;
table.insert(keyBinding, bind);
bind = {};
bind.value = "Emote";
bind.key = Keyboard.KEY_Q;
table.insert(keyBinding, bind);
bind = {};
bind.value = "[Audio]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Music";
bind.key = Keyboard.KEY_NONE;
table.insert(keyBinding, bind);
bind = {};
bind.value = "[Debug]";
table.insert(keyBinding, bind);
bind = {};
bind.value = "Toggle Lua Debugger";
bind.key = Keyboard.KEY_F11;
table.insert(keyBinding, bind);
bind = {};
bind.value = "ToggleLuaConsole";
bind.key = Keyboard.KEY_GRAVE;
table.insert(keyBinding, bind);
bind = {};
bind.value = "ToggleGodModeInvisible";
bind.key = Keyboard.KEY_N;
table.insert(keyBinding, bind);
bind = {};
bind.value = "ToggleModelsEnabled";
bind.key = Keyboard.KEY_F3;
table.insert(keyBinding, bind);
bind = {};
bind.value = "ToggleAnimationText";
bind.key = Keyboard.KEY_F6;
table.insert(keyBinding, bind);

