---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by zacco.
--- DateTime: 29/08/2025 10:51 am
---

require "TimedActions/ISBaseTimedAction"
require "TimedActions/ISInventoryTransferAction"
require "TimedActions/ISGrabCorpseAction"
require "ISUI/PlayerData/ISPlayerData"

ISInventoryTransferUtil = {}

function ISInventoryTransferUtil.newInventoryTransferAction(character, item, srcContainer, destContainer, time)
    local isGrabbingCorpseItem = ISInventoryTransferUtil.isCharacterGrabbingCorpseItem(character, item, srcContainer, destContainer)
    if isGrabbingCorpseItem then
        return ISGrabCorpseItem:new(character, item)
    end

    return ISInventoryTransferAction:new(character, item, srcContainer, destContainer, time)
end

function ISInventoryTransferUtil.isPlayerCharacter(character)
    local isPlayer = instanceof(character, "IsoPlayer")
    return isPlayer
end

function ISInventoryTransferUtil.isCharacterGrabbingCorpseItem(character, item, srcContainer, destContainer)
    local isPlayer = ISInventoryTransferUtil.isPlayerCharacter(character)
    if not isPlayer then
        return false
    end

    local playerNum = character:getPlayerNum()
    local isGrabbingCorpseItem =  ISInventoryTransferUtil.isPlayerGrabbingCorpseItem(playerNum, item, destContainer)
    return isGrabbingCorpseItem
end

function ISInventoryTransferUtil.isPlayerGrabbingCorpseItem(playerNum, item, targetContainer)
    local playerObj = getSpecificPlayer(playerNum)
    if not playerObj then
        return false
    end

    if not item then
        return false
    end

    if not targetContainer then
        return false
    end

    if not item:isHumanCorpse() then
        return false;
    end

    local playerInv = getPlayerInventory(playerNum).inventory;
    if not playerInv then
        return false
    end

    if playerInv == targetContainer then
        return true
    end

    return false
end