-- Flax
-- Hemp
-- Hops

farming_vegetableconf.props.Barley = {
    icon = "Item_Barley",
    texture = "vegetation_farming_01b_6",
--     waterLvl = 35,
    waterLvl = 30,
    waterNeeded = 70,
    timeToGrow = 432,
--    timeToGrow = 960,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName =  "Base.BarleySheaf",
--     produceExtra =  "Base.HayTuft",
    seedName = "Base.BarleySheaf",
    seedTypes = { "Base.BarleySeed",},
    badMonth = { 6, 7 },
    sowMonth = { 8, 9, 10 },
    bestMonth = { 9 },
    riskMonth = { 10 },
    seasonRecipe = "Barley Growing Season",
    harvestLevel = 6,
    mature = 5,
    fullGrown = 6,
    scytheHarvest = true,
    harvestPosition = "High",
    coldHardy = true,
}

farming_vegetableconf.props.BellPepper = {
    icon = "Item_BellPepper",
    texture = "vegetation_farming_01b_70",
--     waterLvl = 75,
    waterLvl = 70,
    timeToGrow = 292,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName =  "Base.BellPepper",
    seedName = "Base.BellPepper",
    seedTypes = { "Base.BellPepperSeed", },

    harvestLevel = 5,
--     waterNeeded = 85,
    waterNeeded = 70,
    mature = 5,
    fullGrown = 6,
    badMonth = { 10, 11, 12, 1, 2, 3 },
    sowMonth = { 4, 5, 6 },
    bestMonth = { 5 },
    riskMonth = { 6 },
    seasonRecipe = "Bell Pepper Growing Season",
}

farming_vegetableconf.props["Broccoli"] = {
    icon = "Item_Broccoli",
    waterLvl = 70,
    texture = "vegetation_farming_01_30",
    timeToGrow = 292,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName = "Base.Broccoli",
    seedName = "Base.BroccoliSeed",

    harvestLevel = 5,
    waterNeeded = 70,
    rotTime = 248,
    mature = 5,
    fullGrown = 6,
    badMonth = { 9, 10, 11, 12, 1 },
    sowMonth = { 2, 3, 4, 5, 6, 7 },
    bestMonth = { 3, 6 },
    riskMonth = { 7 },
    seasonRecipe = "Broccoli Growing Season",
    mothFood = true,
--     seedTypes = {"Base.BroccoliSeed",},
}

farming_vegetableconf.props["Cabbages"] = {
    icon = "Item_Cabbage",
    texture = "vegetation_farming_01_21",
--     waterLvl = 85,
    waterLvl = 80,
    timeToGrow = 292,
    vegetableName = "Base.Cabbage",
    seedName = "Base.CabbageSeed",
--     minVeg = 4,
--     maxVeg = 6,
--     minVegAutorized = 9,
--     maxVegAutorized = 11,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,

    harvestLevel = 5,
    waterNeeded = 80,
    mature = 5,
    fullGrown = 6,
    badMonth = { 10, 11, 12, 1 },
    sowMonth = { 2, 3, 4, 5, 6, 7 },
    bestMonth =  { 3, 5 },
    riskMonth = { 7 },
    seasonRecipe = "Cabbage Growing Season",
    coldHardy = true,
    mothFood = true,
--     seedTypes = {"Base.CabbageSeed",},
}

farming_vegetableconf.props["Carrots"] = {
    icon = "Item_Carrots",
    texture = "vegetation_farming_01_38",
--     waterLvl = 35,
    waterLvl = 30,
--     waterLvlMax = 85,
    timeToGrow = 432,
    minVeg = 3,
    maxVeg = 6,
    minVegAutorized = 10,
    maxVegAutorized = 15,
    vegetableName = "Base.Carrots",
    seedName = "Base.CarrotSeed",

    harvestLevel = 5,
    waterNeeded = 70,
    mature = 5,
    fullGrown = 6,
    badMonth = { 1, 10, 11, 12, },
    badMonthHardyLevel = 4,
    sowMonth = {  2, 3, 4, 5, 6, 7 },
    bestMonth = { 2, 6 },
    riskMonth = { 7 },
    seasonRecipe = "Carrot Growing Season",
--     seedTypes = {"Base.CarrotSeed",},
}

farming_vegetableconf.props["Cauliflower"] = {
    icon = "Item_Cauliflower",
    waterLvl = 70,
    texture = "vegetation_farming_01b_78",
    timeToGrow = 292,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName = "Base.Cauliflower",
    seedName = "Base.CauliflowerSeed",

    harvestLevel = 5,
    waterNeeded = 70,
    rotTime = 248,
    mature = 5,
    fullGrown = 6,
    badMonth = { 9, 10, 11, 12, 1 },
    sowMonth = { 2, 3, 4 },
	riskMonth = { 4 },
    bestMonth = { 3 },
    seasonRecipe = "Cauliflower Growing Season",
    mothFood = true,
--     seedTypes = {"Base.BroccoliSeed",},
}


farming_vegetableconf.props.Corn = {
    texture = "vegetation_farming_01_78",
    icon = "Item_Corn",
--     waterLvl = 35,
    waterLvl = 30,
    timeToGrow = 432,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName =  "Base.Corn",
    seedName = "Base.Corn",
    seedTypes = { "Base.CornSeed", "Base.Corn",},

    harvestLevel = 5,
    waterNeeded = 70,
    mature = 5,
    fullGrown = 6,
    badMonth = { 8, 9, 10, 11, 12, 1, 2 },
    sowMonth = { 3, 4, 5 },
    bestMonth = { 4 },
	riskMonth = { 5 },
    seasonRecipe = "Corn Growing Season",
    harvestPosition = "High",
}

farming_vegetableconf.props.Cucumber = {
    icon = "Item_Cucumber",
    texture = "vegetation_farming_01b_86",
--     waterLvl = 75,
    waterLvl = 70,
    timeToGrow = 432,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName =  "Base.Cucumber",
    seedName = "Base.Cucumber",
    seedTypes = { "Base.CucumberSeed", },

    harvestLevel = 5,
--     waterNeeded = 85,
    waterNeeded = 70,
    mature = 5,
    fullGrown = 6,
    badMonth = { 8, 9, 10, 11, 12, 1, 2 },
    sowMonth = { 3, 4, 5 },
    bestMonth = { 4 },
	riskMonth = { 5 },
    seasonRecipe = "Cucumber Growing Season",
}

farming_vegetableconf.props.Flax = {
    icon = "Item_Flax_Harvested",
    texture = "vegetation_farming_01b_14",
--    waterLvl = 35,
    waterLvl = 30,
    waterNeeded = 70,
    timeToGrow = 432,
--    timeToGrow = 960,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName =  "Base.Flax",
--    produceExtra =  "Base.HayTuft",
    seedName = "Base.Flax",
    seedTypes = { "Base.FlaxSeed",},
    badMonth = { 6, 7 },
    sowMonth = { 8, 9, 10 },
    bestMonth = { 9 },
    riskMonth = { 10 },
    seasonRecipe = "Flax Growing Season",
    harvestLevel = 6,
    mature = 5,
    fullGrown = 6,
    scytheHarvest = true,
    harvestPosition = "High",
	coldHardy = true,
}

farming_vegetableconf.props.Garlic = {
    texture = "vegetation_farming_01_134",
    icon = "Item_Garlic",
--     waterLvl = 35,
    waterLvl = 30,
--     timeToGrow = 432,
    timeToGrow = 1152,
    -- waterLvlMax = 85,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 5,
    maxVegAutorized = 8,
    vegetableName =  "Base.Garlic",
    seedName = "Base.GarlicSeed",

    harvestLevel = 5,
    mature = 5,
    fullGrown = 6,
    waterNeeded = 70,
    badMonth = { 6 },
    sowMonth = { 7, 8, 9 },
    bestMonth = { 8 },
    riskMonth = { 9 },
    seasonRecipe = "Garlic Growing Season",
    seedTypes = { "Base.GarlicSeed", "Base.Garlic",},
    aphidsBane = true,
    slugsProof = true,
    coldHardy = true,
    mothBane = true,
    rabbitBane = true,
}

farming_vegetableconf.props.Greenpeas = {
    icon = "Item_Greenpeas",
    texture = "vegetation_farming_01_110",
--     waterLvl = 75,
    waterLvl = 70,
    timeToGrow = 292,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName =  "Base.Greenpeas",
    seedName = "Base.Greenpeas",
    seedTypes = { "Base.GreenpeasSeed", "Base.Greenpeas",},

    harvestLevel = 5,
--     waterNeeded = 85,
    waterNeeded = 80,
    mature = 5,
    fullGrown = 6,
    badMonth = { 10, 11, 12, 1 },
    sowMonth = { 2, 3, 4 },
    bestMonth = { 3 },
	riskMonth = { 4 },
    -- riskMonth = { 7 },
    seasonRecipe = "Green Pea Growing Season",
    harvestPosition = "Mid",
    slugsProof = true,
    mothFood = true,
}

farming_vegetableconf.props.Hemp = {
    icon = "Item_IndustrialHemp",
    texture = "vegetation_farming_01b_22",
--     waterLvl = 35,
    waterLvl = 30,
    waterNeeded = 70,
--     timeToGrow = 432,
    timeToGrow = 960,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName =  "Base.HempBundle",
--     produceExtra =  "Base.HayTuft",
    seedName = "Base.HempSeed",
    seedTypes = { "Base.HempSeed",},
    badMonth = { 6, 7 },
    sowMonth = { 8, 9, 10 },
    bestMonth = { 9 },
    riskMonth = { 10 },
    seasonRecipe = "Hemp Growing Season",
    harvestLevel = 6,
    mature = 5,
    fullGrown = 6,
    harvestPosition = "High",
}

farming_vegetableconf.props.Hops = {
    icon = "Item_Hops",
    texture = "vegetation_farming_01b_30",
--     waterLvl = 35,
    waterLvl = 30,
    waterNeeded = 70,
--     timeToGrow = 432,
    timeToGrow = 960,
    minVeg = 3,
    maxVeg = 4,
    minVegAutorized = 5,
    maxVegAutorized = 9,
    vegetableName =  "Base.Hops",
--     produceExtra =  "Base.HayTuft",
    seedName = "Base.HopsSeed",
    seedTypes = { "Base.HopsSeed",},
    badMonth = { 6, 7 },
    sowMonth = { 8, 9, 10 },
    bestMonth = { 9 },
    riskMonth = { 10 },
    seasonRecipe = "Hops Growing Season",
    harvestLevel = 6,
    mature = 5,
    fullGrown = 6,
}

farming_vegetableconf.props.Kale = {
    icon = "Item_Kale",
    texture = "vegetation_farming_01_94",
--     waterLvl = 85,
    waterLvl = 70,
--     waterNeeded = 80,
    waterNeeded = 70,
    timeToGrow = 292,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 5,
    maxVegAutorized = 8,
    vegetableName =  "Base.Kale",
    seedName = "Base.KaleSeed",
--     seedTypes = { "Base.KaleSeed", },
    badMonth = { 11, 12, 1 },
    badMonthHardyLevel = 3,
    sowMonth = { 2, 3, 4, 5, 6, 7, 8 },
    bestMonth = { 3, 7 },
    riskMonth = { 8 },
    seasonRecipe = "Kale Growing Season",
    harvestLevel = 5,
    mature = 5,
    fullGrown = 6,
    growBack = 2,
    coldHardy = true,
    mothFood = true,
}

farming_vegetableconf.props.Lettuce = {
    icon = "Item_Lettuce",
    texture = "vegetation_farming_01b_118",
--     waterLvl = 75,
    waterLvl = 70,
    timeToGrow = 292,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName =  "Base.Lettuce",
    seedName = "Base.LettuceSeed",

    harvestLevel = 5,
--     waterNeeded = 85,
    waterNeeded = 80,
    mature = 5,
    fullGrown = 6,
    badMonth = { 10, 11, 12, 1 },
    sowMonth = { 2, 3, 4, 7, 8, 9 },
    bestMonth = { 3, 7 },
	riskMonth = { 9 },
    -- riskMonth = { 7 },
    seasonRecipe = "Lettuce Growing Season",
}

farming_vegetableconf.props.Onion = {
    icon = "Item_Onion",
    texture = "vegetation_farming_01_126",
--     waterLvl = 35,
    waterLvl = 30,
    -- waterLvlMax = 85,
    waterNeeded = 70,
    timeToGrow = 432,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 5,
    maxVegAutorized = 8,
    vegetableName =  "Base.Onion",
    seedName = "Base.OnionSeed",
    seedTypes = {"Base.OnionSeed", "Base.Onion",},
    badMonth = { 7, 8, 9, 10, 11, 12, 1 },
    sowMonth = {  2, 3 },
    bestMonth = { 2 },
	riskMonth = { 3 },
    seasonRecipe = "Onion Growing Season",
    harvestLevel = 5,
    mature = 5,
    fullGrown = 6,
    aphidsBane = true,
    slugsProof = true,
    fliesBane = true,
    rabbitBane = true,
    mothFood = true,
}

farming_vegetableconf.props["Potatoes"] = {
    icon = "Item_Potato",
    texture = "vegetation_farming_01_46",
--     waterLvl = 65,
    waterLvl = 60,
    timeToGrow = 432,
    minVeg = 3,
    maxVeg = 4,
    minVegAutorized = 5,
    maxVegAutorized = 9,
    vegetableName = "Base.Potato",
    seedName = "Base.PotatoSeed",
    seedTypes = {"Base.PotatoSeed", "Base.Potato",},

    harvestLevel = 5,
    waterNeeded = 70,
    mature = 5,
    fullGrown = 6,
    badMonth = { 8, 9, 10, 11, 12, 1 },
    sowMonth = { 2, 3, 4 },
    bestMonth =  { 3 },
	riskMonth = { 4 },
    seasonRecipe = "Potato Growing Season",
    slugsProof = true,
    mothFood = true,
}

farming_vegetableconf.props.Pumpkin = {
    texture = "vegetation_farming_01b_110",
    icon = "Item_Pumpkin",
--     waterLvl = 35,
    waterLvl = 70,
    timeToGrow = 432,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 5,
    maxVegAutorized = 8,
    vegetableName =  "Base.Pumpkin",
    seedName = "Base.Pumpkin",
    seedTypes = { "Base.PumpkinSeed", },

    harvestLevel = 5,
    waterNeeded = 70,
    mature = 5,
    fullGrown = 6,
    badMonth = { 8, 9, 10, 11, 12, 1, 2 },
    sowMonth = { 3, 4, 5 },
    bestMonth = { 4 },
	riskMonth = { 5 },
    seasonRecipe = "Pumpkin Growing Season",
}

farming_vegetableconf.props["Radishes"] = {
    icon = "Item_Radish",
    texture = "vegetation_farming_01_54",
--     waterLvl = 45,
    waterLvl = 40,
--     waterLvlMax = 85,
    timeToGrow = 144,
    minVeg = 4,
    maxVeg = 9,
    minVegAutorized = 11,
    maxVegAutorized = 15,
    vegetableName = "Base.RedRadish",
    seedName = "Base.RedRadishSeed",

    harvestLevel = 5,
    waterNeeded = 70,
    rotTime = 224,
    mature = 5,
    fullGrown = 6,
    badMonth = { 9, 10, 11, 12, 1 },
    sowMonth = { 2, 3, 4, 5, 6, 7, 8 },
    bestMonth = { 3, 7 },
    riskMonth = { 8 },
    seasonRecipe = "Radish Growing Season",
    slugsProof = true,
    mothFood = true,
--     seedTypes = {"Base.RedRadishSeed",},
}

farming_vegetableconf.props.Rye = {
    icon = "Item_RyeWheat",
    texture = "vegetation_farming_01b_38",
--     waterLvl = 35,
    waterLvl = 30,
    waterNeeded = 70,
     timeToGrow = 432,
--    timeToGrow = 960,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName =  "Base.RyeSheaf",
--     produceExtra =  "Base.HayTuft",
    seedName = "Base.RyeSheaf",
    seedTypes = { "Base.RyeSeed",},
    badMonth = { 6, 7 },
    sowMonth = { 8, 9, 10 },
    bestMonth = { 9 },
    riskMonth = { 10 },
    seasonRecipe = "Rye Growing Season",
    harvestLevel = 6,
    mature = 5,
    fullGrown = 6,
    scytheHarvest = true,
    harvestPosition = "High",
    coldHardy = true,
}

farming_vegetableconf.props.Soybeans = {
    icon = "Item_Soybeans",
    texture = "vegetation_farming_01_86",
--     waterLvl = 65,
    waterLvl = 60,
    waterNeeded = 70,
    timeToGrow = 432,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName =  "Base.Soybeans",
    seedName = "Base.Soybeans",
    seedTypes = { "Base.SoybeansSeed", "Base.Soybeans",},
    badMonth = { 8, 9, 10, 11, 12, 1, 2 },
    sowMonth = { 3, 4, 5 },
    bestMonth = { 4 },
    riskMonth = { 5 },
    seasonRecipe = "Soybean Growing Season",
    harvestLevel = 5,
    mature = 5,
    fullGrown = 6,
}

farming_vegetableconf.props["Spinach"] = {
    icon = "Item_Spinach.png",
    waterLvl = 70,
    texture = "vegetation_farming_01b_126",
    timeToGrow = 292,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName = "Base.Spinach",
    seedName = "Base.SpinachSeed",

    harvestLevel = 5,
    waterNeeded = 70,
    rotTime = 248,
    mature = 5,
    fullGrown = 6,
    badMonth = { 9, 10, 11, 12, 1 },
    sowMonth = { 2, 3, 4, 5, 6, 7 },
    bestMonth = { 3, 6 },
    riskMonth = { 7 },
    seasonRecipe = "Spinach Growing Season",
    mothFood = true,
}

farming_vegetableconf.props["Strawberryplant"] = {
    icon = "Item_BerryStraw",
    texture = "vegetation_farming_01_62",
--     waterLvl = 85,
    waterLvl = 80,
--     timeToGrow = 432,
    timeToGrow = 360,
    minVeg = 4,
    maxVeg = 6,
    minVegAutorized = 8,
    maxVegAutorized = 14,
    vegetableName = "Base.Strewberrie",
    seedName = "Base.Strewberrie",

    harvestLevel = 6,
--     waterNeeded = 85,
    waterNeeded = 80,
    mature = 5,
    fullGrown = 6,
    specialSeed = "Base.Strewberrie",
    badMonth = { 7, 8, 9, 10, 11, 12, 1 },
    sowMonth = { 2, 3, 4 },
    bestMonth = { 3 },
	riskMonth = { 4 },
    seasonRecipe = "Strawberry Growing Season",
    seedTypes = {"Base.StrewberrieSeed", },
--     growBack = 1,
    growBack = 2,
}

farming_vegetableconf.props["SugarBeets"] = {
    icon = "Item_SugarBeets",
    texture = "vegetation_farming_01b_46",
--     waterLvl = 45,
    waterLvl = 40,
--     waterLvlMax = 85,
    timeToGrow = 292,
    minVeg = 4,
    maxVeg = 9,
    minVegAutorized = 11,
    maxVegAutorized = 15,
    vegetableName = "Base.SugarBeet",
    seedName = "Base.SugarBeetSeed",

    harvestLevel = 5,
    waterNeeded = 70,
    rotTime = 224,
    mature = 5,
    fullGrown = 6,
    badMonth = { 9, 10, 11, 12, 1 },
    sowMonth = { 2, 3, 4, 5, 6, 7 },
    bestMonth = { 3, 6 },
    riskMonth = { 7 },
    seasonRecipe = "Sugar Beet Growing Season",
    mothFood = true,
--     seedTypes = {"Base.RedRadishSeed",},
}

farming_vegetableconf.props["Sunflower"] = {
    icon = "Item_SunflowerHead",
    texture = "vegetation_farming_01b_54",
    --     waterLvl = 45,
    waterLvl = 30,
    --     waterLvlMax = 85,
    timeToGrow = 432,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName = "Base.SunflowerHead",
    seedName = "Base.SunflowerSeeds",

    harvestLevel = 5,
    waterNeeded = 70,
    mature = 5,
    fullGrown = 6,
    badMonth = { 8, 9, 10, 11, 12, 1, 2 },
    sowMonth = { 3, 4, 5 },
    bestMonth = { 4 },
	riskMonth = { 5 },
    seasonRecipe = "Sunflower Growing Season",
    harvestPosition = "High",
}

farming_vegetableconf.props.SweetPotato = {
    icon = "Item_SweetPotato",
    texture = "vegetation_farming_01_94",
--     waterLvl = 65,
    waterLvl = 60,
    -- waterLvlMax = 85,
    waterNeeded = 70,
    timeToGrow = 432,
    minVeg = 3,
    maxVeg = 4,
    minVegAutorized = 5,
    maxVegAutorized = 9,
    vegetableName =  "Base.SweetPotato",
    seedName = "Base.SweetPotatoSeed",
    seedTypes = { "Base.SweetPotatoSeed", "Base.SweetPotato",},
    badMonth = { 10, 11, 12, 1, 2 },
    sowMonth = { 5, 6, 7 },
    bestMonth = { 6 },
    riskMonth = { 7 },
    seasonRecipe = "Sweet Potato Growing Season",
    harvestLevel = 5,
    mature = 5,
    fullGrown = 6,
}

farming_vegetableconf.props["Tobacco"] = {
    icon = "media/textures/Item_Tobacco.png",
    waterLvl = 70,
    texture = "vegetation_farming_01b_62",
    timeToGrow = 866,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName = "Base.Tobacco",
    seedName = "Base.TobaccoSeed",

    harvestLevel = 5,
    waterNeeded = 70,
    rotTime = 248,
    mature = 5,
    fullGrown = 6,
    badMonth = { 9, 10, 11, 12, 1, 2 },
    sowMonth = { 3, 4, 5, 6, 7 },
    bestMonth = { 3 },
    riskMonth = { 7  },
    seasonRecipe = "Tobacco Growing Season",
    mothFood = true,
}

farming_vegetableconf.props["Tomato"] = {
    icon = "Item_Tomato",
    texture = "vegetation_farming_01_70",
--     waterLvl = 75,
    waterLvl = 70,
--     timeToGrow = 432,
    timeToGrow = 360,
    minVeg = 4,
    maxVeg = 5,
    minVegAutorized = 6,
    maxVegAutorized = 10,
    vegetableName = "Base.Tomato",
    seedName =  "Base.Tomato",

    harvestLevel = 6,
--     waterNeeded = 85,
    waterNeeded = 80,
    mature = 5,
    fullGrown = 6,
    specialSeed = "Base.Tomato",
    badMonth = { 10, 11, 12, 1, 2, 3 },
    sowMonth = { 4, 5, 6 },
    bestMonth = { 5 },
    riskMonth = { 6 },
    seasonRecipe = "Tomato Growing Season",
    seedTypes = {"Base.TomatoSeed",},
    harvestPosition = "Mid",
    slugsProof = true,
    mothFood = true,
}

farming_vegetableconf.props.Turnip = {
    icon = "Item_Turnip",
    texture = "vegetation_farming_01_94",
--     waterLvl = 65,
    waterLvl = 60,
    -- waterLvlMax = 85,
    waterNeeded = 70,
    timeToGrow = 292,
    minVeg = 3,
    maxVeg = 4,
    minVegAutorized = 5,
    maxVegAutorized = 9,
    vegetableName =  "Base.Turnip",
    seedName = "Base.TurnipSeed",
    seedTypes = { "Base.TurnipSeed", },
    badMonth = { 11, 12, 1, 2 },
    sowMonth = { 5, 6, 7, 8, 9, 10 },
    bestMonth = { 6, 9 },
    riskMonth = { 7, 10 },
    seasonRecipe = "Turnip Growing Season",
    harvestLevel = 5,
    mature = 5,
    fullGrown = 6,
}

farming_vegetableconf.props.Watermelon = {
    texture = "vegetation_farming_01b_134",
    icon = "Item_Watermelon",
--     waterLvl = 35,
    waterLvl = 70,
    timeToGrow = 432,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 5,
    maxVegAutorized = 8,
    vegetableName =  "Base.Watermelon",
    seedName = "Base.Watermelon",
    seedTypes = { "Base.WatermelonSeed", },

    harvestLevel = 5,
    waterNeeded = 80,
    mature = 5,
    fullGrown = 6,
    badMonth = { 10, 11, 12, 1, 2 },
    sowMonth = { 3, 4, 5 },
    bestMonth = { 4 },
    riskMonth = { 5 },
    seasonRecipe = "Watermelon Growing Season",
}

farming_vegetableconf.props.Wheat = {
    icon = "Item_WheatBundle",
    texture = "vegetation_farming_01_118",
--     waterLvl = 35,
    waterLvl = 30,
    waterNeeded = 70,
     timeToGrow = 432,
--    timeToGrow = 960,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName =  "Base.WheatSheaf",
--     produceExtra =  "Base.HayTuft",
    seedName = "Base.WheatSheaf",
    seedTypes = { "Base.WheatSeed", },
    badMonth = { 6, 7 },
    sowMonth = { 8, 9, 10 },
    bestMonth = { 9 },
    riskMonth = { 10 },
    seasonRecipe = "Wheat Growing Season",
    harvestLevel = 6,
    mature = 5,
    fullGrown = 6,
    scytheHarvest = true,
    harvestPosition = "High",
    coldHardy = true,
}

farming_vegetableconf.props.Zucchini = {
    texture = "vegetation_farming_01b_110",
    icon = "Item_Zucchini",
--     waterLvl = 35,
    waterLvl = 70,
    timeToGrow = 432,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName =  "Base.Zucchini",
    seedName = "Base.Zucchini",
    seedTypes = { "Base.ZucchiniSeed", },

    harvestLevel = 5,
    waterNeeded = 70,
    mature = 5,
    fullGrown = 6,
    badMonth = { 8, 9, 10, 11, 12, 1, 2 },
    sowMonth = { 3, 4, 5 },
    bestMonth = { 4 },
	riskMonth = { 5 },
    seasonRecipe = "Zucchini Growing Season",
}