require "Farming/farming_vegetableconf"

farming_vegetableconf.props.Basil = {
    texture = "vegetation_farming_02_4",
    icon = "Item_HerbBasil",
    seedName = "Base.BasilSeed",
    seedTypes = {"Base.BasilSeed", "Base.Basil", },
    vegetableName = "Base.Basil",
    waterLvl = 80,
    timeToGrow = 484,
    minVeg = 4,
    maxVeg = 6,
    minVegAutorized = 9,
    maxVegAutorized = 11,
    waterNeeded = 70,
    badMonth = { 8, 9, 10, 11, 12, 1 },
    sowMonth = { 3, 4, 5 },
    bestMonth = { 4 },
    seasonRecipe = "Basil Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
    growBack = 2,
    fliesBane = true,
--     waterLvlMax = 85,
}

farming_vegetableconf.props.BlackSage = {
    texture = "vegetation_farming_02_116",
    icon = "Item_BlackSage",
    seedName = "Base.BlackSageSeed",
    vegetableName = "Base.BlackSage",
    waterLvl = 60,
    timeToGrow = 484,
    minVeg = 4,
    maxVeg = 6,
    minVegAutorized = 9,
    maxVegAutorized = 11,
    waterNeeded = 70,
    badMonth = { 12, 1, 2, 10, 11 },
    sowMonth = { 3, 4, 5, 6, 7, 8,  },
    riskMonth = {  6, 7,   },
    seasonRecipe = "Black Sage Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
}

farming_vegetableconf.props.BroadleafPlantain = {
    texture = "vegetation_farming_02_132",
    icon = "Item_PlantainPlantago",
    seedName = "Base.BroadleafPlantainSeed",
    vegetableName = "Base.Plantain",
    waterLvl = 60,
    timeToGrow = 484,
    minVeg = 4,
    maxVeg = 6,
    minVegAutorized = 9,
    maxVegAutorized = 11,
    waterNeeded = 70,
    badMonth = { 12, 1, 2, 10, 11 },
    sowMonth = { 3, 4, 5, 6, 7, 8,  },
    riskMonth = {  6, 7,   },
    seasonRecipe = "Broadleaf Plantain Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
}

farming_vegetableconf.props.Chamomile = {
    texture = "vegetation_farming_02_140",
    icon = "Item_Chamomile",
    seedName = "Base.ChamomileSeed",
    seedTypes = {"Base.ChamomileSeed", "Base.Chamomile", },
    vegetableName = "Base.Chamomile",
    waterLvl = 80,
    timeToGrow = 484,
    minVeg = 4,
    maxVeg = 6,
    minVegAutorized = 9,
    maxVegAutorized = 11,
    waterNeeded = 70,
    badMonth = { 8, 9, 10, 11, 12, 1 },
    sowMonth = { 3, 4, 5 },
    bestMonth = { 4 },
    seasonRecipe = "Chamomile Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
    growBack = 2,
	isFlower = true,
--     waterLvlMax = 85,
}

farming_vegetableconf.props.Chives = {
    texture = "vegetation_farming_02_12",
    icon = "Item_HerbChives",
    seedName = "Base.ChivesSeed",
    seedTypes = {"Base.ChivesSeed", "Base.Chives", },
    vegetableName = "Base.Chives",
    waterLvl = 60,
    timeToGrow = 484,
    minVeg = 4,
    maxVeg = 6,
    minVegAutorized = 9,
    maxVegAutorized = 11,
    waterNeeded = 70,
    badMonth = { 12, 1, 2, 10, 11 },
    sowMonth = { 3, 4, 5, 6, 7, 8,  },
    riskMonth = {  6, 7,   },
    seasonRecipe = "Chives Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
    growBack = 2,
    aphidsBane = true,
    slugsProof = true,
}

farming_vegetableconf.props.Cilantro = {
    texture = "vegetation_farming_02_20",
    icon = "Item_HerbCilantro",
    seedName = "Base.CilantroSeed",
    seedTypes = {"Base.CilantroSeed", "Base.Cilantro", },
    vegetableName = "Base.Cilantro",
    waterLvl = 70,
    timeToGrow = 484,
    minVeg = 4,
    maxVeg = 6,
    minVegAutorized = 9,
    maxVegAutorized = 11,
    waterNeeded = 70,
    badMonth = { 7, 8, 9, 10, 11, 12, 1 },
    sowMonth = { 3, 4, 5 },
    bestMonth = { 4 },
    seasonRecipe = "Cilantro Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
    growBack = 2,
    slugsProof = true,
}

farming_vegetableconf.props.Comfrey = {
    texture = "vegetation_farming_02_108",
    icon = "Item_Comfrey",
    seedName = "Base.ComfreySeed",
    vegetableName = "Base.Comfrey",
    waterLvl = 60,
    timeToGrow = 484,
    minVeg = 4,
    maxVeg = 6,
    minVegAutorized = 9,
    maxVegAutorized = 11,
    waterNeeded = 70,
    badMonth = { 12, 1, 2, 10, 11 },
    sowMonth = { 3, 4, 5, 6, 7, 8,  },
    riskMonth = {  6, 7,   },
    seasonRecipe = "Comfrey Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
}

farming_vegetableconf.props.CommonMallow = {
    texture = "vegetation_farming_02_108",
    icon = "Item_CommonMallow",
    seedName = "Base.CommonMallowSeed",
    vegetableName = "Base.CommonMallow",
    waterLvl = 60,
    timeToGrow = 484,
    minVeg = 4,
    maxVeg = 6,
    minVegAutorized = 9,
    maxVegAutorized = 11,
    waterNeeded = 70,
    badMonth = { 12, 1, 2, 10, 11 },
    sowMonth = { 3, 4, 5, 6, 7, 8,  },
    riskMonth = {  6, 7,   },
    seasonRecipe = "Common Mallow Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
}

farming_vegetableconf.props.Habanero = {
    icon = "Item_PepperHabanero",
    texture = "vegetation_farming_02_68",
--     waterLvl = 75,
    waterLvl = 70,
    timeToGrow = 487,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName =  "Base.PepperHabanero",
    seedName = "Base.PepperHabanero",
    seedTypes = { "Base.HabaneroSeed", },

    harvestLevel = 5,
--     waterNeeded = 85,
    waterNeeded = 70,
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
    badMonth = { 10, 11, 12, 1, 2, 3},
    sowMonth = { 4, 5, 6},
    bestMonth = { 5 },
    riskMonth = { 6 },
    seasonRecipe = "Habanero Growing Season",
}

farming_vegetableconf.props.Jalapeno = {
    icon = "Item_PepperJalapeno",
    texture = "vegetation_farming_02_76",
--     waterLvl = 75,
    waterLvl = 70,
    timeToGrow = 487,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 6,
    maxVegAutorized = 8,
    vegetableName =  "Base.PepperJalapeno",
    seedName = "Base.PepperJalapeno",
    seedTypes = { "Base.JalapenoSeed", },

    harvestLevel = 5,
--     waterNeeded = 85,
    waterNeeded = 70,
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
    badMonth = { 10, 11, 12, 1, 2, 3},
    sowMonth = { 4, 5, 6},
    bestMonth = { 5 },
    riskMonth = { 6 },
    seasonRecipe = "Jalapeno Growing Season",
}

farming_vegetableconf.props.Lavender = {
    texture = "vegetation_gardening_01_20",
    icon = "Item_Bouquet_Lavender",
    seedName = "Base.LavenderSeed",
    seedTypes = {"Base.LavenderSeed",  },
    vegetableName = "Base.Lavender",
    waterLvl = 80,
    timeToGrow = 484,
    minVeg = 4,
    maxVeg = 6,
    minVegAutorized = 9,
    maxVegAutorized = 11,
    waterNeeded = 70,
    badMonth = { 8, 9, 10, 11, 12, 1 },
    sowMonth = { 3, 4, 5 },
    bestMonth = { 4 },
    seasonRecipe = "Lavender Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
    growBack = 2,
	isFlower = true,
}

farming_vegetableconf.props.Leek = {
    texture = "vegetation_farming_02_84",
    icon = "Item_Leek",
    seedName = "Base.LeekSeed",
    vegetableName = "Base.Leek",
--     waterLvl = 35,
    waterLvl = 70,
    timeToGrow = 1203,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 5,
    maxVegAutorized = 8,
    waterNeeded = 70,
    badMonth = { 12, 1, 2, 10, 11 },
    sowMonth = { 2, 3, 4, 5, 6, 7, 8, 9,  },
    seasonRecipe = "Leek Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
--     waterLvlMax = 85,
    aphidsBane = true,
    slugsProof = true,
    coldHardy = true,
--     mothBane = true,
    rabbitBane = true,
}

farming_vegetableconf.props.LemonGrass = {
    texture = "vegetation_farming_02_92",
    icon = "Item_LemonGrass",
    seedName = "Base.LemonGrassSeed",
    vegetableName = "Base.LemonGrass",
    seedTypes = {"Base.LemonGrassSeed", "Base.LemonGrass", },
--     waterLvl = 35,
    waterLvl = 70,
    timeToGrow = 484,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 5,
    maxVegAutorized = 8,
    waterNeeded = 70,
    badMonth = { 12, 1, 2, 10, 11 },
    sowMonth = { 2, 3, 4, 5, 6, 7, 8, 9,  },
    seasonRecipe = "Lemongrass Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
    growBack = 2,
    aphidsBane = true,
    slugsBane = true,
    mothBane = true,
    rabbitBane = true,
    deerBane = true,
}

farming_vegetableconf.props.Marigold = {
    texture = "vegetation_farming_02_148",
    icon = "Item_Marigold",
    seedName = "Base.MarigoldSeed",
    seedTypes = {"Base.MarigoldSeed", "Base.Marigold", },
    vegetableName = "Base.Marigold",
    waterLvl = 80,
    timeToGrow = 484,
    minVeg = 4,
    maxVeg = 6,
    minVegAutorized = 9,
    maxVegAutorized = 11,
    waterNeeded = 70,
    badMonth = { 8, 9, 10, 11, 12, 1 },
    sowMonth = { 3, 4, 5 },
    bestMonth = { 4 },
    seasonRecipe = "Marigold Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
    growBack = 2,
	aphidsBane = true,
	fliesBane = true,
	isFlower = true,
--     waterLvlMax = 85,
}

farming_vegetableconf.props.Mint = {
    texture = "vegetation_farming_02_156",
    icon = "Item_Mint",
    seedName = "Base.MintSeed",
    seedTypes = {"Base.MintSeed", "Base.MintHerb", },
    vegetableName = "Base.MintHerb",
    waterLvl = 70,
    timeToGrow = 484,
    minVeg = 4,
    maxVeg = 6,
    minVegAutorized = 9,
    maxVegAutorized = 11,
    waterNeeded = 70,
    badMonth = { 6, 7, 8, 9, 10, 11, 12, 1 },
    sowMonth = { 2, 3, 4 },
    bestMonth = { 3 },
    seasonRecipe = "Mint Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
    growBack = 2,
--     waterLvlMax = 85,
}

farming_vegetableconf.props.Oregano = {
    texture = "vegetation_farming_02_28",
    icon = "Item_HerbOregano",
    seedName = "Base.OreganoSeed",
    seedTypes = {"Base.OreganoSeed", "Base.Oregano", },
    vegetableName = "Base.Oregano",
    waterLvl = 60,
    timeToGrow = 484,
    minVeg = 4,
    maxVeg = 6,
    minVegAutorized = 9,
    maxVegAutorized = 11,
    waterNeeded = 70,
    badMonth = { 7, 8, 9, 10, 11, 12, 1 },
    sowMonth = { 2, 3, 4 },
    bestMonth = { 3 },
    seasonRecipe = "Oregano Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
    growBack = 2,
    slugsProof = true,
    mothBane = true,
    deerBane = true,
}

farming_vegetableconf.props.Parsley = {
    texture = "vegetation_farming_02_36",
    icon = "Item_HerbParsley",
    seedName = "Base.ParsleySeed",
    seedTypes = {"Base.ParsleySeed", "Base.Parsley", },
    vegetableName = "Base.Parsley",
    waterLvl = 70,
    timeToGrow = 484,
    minVeg = 4,
    maxVeg = 6,
    minVegAutorized = 9,
    maxVegAutorized = 11,
    waterNeeded = 70,
    badMonth = { 6, 7, 8, 9, 10, 11, 12, 1 },
    sowMonth = { 2, 3, 4 },
    bestMonth = { 3 },
    seasonRecipe = "Parsley Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
    growBack = 2,
    slugsProof = true,
}

farming_vegetableconf.props.Poppies = {
    texture = "vegetation_gardening_01_12",
    icon = "Item_Bouquet_Poppy",
    seedName = "Base.PoppyPods",
    seedTypes = {"Base.PoppySeed",  },
    vegetableName = "Base.Poppies",
    waterLvl = 80,
    timeToGrow = 484,
    minVeg = 4,
    maxVeg = 6,
    minVegAutorized = 9,
    maxVegAutorized = 11,
    waterNeeded = 70,
    badMonth = { 8, 9, 10, 11, 12, 1 },
    sowMonth = { 3, 4, 5 },
    bestMonth = { 4 },
    seasonRecipe = "Poppy Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
    growBack = 2,
}

farming_vegetableconf.props.Rosemary = {
    texture = "vegetation_farming_02_50",
    icon = "Item_HerbRosemary",
    seedName = "Base.RosemarySeed",
    seedTypes = {"Base.RosemarySeed", "Base.Rosemary", },
    vegetableName = "Base.Rosemary",
--     waterLvl = 35,
    waterLvl = 30,
    timeToGrow = 1444,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 5,
    maxVegAutorized = 8,
    waterNeeded = 70,
    badMonth = { 12, 1, 2, 10, 11 },
    sowMonth = { 2, 3, 4, 5, 6, 7, 8, 9,  },
    seasonRecipe = "Rosemary Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
    growBack = 2,
--     waterLvlMax = 85,
    slugsBane = true,
    aphidsBane = true,
    mothBane = true,
    fliesBane = true,
	isFlower = true,
}

farming_vegetableconf.props.Roses = {
    texture = "vegetation_gardening_01_4",
    icon = "Item_Bouquet_Rose",
    seedName = "Base.RoseSeed",
    seedTypes = {"Base.RoseSeed",  },
    vegetableName = "Base.Roses",
    waterLvl = 80,
    timeToGrow = 484,
    minVeg = 4,
    maxVeg = 6,
    minVegAutorized = 9,
    maxVegAutorized = 11,
    waterNeeded = 70,
    badMonth = { 8, 9, 10, 11, 12, 1 },
    sowMonth = { 3, 4, 5 },
    bestMonth = { 4 },
    seasonRecipe = "Rose Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
    growBack = 2,
	isFlower = true,
}

farming_vegetableconf.props.Sage = {
    texture = "vegetation_farming_02_42",
    icon = "Item_HerbSage",
    seedName = "Base.SageSeed",
    seedTypes = {"Base.SageSeed", "Base.Sage", },
    vegetableName = "Base.Sage",
--     waterLvl = 35,
    waterLvl = 30,
    timeToGrow = 721,
    minVeg = 4,
    maxVeg = 6,
    minVegAutorized = 9,
    maxVegAutorized = 11,
    waterNeeded = 70,
    badMonth = { 7, 8, 9, 10, 11, 12 },
    sowMonth = { 2, 3, 4 },
    bestMonth = { 3 },
    seasonRecipe = "Sage Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
    growBack = 2,
    fliesBane = true,
    mothBane = true,
}

farming_vegetableconf.props.Thyme = {
    texture = "vegetation_farming_02_58",
    icon = "Item_HerbThyme",
    seedName = "Base.ThymeSeed",
    seedTypes = {"Base.ThymeSeed", "Base.Thyme", },
    vegetableName = "Base.Thyme",
--     waterLvl = 35,
    waterLvl = 30,
    timeToGrow = 484,
    minVeg = 4,
    maxVeg = 6,
    minVegAutorized = 9,
    maxVegAutorized = 11,
    waterNeeded = 70,
    badMonth = { 8, 9, 10, 11, 12, 1 },
    sowMonth = { 2, 3, 4},
    bestMonth = { 3 },
    seasonRecipe = "Thyme Growing Season",
    harvestLevel = 3,
    mature = 3,
    fullGrown = 4,
    growBack = 2,
    aphidsBane = true,
    mothBane = true,
}

farming_vegetableconf.props.WildGarlic = {
    texture = "vegetation_farming_02_100",
    icon = "Item_WildGarlic",
--     waterLvl = 35,
    waterLvl = 30,
--     timeToGrow = 432,
    timeToGrow = 1152,
    -- waterLvlMax = 85,
    minVeg = 2,
    maxVeg = 4,
    minVegAutorized = 5,
    maxVegAutorized = 8,
    vegetableName =  "Base.WildGarlic2",
    seedName = "Base.WildGarlicSeed",

    harvestLevel = 5,
    mature = 5,
    fullGrown = 6,
    waterNeeded = 70,
    badMonth = { 6, },
    sowMonth = { 7, 8, 9, },
    bestMonth = { 8 },
    riskMonth = { 9 },
    seasonRecipe = "Wild Garlic Growing Season",
    seedTypes = { "Base.WildGarlicSeed", "Base.WildGarlic2",},
    aphidsBane = true,
    slugsProof = true,
    coldHardy = true,
    mothBane = true,
    rabbitBane = true,
}
--
-- farming_vegetableconf.growHerbDefault = function(planting, nextGrowing, updateNbOfGrow)
-- 	local nbOfGrow = planting.nbOfGrow;
-- 	local water = farming_vegetableconf.calcWater(planting.waterNeeded, planting.waterLvl);
-- 	local waterMax = farming_vegetableconf.calcWater(planting.waterLvl, planting.waterNeededMax) or 0;
-- 	-- disease level can be either positive or negative; if either is a negative number than we want the lower of the two; otherwise we want the greater of thetwo
-- 	local diseaseLvl = farming_vegetableconf.calcDisease(planting.mildewLvl)
-- 	local diseaseLvl2 = farming_vegetableconf.calcDisease(planting.slugsLvl)
-- 	if diseaseLvl < 0 or diseaseLvl2 < 2 then
-- 		if diseaseLvl2 < diseaseLvl then diseaseLvl = diseaseLvl2 end
-- 	else
-- 		if diseaseLvl2 > diseaseLvl then diseaseLvl = diseaseLvl2 end
-- 	end
-- 	if (nbOfGrow == 0) then -- young
-- 			planting = growNext(planting, farming_vegetableconf.getSpriteName(planting), farming_vegetableconf.getObjectName(planting), nextGrowing, farming_vegetableconf.props[planting.typeOfSeed].timeToGrow + water + diseaseLvl);
-- 			planting.waterNeeded = farming_vegetableconf.props[planting.typeOfSeed].waterNeeded;
-- 	elseif (nbOfGrow <= 2) then -- young herb
-- 		if(water >= 0 and diseaseLvl >= 0) then
-- 			planting = growNext(planting, farming_vegetableconf.getSpriteName(planting), farming_vegetableconf.getObjectName(planting), nextGrowing, farming_vegetableconf.props[planting.typeOfSeed].timeToGrow + water + diseaseLvl);
-- 			planting.waterNeeded = farming_vegetableconf.props[planting.typeOfSeed].waterLvl;
-- 		else
-- 			badPlant(water, nil, diseaseLvl, planting, nextGrowing, updateNbOfGrow);
-- 		end
-- 	elseif (nbOfGrow == 3) then -- mature herb
-- 		if(water >= 0 and diseaseLvl >= 0) then
-- 			planting.nextGrowing = calcNextGrowing(nextGrowing, farming_vegetableconf.props[planting.typeOfSeed].timeToGrow + water + diseaseLvl);
-- 			planting:setObjectName(farming_vegetableconf.getObjectName(planting))
-- 			planting:setSpriteName(farming_vegetableconf.getSpriteName(planting))
-- 			planting.hasVegetable = true;
-- 		else
-- 			badPlant(water, nil, diseaseLvl, planting, nextGrowing, updateNbOfGrow);
-- 		end
-- 	elseif (nbOfGrow == 4) then -- mature herb with seed
-- 		if(water >= 0) then
-- 			planting.nextGrowing = calcNextGrowing(nextGrowing, 248);
-- 			planting:setObjectName(farming_vegetableconf.getObjectName(planting))
-- 			planting:setSpriteName(farming_vegetableconf.getSpriteName(planting))
-- 			planting.hasVegetable = true;
-- 			planting.hasSeed = true;
-- 		else
-- 			badPlant(water, nil, diseaseLvl, planting, nextGrowing, updateNbOfGrow);
-- 		end
-- 	elseif (planting.state ~= "rotten") then -- rotten herb
-- 		planting:rottenThis()
-- 	end
-- 	return planting;
-- end
