--
-- Created by IntelliJ IDEA.
-- User: RJ
-- Date: 06/02/14
-- Time: 10:22
-- To change this template use File | Settings | File Templates.
--

-- Traps definition
Traps = {};
local crateTrap = {};
crateTrap.type = "Base.TrapCrate";
crateTrap.sprite = "constructedobjects_01_3";
crateTrap.closedSprite = "constructedobjects_01_2";
crateTrap.trapStrength = 15;
crateTrap.destroyItem = { "Base.UnusableWood", "Base.Nails" };
table.insert(Traps, crateTrap);
local trapBox = {};
trapBox.type = "Base.TrapBox";
trapBox.sprite = "constructedobjects_01_4";
trapBox.northSprite = "constructedobjects_01_7";
trapBox.closedSprite = "constructedobjects_01_5";
trapBox.northClosedSprite = "constructedobjects_01_6";
trapBox.trapStrength = 15;
trapBox.destroyItem = { "Base.UnusableWood", "Base.Nails", "Base.Nails" };
table.insert(Traps, trapBox);
local cageTrap = {};
cageTrap.type = "Base.TrapCage";
cageTrap.sprite = "constructedobjects_01_8";
cageTrap.northSprite = "constructedobjects_01_11";
cageTrap.closedSprite = "constructedobjects_01_9";
cageTrap.northClosedSprite = "constructedobjects_01_10";
cageTrap.trapStrength = 20;
cageTrap.destroyItem = "Base.Wire";
table.insert(Traps, cageTrap);
local snareTrap = {};
snareTrap.type = "Base.TrapSnare";
snareTrap.sprite = "constructedobjects_01_16";
snareTrap.closedSprite = "constructedobjects_01_17";
snareTrap.trapStrength = 10;
snareTrap.destroyItem = { "Base.UnusableWood", "Base.Twine", "Base.Twine" };
table.insert(Traps, snareTrap);
local stickTrap = {};
stickTrap.type = "Base.TrapStick";
stickTrap.sprite = "constructedobjects_01_13";
stickTrap.closedSprite = "constructedobjects_01_12";
stickTrap.trapStrength = 15;
stickTrap.destroyItem = { "Base.UnusableWood", "Base.Twine" };
table.insert(Traps, stickTrap);
local mouseTrap = {};
mouseTrap.type = "Base.TrapMouse";
mouseTrap.sprite = "constructedobjects_01_18";
mouseTrap.closedSprite = "constructedobjects_01_19";
mouseTrap.trapStrength = 50;
mouseTrap.destroyItem = "Base.UnusableWood";
table.insert(Traps, mouseTrap);

-- Animals definition
TrapAnimals = TrapAnimals or {};
local rabbit = {};
rabbit.type = "rabbit";
-- after how many hour the animal will start to destroy the cage/escape
rabbit.strength = 24;
-- item given to the player
rabbit.item = "Base.DeadRabbit";
-- hour this animal will be out and when you can catch it
rabbit.minHour = 19;
rabbit.maxHour = 5;
-- min and max "size" (understand hunger reduction) of the animal
rabbit.minSize = 30;
rabbit.maxSize = 100;
rabbit.canBeAlive = true;
rabbit.aliveAnimals = {};
table.insert(rabbit.aliveAnimals, "rabbuck");
table.insert(rabbit.aliveAnimals, "rabdoe");
table.insert(rabbit.aliveAnimals, "rabkitten");
rabbit.aliveBreed = {};
table.insert(rabbit.aliveBreed, "swamp");
table.insert(rabbit.aliveBreed, "appalachian");
table.insert(rabbit.aliveBreed, "cottontail");
-- chance to get the animals per zone
rabbit.zone = {};
rabbit.zone["TownZone"] = 2;
rabbit.zone["TrailerPark"] = 2;
rabbit.zone["Vegitation"] = 10;
rabbit.zone["Forest"] = 12;
rabbit.zone["DeepForest"] = 15;
rabbit.zone["BirchForest"] = 12;
rabbit.zone["BirchMixForest"] = 12;
rabbit.zone["FarmForest"] = 12;
rabbit.zone["FarmMixForest"] = 12;
rabbit.zone["PRForest"] = 12;
rabbit.zone["PHForest"] = 12;
rabbit.zone["PHMixForest"] = 12;
rabbit.zone["OrganicForest"] = 15;
-- chance to get animals for each trap
rabbit.traps = {};
rabbit.traps["Base.TrapCage"] = 40;
rabbit.traps["Base.TrapSnare"] = 30;
rabbit.traps["Base.TrapBox"] = 30;
rabbit.traps["Base.TrapCrate"] = 30;
-- chance to attract animal per bait
rabbit.baits = {};
rabbit.baits["Base.Carrots"] = 45;
rabbit.baits["Base.Apple"] = 35;
rabbit.baits["Base.Lettuce"] = 40;
rabbit.baits["Base.BellPepper"] = 40;
rabbit.baits["Base.Cabbage"] = 40;
rabbit.baits["Base.Corn"] = 35;
rabbit.baits["Base.Banana"] = 35;
rabbit.baits["Base.Potato"] = 35;
rabbit.baits["Base.Tomato"] = 35;
rabbit.baits["Base.Peach"] = 35;

local squirrel = {};
squirrel.type = "squirrel";
squirrel.strength = 20;
squirrel.item = "Base.DeadSquirrel";
squirrel.minHour = 19;
squirrel.maxHour = 5;
squirrel.minSize = 10;
squirrel.maxSize = 60;
squirrel.zone = {};
squirrel.zone["TownZone"] = 2;
squirrel.zone["TrailerPark"] = 2;
squirrel.zone["Vegitation"] = 10;
squirrel.zone["Forest"] = 12;
squirrel.zone["DeepForest"] = 15;
squirrel.zone["BirchForest"] = 12;
squirrel.zone["BirchMixForest"] = 12;
squirrel.zone["FarmForest"] = 12;
squirrel.zone["FarmMixForest"] = 12;
squirrel.zone["PRForest"] = 12;
squirrel.zone["PHForest"] = 12;
squirrel.zone["PHMixForest"] = 12;
squirrel.zone["OrganicForest"] = 15;
squirrel.traps = {};
squirrel.traps["Base.TrapBox"] = 25;
squirrel.traps["Base.TrapCage"] = 40;
squirrel.traps["Base.TrapCrate"] = 30;
squirrel.traps["Base.TrapSnare"] = 30;
squirrel.baits = {};
squirrel.baits["Base.PeanutButter"] = 45;
squirrel.baits["Base.Cereal"] = 45;
squirrel.baits["Base.Orange"] = 40;
squirrel.baits["Base.Peanuts"] = 40;
squirrel.baits["Base.Apple"] = 40;
squirrel.baits["Base.Corn"] = 40;
squirrel.baits["Base.Popcorn"] = 40;
squirrel.baits["Base.Lettuce"] = 40;
squirrel.baits["Base.BellPepper"] = 30;
squirrel.baits["Base.Peach"] = 35;

local bird = {};
bird.type = "bird";
bird.item = "Base.DeadBird";
bird.minHour = 0;
bird.maxHour = 0;
bird.minSize = 2;
bird.maxSize = 32;
bird.zone = {};
bird.zone["Farm"] = 35;
bird.zone["FarmLand"] = 35;
bird.zone["TownZone"] = 30;
bird.zone["Vegitation"] = 30;
bird.zone["TrailerPark"] = 20;
bird.zone["Forest"] = 20;
bird.zone["DeepForest"] = 20;
bird.zone["BirchForest"] = 20;
bird.zone["BirchMixForest"] = 20;
bird.zone["OrganicForest"] = 20;
bird.zone["FarmForest"] = 20;
bird.zone["FarmMixForest"] = 20;
bird.zone["PRForest"] = 20;
bird.zone["PHForest"] = 20;
bird.zone["PHMixForest"] = 20;
bird.traps = {};
bird.traps["Base.TrapStick"] = 40;
bird.baits = {};
bird.baits["Base.AmericanLadyCaterpillar"] = 50;
bird.baits["Base.BandedWoolyBearCaterpillar"] = 50;
bird.baits["Base.Bread"] = 50;
bird.baits["Base.BreadSlices"] = 50;
bird.baits["Base.Centipede"] = 50;
bird.baits["Base.Centipede2"] = 50;
bird.baits["Base.Cereal"] = 45;
bird.baits["Base.Cockroach"] = 50;
bird.baits["Base.Corn"] = 45;
bird.baits["Base.Cricket"] = 50;
bird.baits["Base.Grasshopper"] = 50;
bird.baits["Base.Millipede"] = 50;
bird.baits["Base.Millipede2"] = 50;
bird.baits["Base.MonarchCaterpillar"] = 50;
bird.baits["Base.Pillbug"] = 50;
bird.baits["Base.SawflyLarva"] = 50;
bird.baits["Base.SilkMothCaterpillar"] = 50;
bird.baits["Base.SwallowtailCaterpillar"] = 50;
bird.baits["Base.Termites"] = 50;
bird.baits["Base.Worm"] = 50;

local mouse = {};
mouse.type = "mouse";
mouse.item = "Base.DeadMouse";
mouse.minHour = 0;
mouse.maxHour = 0;
mouse.minSize = 1;
mouse.maxSize = 10;
mouse.canBeAlive = true;
mouse.aliveAnimals = {};
table.insert(mouse.aliveAnimals, "mouse");
table.insert(mouse.aliveAnimals, "mousefemale");
table.insert(mouse.aliveAnimals, "mousepups");
mouse.aliveBreed = {};
table.insert(mouse.aliveBreed, "golden");
table.insert(mouse.aliveBreed, "deer");
table.insert(mouse.aliveBreed, "white");
mouse.zone = {};
mouse.zone["Farm"] = 60;
mouse.zone["FarmLand"] = 60;
mouse.zone["TownZone"] = 50;
mouse.zone["TrailerPark"] = 60;
mouse.zone["Vegitation"] = 20;
mouse.zone["Forest"] = 10;
mouse.zone["DeepForest"] = 10;
mouse.zone["BirchForest"] = 10;
mouse.zone["BirchMixForest"] = 10;
mouse.zone["OrganicForest"] = 10;
mouse.zone["FarmForest"] = 10;
mouse.zone["FarmMixForest"] = 10;
mouse.zone["PRForest"] = 10;
mouse.zone["PHForest"] = 10;
mouse.zone["PHMixForest"] = 10;
mouse.traps = {};
mouse.traps["Base.TrapMouse"] = 30;
mouse.baits = {};
mouse.baits["Base.Cheese"] = 60;
mouse.baits["Base.Processedcheese"] = 55;
mouse.baits["Base.PeanutButter"] = 40;
mouse.baits["Base.BaconBits"] = 40;
mouse.baits["Base.Chocolate"] = 30;
mouse.baits["Base.Orange"] = 35;
mouse.baits["Base.Apple"] = 35;
mouse.baits["Base.Tomato"] = 35;

local rat = {};
rat.type = "rat";
rat.item = "Base.DeadRat";
rat.minHour = 0;
rat.maxHour = 0;
rat.minSize = 5;
rat.maxSize = 25;
rat.canBeAlive = true;
rat.aliveAnimals = {};
table.insert(rat.aliveAnimals, "rat");
table.insert(rat.aliveAnimals, "ratfemale");
table.insert(rat.aliveAnimals, "ratbaby");
rat.aliveBreed = {};
table.insert(rat.aliveBreed, "grey");
table.insert(rat.aliveBreed, "white");
rat.zone = {};
rat.zone["Farm"] = 50;
rat.zone["FarmLand"] = 50;
rat.zone["TrailerPark"] = 40;
rat.zone["TownZone"] = 30;
rat.zone["Vegitation"] = 20;
rat.zone["Forest"] = 10;
rat.zone["DeepForest"] = 10;
rat.zone["BirchForest"] = 10;
rat.zone["BirchMixForest"] = 10;
rat.zone["OrganicForest"] = 10;
rat.zone["FarmForest"] = 10;
rat.zone["FarmMixForest"] = 10;
rat.zone["PRForest"] = 10;
rat.zone["PHForest"] = 10;
rat.zone["PHMixForest"] = 10;
rat.traps = {};
rat.traps["Base.TrapMouse"] = 25;
rat.baits = {};
rat.baits["Base.Cheese"] = 60;
rat.baits["Base.PeanutButter"] = 40;
rat.baits["Base.BaconBits"] = 40;
rat.baits["Base.Chocolate"] = 30;
rat.baits["Base.Orange"] = 35;
rat.baits["Base.Apple"] = 35;
rat.baits["Base.Tomato"] = 35;
rat.baits["Base.Processedcheese"] = 55;

local raccoon = {};
raccoon.type = "raccoon";
-- after how many hour the animal will start to destroy the cage/escape
raccoon.strength = 24;
-- item given to the player
raccoon.item = "Base.DeadRabbit"; -- TODO RJ: ask for model
-- hour this animal will be out and when you can catch it
raccoon.minHour = 19;
raccoon.maxHour = 5;
-- min and max "size" (understand hunger reduction) of the animal
raccoon.minSize = 30;
raccoon.maxSize = 100;
raccoon.canBeAlive = true;
raccoon.aliveAnimals = {};
table.insert(raccoon.aliveAnimals, "raccoonboar");
table.insert(raccoon.aliveAnimals, "raccoonsow");
table.insert(raccoon.aliveAnimals, "raccoonkit");
raccoon.aliveBreed = {};
table.insert(raccoon.aliveBreed, "grey");
-- chance to get the animals per zone
raccoon.zone = {};
raccoon.zone["TownZone"] = 2;
raccoon.zone["TrailerPark"] = 2;
raccoon.zone["Vegitation"] = 10;
raccoon.zone["Forest"] = 12;
raccoon.zone["DeepForest"] = 15;
raccoon.zone["BirchForest"] = 12;
raccoon.zone["BirchMixForest"] = 12;
raccoon.zone["FarmForest"] = 12;
raccoon.zone["FarmMixForest"] = 12;
raccoon.zone["PRForest"] = 12;
raccoon.zone["PHForest"] = 12;
raccoon.zone["PHMixForest"] = 12;
raccoon.zone["OrganicForest"] = 15;
-- chance to get animals for each trap
raccoon.traps = {};
raccoon.traps["Base.TrapCage"] = 40;
raccoon.traps["Base.TrapSnare"] = 30;
raccoon.traps["Base.TrapBox"] = 30;
raccoon.traps["Base.TrapCrate"] = 30;
-- chance to attract animal per bait
raccoon.baits = {};
raccoon.baits["Base.Carrots"] = 45;
raccoon.baits["Base.Apple"] = 35;
raccoon.baits["Base.Lettuce"] = 40;
raccoon.baits["Base.BellPepper"] = 40;
raccoon.baits["Base.Cabbage"] = 40;
raccoon.baits["Base.Corn"] = 35;
raccoon.baits["Base.Banana"] = 35;
raccoon.baits["Base.Potato"] = 35;
raccoon.baits["Base.Tomato"] = 35;
raccoon.baits["Base.Peach"] = 35;

table.insert(TrapAnimals, bird);
table.insert(TrapAnimals, rat);
table.insert(TrapAnimals, mouse);
table.insert(TrapAnimals, rabbit);
table.insert(TrapAnimals, squirrel);
table.insert(TrapAnimals, raccoon);