StoryClutter = {}

-- the stuff in Barns and Stables that imply the presence of farm animals; farm storage is for crop-based agriculture, used in the Barn Randomized Building
StoryClutter.BarnClutter = {
    "Base.Lantern_Hurricane",
    "Base.Rope",
    "Base.Scythe",
    "Base.ScytheForged",
    "Base.HandScythe",
    "Base.AnimalFeedBag",
    "Base.EmptySandbag",
    "Base.Bag_Gunny",
    "Base.Rake",
    "Base.RubberHose",
    "Base.Tongs",
    "Base.GardenFork",
    "Base.Shovel",
    "Base.Shovel2",
    "Base.GardenHoe",
    "Base.PickAxe",
    "Base.JerryCan",
    "Base.Bucket",
    "Base.Twine",
    "Base.Hat_StrawHat",
    "Base.Dungarees",
    "Base.Shoes_Wellies",
    "Base.Gloves_LeatherGloves",
    "Base.Boilersuit_BlueRed",
    "Base.SheepShears",
    "Base.SheepElectricShears",
    "Base.NormalTire2",
    "Base.CarBattery2",
    "Base.Torch",
    "Base.LargeKnife",
    "Base.Pliers",
    "Base.ScytheBlade",
    "Base.BookHusbandry4",
    "Base.BookHusbandry5",
    "Base.TrophyGold", -- prize hogs!
    "Base.TrophySilver",
    "Base.Garbagebag_box",
    "Base.JawboneBovide", -- poor bessie! :(
    "Base.Toolbox_Wooden",
    "Base.Fleshing_Tool",
}

-- residential bathrooms, used for Randomized Residential Buildings
StoryClutter.BathroomSinkClutter = {
    "Base.Comb",
    "Base.Cologne",
    "Base.Antibiotics",
    "Base.Bandage",
    "Base.Pills",
    "Base.PillsAntiDep",
    "Base.PillsBeta",
    "Base.PillsSleepingTablets",
    "Base.PillsVitamins",
    "Base.Lipstick",
    "Base.MakeupEyeshadow",
    "Base.MakeupFoundation",
    "Base.Perfume",
    "Base.Razor",
    "Base.Toothbrush",
    "Base.Toothpaste",
    "Base.Tweezers",
    "Base.HairDryer",
    "Base.HairIron",
    "Base.Scissors",
    "Base.StraightRazor",
    "Base.TissueBox",
    "Base.HottieZ",
    "Base.Hairspray2",
    "Base.Hairgel",
    "Base.Paperback_SelfHelp",
    "Base.Ring_Left_RingFinger_Gold",
    "Base.Ring_Left_RingFinger_GoldDiamond",
    "Base.Ring_Left_RingFinger_Silver",
    "Base.Rubberducky",
}

-- items scattered on the ground for the bbq story on the beaches, not stuff inside BBQs; that is normal loot
StoryClutter.BBQClutter = {
    "Base.Bag_PicnicBasket",
    "Base.BeerBottle",
    "Base.BeerBottle",
    "Base.BeerCan",
    "Base.BeerCan",
    "Base.BeerCan",
    "Base.BeerCan",
    "Base.BeerCan",
    "Base.BeerCan",
	"Base.Crisps",
    "Base.Crisps3",
    "Base.MuttonChop",
    "Base.Pop",
    "Base.PorkChop",
    "Base.Steak",
}

-- the clothing that spawns on the foot of the bed in residential bedrooms, used for Randomized Residential Buildings
StoryClutter.BedClutter = {
    "Base.Shirt_FormalTINT",
    "Base.Shirt_FormalWhite_ShortSleeveTINT",
    "Base.Tshirt_DefaultDECAL_TINT",
    "Base.Tshirt_PoloStripedTINT",
    "Base.Tshirt_PoloTINT",
    "Base.Jacket_WhiteTINT",
    "Base.Jumper_DiamondPatternTINT",
    "Base.Jumper_TankTopDiamondTINT",
    "Base.HoodieDOWN_WhiteTINT",
    "Base.Trousers_DefaultTEXTURE_TINT",
    "Base.Trousers_WhiteTINT",
    "Base.Trousers_Denim",
    "Base.Trousers_Padded",
    "Base.TrousersMesh_DenimLight",
    "Base.Belt2",
    "Base.Boxers_Hearts",
    "Base.Socks_Ankle",
    "Base.Socks_Long",
    "Base.Socks_Ankle_White",
    "Base.Socks_Long_White",
    "Base.Underpants_White",
    "Base.Boxers_White",
    "Base.Briefs_White",
    "Base.Sheet",
}

StoryClutter.CafeClutter = {
	"Base.CookieChocolateChip",
	"Base.CookiesChocolate",
	"Base.CookieJelly",
	"Base.CookiesShortbread",
	"Base.CookiesSugar",
	"Base.Cupcake",
	"Base.Kettle",
	"Base.MuffinFruit",
	"Base.MugWhite",
	"Base.MugWhite",
	"Base.SugarPacket",
	"Base.Teabag2",
}

-- the tools that can spawn on the road for carpentry vehicles
StoryClutter.CarpentryToolClutter = {
    "Base.Hammer",
    "Base.NailsBox",
    "Base.Plank",
    "Base.Plank",
    "Base.Plank",
    "Base.Saw",
    "Base.Saw",
    "Base.Screwdriver",
    "Base.Woodglue",
}

-- tragic end ground clutter for the dead end road story; first aid kits may also be randomly spawned by the story
StoryClutter.DeadEndClutter = {
    "Base.Bag_Satchel_Leather",
    "Base.Bag_Schoolbag_Kids",
    "Base.BandageDirty",
    "Base.BandageDirty",
    "Base.Book_Bible",
    "Base.Briefcase",
    "Base.Doll",
    "Base.DoodleKids",
    "Base.Handbag",
    "Base.LetterHandwritten",
    "Base.Locket",
    "Base.Necklace_SilverCrucifix",
    "Base.Photo",
    "Base.Purse",
    "Base.Suitcase",
    "Base.ToyBear",
    "Base.ToyCar",
    "Base.Wallet",
    "Base.Passport",
    "Base.DogTag_Pet",
    "Base.ChildsPictureBook",
}

-- university dorm squalor, used in the Dorm Randomized Building
StoryClutter.DormClutter = {
    "Base.PlasticCup",
    "Base.GuitarAcoustic",
    "Base.Book_Classic",
    "Base.Book_GeneralReference",
    "Base.Book_History",
    "Base.Book_LiteraryFiction",
    "Base.Book_Medical",
    "Base.Book_Philosophy",
    "Base.Book_Science",
    "Base.Paperback_Travel",
    "Base.Paperback_Fiction",
    "Base.Paperback_Classic",
    "Base.Paperback",
    "Base.Book",
    "Base.Bag_Satchel",
    "Base.Bag_Schoolbag",
    "Base.Bag_Schoolbag_Patches",
    "Base.Bag_Schoolbag_Travel",
    "Base.Football",
    "Base.Basketball",
    "Base.Baseball",
    "Base.SoccerBall",
    "Base.TennisBall",
    "Base.Socks_Ankle",
    "Base.TennisRacket",
    "Base.CigaretteRollingPapers",
    "Base.LighterDisposable",
    "Base.TobaccoLoose",
    "Base.ComicBook",
    "Base.Magazine_Humor",
    "Base.Magazine_Popular_New",
    "Base.Journal",
    "Base.Notebook",
    "Base.Note",
    "Base.Diary2",
    "Base.Yoyo",
    "Base.Cube",
    "Base.Comb",
    "Base.Hairspray2",
    "Base.PopEmpty",
    "Base.Eraser",
    "Base.Pen",
    "Base.Pencil",
    "Base.BluePen",
    "Base.GreenPen",
    "Base.RedPen",
    "Base.Briefs_White",
    "Base.RPGmanual",
    "Base.FieldHockeyStick",
    "Base.Jacket_Varsity",
    "Base.Tshirt_Rock",
    "Base.Calculator",
    "Base.HottieZ",
    "Base.Magazine_Popular_New",
    "Base.Hairgel",
    "Base.Razor",
    "Base.Soap2",
    "Base.BathTowel",
    "Base.LongCoat_Bathrobe",
    "Base.Glasses_Normal",
    "Base.Glasses_Reading",
    "Base.HollowBook_Whiskey",
    "Base.Sportsbottle",
    "Base.CanteenCowboy",
    "Base.CardDeck",
    "Base.Tweezers",
    "Base.PillsVitamins",
    "Base.TrophyGold",
    "Base.TrophySilver",
    "Base.Medal_Gold",
    "Base.Pizza",
    "Base.Garbagebag_box",
    "Base.HempBagSeed",
    "Base.AthleticCup",
    "Base.Rubberducky",
    "Base.HempMag1",
    "Base.GuitarPick",
    "Base.Crystal",
    "Base.TarotCardDeck",
    "Base.HairIron",
    "Base.CorrectionFluid",
    "Base.Specimen_Butterflies",
    "Base.KeyRing_StinkyFace",
}

-- farming stuff that isn't farm animal based for farm storage rooms, used in the Barn Randomized Buildings
StoryClutter.FarmStorageClutter = {
    "Base.Lantern_Hurricane",
    "Base.Rope",
    "Base.Scythe",
    "Base.ScytheForged",
    "Base.HandScythe",
    "Base.EmptySandbag",
    "Base.Bag_Gunny",
    "Base.Rake",
    "Base.RubberHose",
    "Base.Tongs",
    "Base.GardenFork",
    "Base.Shovel",
    "Base.Shovel2",
    "Base.GardenHoe",
    "Base.PickAxe",
    "Base.JerryCan",
    "Base.WateredCan",
    "Base.KnapsackSprayer",
    "Base.GardeningSprayEmpty",
    "Base.Fertilizer",
    "Base.CompostBag",
    "Base.Bucket",
    "Base.HandFork",
    "Base.HandShovel",
    "Base.Twine",
    "Base.Hat_StrawHat",
    "Base.Dungarees",
    "Base.Shoes_Wellies",
    "Base.Gloves_LeatherGloves",
    "Base.Boilersuit_BlueRed",
    "Base.RatPoison",
    "Base.NormalTire2",
    "Base.CarBattery2",
    "Base.Torch",
    "Base.Hat_BuildersRespirator",
    "Base.LargeKnife",
    "Base.ViseGrips",
    "Base.Pliers",
    "Base.Wrench",
    "Base.TireIron",
    "Base.LugWrench",
    "Base.TirePump",
    "Base.ScrapMetal",
    "Base.EngineParts",
    "Base.File",
    "Base.MetalworkingChisel",
    "Base.MetalworkingPunch",
    "Base.SmallFileSet",
    "Base.SmallPunchSet",
    "Base.CrudeBenchVise",
    "Base.BenchAnvil",
    "Base.SteelBar",
    "Base.SteelBarHalf",
    "Base.SteelBarQuarter",
    "Base.SteelBlock",
    "Base.SteelChunk",
    "Base.NutsBolts",
    "Base.RailroadSpike",
    "Base.RailroadTrackPiece",
    "Base.Screwdriver",
    "Base.MeasuringTape",
    "Base.BallPeenHammer",
    "Base.Handle",
    "Base.LongHandle",
    "Base.BlacksmithAnvil",
    "Base.Whetstone",
    "Base.Saw",
    "Base.SmallSaw",
    "Base.GardenSaw",
    "Base.PipeWrench",
    "Base.FarmingMag6",
    "Base.CircularSawblade",
    "Base.HeavyChain",
    "Base.HeavyChain_Hook",
    "Base.LargeHook",
    "Base.BookFarming4",
    "Base.BookFarming5",
    "Base.Shotgun",
    "Base.Jack",
    "Base.Extinguisher",
    "Base.BlowerFan",
    "Base.BeerPack",
    "Base.BeerCanPack",
    "Base.MysteryCan",
    "Base.DentedCan",
    "Base.MysteryCan_Box",
    "Base.DentedCan_Box",
    "Base.BoxOfJars",
    "Base.CannedBellPepper",
    "Base.CannedBroccoli",
    "Base.CannedCabbage",
    "Base.CannedCarrots",
    "Base.CannedEggplant",
    "Base.CannedLeek",
    "Base.CannedPotato",
    "Base.CannedRedRadish",
    "Base.CannedTomato",
    "Base.Cooler_Beer",
    "Base.SmokingPipe",
    "Base.CigarettePack",
    "Base.Garbagebag_box",
    "Base.HempBagSeed", -- someone was growing the ole kentucky bluegrass
    "Base.Toolbox_Wooden",
    "Base.ElectricWire",
    "Base.Bag_GardenBasket",
    "Base.WaterDispenserBottle",
    "Base.ShotgunShells", -- ain't no big deal in farm country
    "Base.Calipers", -- fixing farm equipment
}

-- used for the football night story clutter
-- the names of the tables aren't so important, this is drinks, booze, smokes, sins, whatever
StoryClutter.FootballNightDrinks = {
    "Base.BeerPack",
    "Base.BeerCanPack",
    "Base.BeerBottle",
    "Base.BeerCan",
    "Base.Cigar",
    "Base.CigaretteSingle",
    "Base.Wine",
    "Base.Wine2",
}

-- yes pop are also drinks, but the name of the table isn't that important
StoryClutter.FootballNightSnacks = {
    "Base.Crisps",
    "Base.Crisps2",
    "Base.Crisps3",
    "Base.Pizza",
    "Base.Pop",
    "Base.Pop2",
    "Base.Pop3",
}

-- residential garage clutter, used in the Barn Randomized Buildings
StoryClutter.GarageStorageClutter = {
    "Base.Lantern_Propane",
    "Base.Rope",
    "Base.Rake",
    "Base.RubberHose",
    "Base.Shovel",
    "Base.Shovel2",
    "Base.PetrolCan",
    "Base.WateredCan",
    "Base.GardeningSprayEmpty",
    "Base.Fertilizer",
    "Base.CompostBag",
    "Base.Bucket",
    "Base.HandFork",
    "Base.HandShovel",
    "Base.Twine",
    "Base.Hat_StrawHat",
    "Base.Shoes_Wellies",
    "Base.Gloves_LeatherGloves",
    "Base.RatPoison",
    "Base.NormalTire1",
    "Base.CarBattery1",
    "Base.Torch",
    "Base.Hat_BuildersRespirator",
    "Base.ViseGrips",
    "Base.Pliers",
    "Base.Wrench",
    "Base.TireIron",
    "Base.LugWrench",
    "Base.TirePump",
    "Base.ScrapMetal",
    "Base.EngineParts",
    "Base.File",
    "Base.MetalworkingChisel",
    "Base.MetalworkingPunch",
    "Base.SmallFileSet",
    "Base.SmallPunchSet",
    "Base.NutsBolts",
    "Base.Screwdriver",
    "Base.MeasuringTape",
    "Base.BallPeenHammer",
    "Base.Whetstone",
    "Base.Saw",
    "Base.SmallSaw",
    "Base.GardenSaw",
    "Base.PipeWrench",
    "Base.CircularSawblade",
    "Base.Toolbox",
    "Base.Toolbox_Wooden",
    "Base.Tacklebox",
    "Base.Jack",
    "Base.CigarettePack",
    "Base.Extinguisher",
    "Base.Cooler_Beer",
    "Base.PowerBar",
    "Base.Shoes_WorkBoots",
    "Base.BeerPack",
    "Base.MysteryCan",
    "Base.DentedCan",
    "Base.MysteryCan_Box",
    "Base.DentedCan_Box",
    "Base.BoxOfJars",
    "Base.CannedBellPepper",
    "Base.CannedBroccoli",
    "Base.CannedCabbage",
    "Base.CannedCarrots",
    "Base.CannedEggplant",
    "Base.CannedLeek",
    "Base.CannedPotato",
    "Base.CannedRedRadish",
    "Base.CannedTomato",
    "Base.TinnedSoup_Box",
    "Base.CannedFruitCocktail_Box",
    "Base.CannedFruitBeverage_Box",
    "Base.CannedPeaches_Box",
    "Base.CannedPineapple_Box",
    "Base.CannedCornedBeef_Box",
    "Base.CannedCorn_Box",
    "Base.CannedBolognese_Box",
    "Base.CannedChili_Box",
    "Base.CannedMushroomSoup_Box",
    "Base.CannedPeas_Box",
    "Base.CannedPotato_Box",
    "Base.CannedSardines_Box",
    "Base.CannedTomato_Box",
    "Base.CannedCarrots_Box",
    "Base.TinnedBeans_Box",
    "Base.Dogfood_Box",
    "Base.CannedMilk_Box",
    "Base.Macandcheese_Box",
    "Base.WineBox",
    "Base.TrophyGold", -- past glories
    "Base.TrophySilver",
    "Base.BBQStarterFluid",
    "Base.GrillBrush",
    "Base.Garbagebag_box",
    "Base.BookMechanic4",
    "Base.BookMechanic5",
    "Base.ElectricWire",
    "Base.Hat_SummerFlowerHat",
    "Base.Bag_GardenBasket",
    "Base.WaterDispenserBottle",
    "Base.Calipers",
}

StoryClutter.GigamartClutter = {
	"Base.CreditCard",
	"Base.Money",
	"Base.Plasticbag",
	"Base.Plasticbag",
	"Base.Plasticbag",
	"Base.Plasticbag",
}

StoryClutter.GroceryClutter = {
	"Base.Apple",
	"Base.Avocado",
	"Base.Banana",
	"Base.BellPepper",
	"Base.Broccoli",
	"Base.Carrots",
	"Base.Cherry",
	"Base.Corn",
	"Base.Eggplant",
	"Base.Grapefruit",
	"Base.Grapes",
	"Base.Leek",
	"Base.Lemon",
	"Base.Lime",
	"Base.Lettuce",
	"Base.Mango",
	"Base.Money",
	"Base.Onion",
	"Base.Orange",
	"Base.Peach",
	"Base.Pear",
	"Base.Peas",
	"Base.PepperHabanero",
	"Base.PepperJalapeno",
	"Base.Pineapple",
	"Base.Plasticbag",
	"Base.Plasticbag",
	"Base.Plasticbag",
	"Base.Plasticbag",
	"Base.Plasticbag",
	"Base.Pumpkin",
	"Base.Tomato",
	"Base.Watermelon",
	"Base.Zucchini",
}

-- stuff spawning as hair salon clutter in Randomized Buildings
StoryClutter.HairSalonClutter = {
    "Base.Comb",
    "Base.HairDryer",
    "Base.HairDyeCommon",
    "Base.HairDyeUncommon",
    "Base.HairDyeRare",
    "Base.Hairgel",
    "Base.Hairspray2",
    "Base.Magazine_Popular",
    "Base.Razor",
    "Base.Scissors",
    "Base.StraightRazor",
    "Base.TissueBox",
}

-- stuff on the rare tabletops in the rare halls in larger houses used for Randomized Residential Buildings
StoryClutter.HallClutter = {
    "Base.Bag_Satchel",
    "Base.Brochure",
    "Base.BusinessCard",
    "Base.CatToy",
    "Base.CatTreats",
    "Base.CigarettePack",
    "Base.CordlessPhone",
    "Base.DogChew",
    "Base.Flask",
    "Base.Flier",
    "Base.GenericMail",
    "Base.Glasses_Normal",
    "Base.Gloves_WhiteTINT",
    "Base.Handbag",
    "Base.Hat_Cowboy",
    "Base.Hat_Fedora",
    "Base.Hat_GolfHat",
    "Base.Hat_SummerFlowerHat",
    "Base.KeyRing",
    "Base.LetterHandwritten",
    "Base.Lighter",
    "Base.LighterDisposable",
    "Base.Magazine_Popular",
    "Base.Newspaper_Recent",
    "Base.Note",
    "Base.Purse",
    "Base.Revolver_Short", -- it's the south in 1993, it's normal to have a "hallway gun" just in case
    "Base.Ring_Left_RingFinger_Gold",
    "Base.Ring_Left_RingFinger_GoldDiamond",
    "Base.Ring_Left_RingFinger_Silver",
    "Base.ScoutCookies",
    "Base.Sportsbottle",
    "Base.SmokingPipe",
    "Base.ToyCar",
    "Base.Wallet",
}

-- used for the hen do story clutter
-- the names of the tables aren't so important, this is drinks, booze, smokes, sins, whatever
StoryClutter.HenDoDrinks = {
    "Base.CigaretteSingle",
    "Base.Wine",
    "Base.Wine2",
    "Base.WineBox",
}
-- yes pop are also drinks, but the name of the table isn't that important
StoryClutter.HenDoSnacks = {
    "Base.Crisps",
    "Base.Crisps2",
    "Base.Crisps3",
    "Base.Cupcake",
    "Base.Pop",
    "Base.Pop2",
    "Base.Pop3",
}

-- used for the hillbilly hoedown story ground clutter
StoryClutter.HoedownClutter = {
    "Base.Banjo",
    "Base.Banjo",
    "Base.BeerBottle",
    "Base.BeerCan",
    "Base.BeerPack",
    "Base.BeerCanPack",
    "Base.DoubleBarrelShotgun",
    "Base.Flask",
    "Base.GuitarAcoustic",
    "Base.GuitarAcoustic",
    "Base.Hat_Cowboy",
    "Base.Hat_StrawHat",
	"Base.MetalCup",
    "Base.PillsVitamins",
    "Base.Violin",
}

-- used for the house party story clutter
StoryClutter.HousePartyClutter = {
    "Base.Pop",
    "Base.Pop2",
    "Base.Pop3",
    "Base.Cupcake",
    "Base.Cupcake",
    "Base.CakeSlice",
    "Base.CakeSlice",
    "Base.CakeSlice",
    "Base.CakeSlice",
    "Base.CakeSlice",
    "Base.Present_ExtraSmall",
    "Base.Present_Small",
    "Base.Present_Medium",
    "Base.Card_Birthday",
}

-- stuff for the Judge Matt Hass studio in the Triple-N building. Some items are repeated to increase spawn weights.
StoryClutter.JudgeClutter = {
	"Base.Magazine_Golf",
	"Base.Magazine_Firearm",
	"Base.Paperback_Hass",
	"Base.Paperback_Hass",
	"Base.Photo_Hass",
	"Base.Photo_Hass",
	"Base.Photo_Hass",
	"Base.Photo_Hass",
}

-- stuff that can spawn in kids rooms, including instead of pillows, used for Randomized Residential Buildings
-- it's intentional that these can show up in beds, kids are animals
StoryClutter.KidClutter = {
    -- note that the spiffo and magical woodland bunch are supposed to be ultra rare collectibles; however this item pool has a lot of items in it, and we can always add more if these varmints spawn too much
    "Base.Spiffo",
    "Base.BorisBadger",
    "Base.FluffyfootBunny",
    "Base.FreddyFox",
    "Base.FurbertSquirrel",
    "Base.JacquesBeaver",
    "Base.MoleyMole",
    "Base.PancakeHedgehog",
    "Base.Pancho",
    "Base.Plushabug",
    "Base.Pillow_Happyface",
    "Base.Pillow_Star",
    "Base.ToyBear",
    "Base.Doll",
    "Base.Diary1",
    "Base.ComicBook",
    "Base.RPGmanual",
    "Base.VideoGame",
    "Base.Book_Childs",
    "Base.Magazine_Childs",
    "Base.Paperback_Childs",
	"Base.ChildsPictureBook",
    "Base.Bag_Schoolbag_Kids",
    "Base.Yoyo",
    "Base.ToyCar",
    "Base.Cube",
    "Base.Bricktoys",
    "Base.Firecracker", -- hell yeah! this kid is AWESOME
    "Base.RubberSpider", -- again, AWESOME
    "Base.Photo",
    "Base.Paperback_Bible",
    "Base.Crayons",
    "Base.CatToy",
    "Base.DogChew",
    "Base.Lunchbox",
    "Base.Football",
    "Base.Basketball",
    "Base.Baseball",
    "Base.SoccerBall",
    "Base.TrophyBronze", -- it's intentional that these can show up in beds; this little snot is really in love with themselves it appears
    "Base.TrophyGold",
    "Base.TrophySilver",
    "Base.Medal_Gold",
    "Base.Medal_Silver",
    "Base.Medal_Bronze",
    "Base.Hat_FurryEars",
    "Base.Magazine_Humor", -- Mad magazine etc. another awesome kid
    "Base.Hat_NewspaperHat",
    "Base.Sportsbottle",
    "Base.Pizza", -- again, kids can be filthy little beasts
    "Base.PenSpiffo",
    "Base.PencilSpiffo",
    "Base.Book_SchoolTextbook",
    "Base.Book_GeneralReference",
    "Base.HollowBook_Kids",
    "Base.ScoutCookies",
    "Base.Necklace_Crucifix",
    "Base.PenSpiffo",
    "Base.PencilSpiffo",
    "Base.CatTreats", -- my cat's breath smells like cat food
    "Base.Card_Birthday", -- well, turns out it wasn't that great
    "Base.KeyRing_RabbitFoot", -- turned out to not be that lucky after all I guess
    "Base.Socks_Ankle",
    "Base.Socks_Ankle_White",
    "Base.Whistle",
    "Base.KnifePocket", -- normal thing for a kid in 1993 kentucky to have
    "Base.Handiknife", -- ditto
    "Base.Hat_ArmyWWII", -- kids like using hats as toys and some kids have cooler toys than others; again, kentucky, 1993, not unusual for kids to have surplus stuff as toys
    "Base.Hat_Cowboy",
    "Base.Hat_Pirate",
    "Base.Hat_FishermanRainHat",
    "Base.MagazineWordsearch",
    "Base.Clitter",
    "Base.GuitarPick",
}

-- residential kitchens, used for Randomized Residential Buildings
StoryClutter.KitchenCounterClutter = {
    "Base.Dogfood",
    "Base.CannedCorn",
    "Base.CannedPeas",
    "Base.CannedPotato2",
    "Base.CannedSardines",
    "Base.CannedTomato2",
    "Base.CannedCarrots2",
    "Base.CannedChili",
    "Base.CannedBolognese",
    "Base.TinOpener",
    "Base.TinOpener_Old",
    "Base.WaterBottle",
    "Base.Cereal",
    "Base.CerealBowl",
    "Base.Spoon",
    "Base.Fork",
    "Base.KitchenKnife",
    "Base.ButterKnife",
    "Base.BreadKnife",
    "Base.KnifeParing",
    "Base.DishCloth",
    "Base.RollingPin",
    "Base.EmptyJar",
    "Base.Bowl",
    "Base.Mugl",
    "Base.Pot",
    "Base.Saucepan",
    "Base.SaucepanCopper",
    "Base.Kettle",
    "Base.Kettle_Copper",
    "Base.PotOfSoup",
    "Base.StewBowl",
    "Base.SoupBowl",
    "Base.WaterSaucepanPasta",
    "Base.WaterSaucepanRice",
    "Base.GlassTumbler",
    "Base.RecipeClipping",
    "Base.Note",
    "Base.Plate",
    "Base.CheeseGrater",
    "Base.Ladle",
    "Base.Strainer",
    "Base.Whisk",
    "Base.Salt",
    "Base.Pepper",
    "Base.Bread",
    "Base.CordlessPhone",
    "Base.ScoutCookies",
    "Base.Phonebook",
    "Base.Brochure",
    "Base.Flier",
    "Base.GenericMail",
    "Base.LetterHandwritten",
    "Base.Money",
    "Base.Matches",
    "Base.MenuCard",
    "Base.Purse",
    "Base.Handbag",
    "Base.Receipt",
    "Base.ScratchTicket",
    "Base.CatToy",
    "Base.Yoyo",
    "Base.Cube",
    "Base.Catalog",
    "Base.RatPoison",
    "Base.PeanutButter",
    "Base.Bag_Satchel",
    "Base.Spatula",
    "Base.Teacup",
    "Base.Chopsticks",
    "Base.MuffinTray",
    "Base.Corkscrew",
    "Base.CuttingBoardPlastic",
    "Base.CuttingBoardWooden",
    "Base.MortarPestle",
    "Base.OvenMitt",
    "Base.Timer",
    "Base.CatTreats",
    "Base.Parcel_ExtraSmall",
    "Base.Parcel_Medium",
    "Base.Parcel_Small",
    "Base.Card_Birthday", -- womp womp!
    "Base.Card_Sympathy", -- indeed...
    "Base.WineBox",
    "Base.Ring_Left_RingFinger_Gold",
    "Base.Ring_Left_RingFinger_GoldDiamond",
    "Base.Ring_Left_RingFinger_Silver",
    "Base.CigaretteRollingPapers",
    "Base.BeerPack",
    "Base.BeerCanPack",
    "Base.CannedBellPepper",
    "Base.CannedBroccoli",
    "Base.CannedCabbage",
    "Base.CannedCarrots",
    "Base.CannedEggplant",
    "Base.CannedLeek",
    "Base.CannedPotato",
    "Base.CannedRedRadish",
    "Base.CannedTomato",
    "Base.Chamomile",
    "Base.Marigold",
    "Base.Garbagebag_box",
    "Base.Wallet",
    "Base.Sugar",
    "Base.Vinegar_Jug",
    "Base.MilkBottle",
    "Base.Glasses_Normal",
    "Base.BakingSoda",
    "Base.Roses",
    "Base.Poppies",
    "Base.Lavender",
    "Base.SunflowerHead",
    "Base.ParkingTicket",
    "Base.SpeedingTicket",
    "Base.Postcard",
}

-- residential kitchen sinks, used for Randomized Residential Buildings
StoryClutter.KitchenSinkClutter = {
    "Base.CleaningLiquid2",
    "Base.DishCloth",
    "Base.Gloves_Dish",
    "Base.Soap2",
    "Base.Sponge",
    "Base.SteelWool",
}

-- the food stuff on top of residential stoves, used for Randomized Residential Buildings
StoryClutter.KitchenStoveClutter = {
    "Base.DishCloth",
    "Base.Kettle",
    "Base.Kettle_Copper",
    "Base.OvenMitt",
    "Base.PastaPot",
    "Base.Pot",
    "Base.PotOfSoup",
    "Base.PotOfStew",
    "Base.RicePot",
    "Base.Saucepan",
    "Base.SaucepanCopper",
    "Base.Sponge",
    "Base.WaterSaucepanPasta",
    "Base.WaterSaucepanRice",
}

-- laundry room stuff for Randomized Residential Buildings
StoryClutter.LaundryRoomClutter = {
    "Base.Bag_Laundry",
    "Base.BakingSoda", -- can be used for laundry or cleaning in general
    "Base.BathTowel",
    "Base.Bleach",
    "Base.Boxers_White",
    "Base.Briefs_White",
    "Base.Bucket",
    "Base.CleaningLiquid2",
    "Base.DryerLint",
    "Base.Garbagebag_box",
    "Base.RippedSheets",
    "Base.RippedSheetsDirty",
    "Base.Socks_Ankle",
    "Base.Socks_Long",
    "Base.Socks_Ankle_White",
    "Base.Socks_Long_White",
    "Base.Sponge",
    "Base.Underpants_White",
    "Base.WineBox", -- "doing the laundry"
    "Base.Vinegar_Jug", -- can be used for laundry or cleaning in general
}

-- residential livingrooms, used for Randomized Residential Buildings
StoryClutter.LivingroomClutter = {
    "Base.TVMagazine",
    "Base.Newspaper_Recent",
    "Base.VideoGame",
    "Base.Headphones",
	"Base.PhotoBook",
    "Base.Magazine_Popular",
    "Base.Photo",
    "Base.CordlessPhone",
    "Base.GenericMail",
    "Base.CatToy",
    "Base.DogChew",
    "Base.Phonebook",
    "Base.Brochure",
    "Base.Flier",
    "Base.LetterHandwritten",
    "Base.Paperback",
    "Base.Catalog",
    "Base.ComicBook",
    "Base.Yoyo",
    "Base.Cube",
    "Base.Teacup",
    "Base.CatTreats",
    "Base.CigaretteRollingPapers",
    "Base.SmokingPipe",
    "Base.Wallet",
    "Base.Glasses_Normal",
    "Base.Glasses_Reading",
    "Base.SnowGlobe",
    "Base.Doily",
    "Base.PhotoAlbum",
}

-- used for Clinics, Hospital Rooms, Medical Randomized Buildings
StoryClutter.MedicalClutter = {
    "Base.Scalpel",
    "Base.Bandage",
    "Base.Pills",
    "Base.AlcoholWipes",
    "Base.Bandaid",
    "Base.CottonBalls",
    "Base.Disinfectant",
    "Base.SutureNeedle",
    "Base.SutureNeedleHolder",
    "Base.Tweezers",
    "Base.Gloves_Surgical",
    "Base.Hat_SurgicalMask",
    "Base.ScissorsBluntMedical",
    "Base.TongueDepressor",
    "Base.BandageDirty",
    "Base.Gloves_Surgical",
    "Base.RubberHose",
}

-- stuff on the ground for old campsites, shelters and tents in the forest
StoryClutter.OldShelterClutter = {
    "Base.GuitarAcoustic",
    "Base.Harmonica",
	"Base.MetalCup",
    "Base.Diary2",
    "Base.Paperback_Bible",
    "Base.Photo",
    "Base.Locket",
    "Base.KnifePocket",
    "Base.LetterHandwritten",
    "Base.HandAxe",
    "Base.Bag_NormalHikingBag",
    "Base.Book",
    "Base.Paperback",
    "Base.Spork",
}

-- to be used in Nolan's offices
-- some entries repeated to weigh results
StoryClutter.OfficeCarDealerClutter = {
	"BusinessCard_Nolans",
	"BusinessCard_Nolans",
	"BusinessCard_Nolans",
	"Flier_Nolans",
	"Flier_Nolans",
	"Flier_Nolans",
	"Flier_Nolans",
	"Flier_Nolans",
	"KeyRing_Nolans",
}

-- what is being worked on, used for Office Randomized Buildings
-- some entries repeated to weigh results
StoryClutter.OfficePaperworkClutter = {
    "Base.Doodle", -- get back to work!!!
    "Base.Book_Business",
    "Base.Notebook",
    "Base.SheetPaper2",
    "Base.Diary2",
    "Base.LetterHandwritten",
    "Base.Note",
    "Base.Notepad",
    "Base.Paperwork",
    "Base.Notebook",
    "Base.SheetPaper2",
    "Base.Notepad",
    "Base.Paperwork",
    "Base.Phonebook",
    "Base.Magazine",
    "Base.GenericMail",
    "Base.Newspaper_New",
    "Base.MenuCard",
    "Base.Receipt",
    "Base.BrassNameplate",
    "Base.CorrectionFluid",
}

-- grown up, serious, professional writing tools, no multicolors or spiffos (which are supposed to be rare anyways!), used for Office Randomized Buildings
-- some entries repeated to weigh results
StoryClutter.OfficePenClutter = {
    "Base.Pen",
    "Base.Pencil",
    "Base.RedPen",
    "Base.BluePen",
    "Base.Eraser",
    "Base.GreenPen",
    "Base.MarkerBlack",
    "Base.MarkerBlue",
    "Base.MarkerGreen",
    "Base.MarkerRed",
    "Base.Pen",
    "Base.Pencil",
    "Base.RedPen",
    "Base.BluePen",
    "Base.Eraser",
}

-- other work related stuff, used for Office Randomized Buildings
StoryClutter.OfficeOtherClutter = {
    "Base.MugWhite",
    "Base.PaperclipBox",
    "Base.RubberBand",
    "Base.Calculator",
    "Base.Clipboard",
    "Base.Paperclip",
    "Base.Scotchtape",
    "Base.Stapler",
    "Base.Staples",
    "Base.Newspaper_New",
    "Base.Magazine_Popular",
    "Base.MarkerRed",
    "Base.CordlessPhone",
    "Base.Newspaper_Recent",
    "Base.Magazine_Rich",
    "Base.BusinessCard",
    "Base.Teacup",
    "Base.Glasses_Normal",
    "Base.Glasses_Reading",
    "Base.Pager",
}

-- snacks, distractions and others, used for Office Randomized Buildings
StoryClutter.OfficeTreatClutter = {
    "Base.Apple",
    "Base.BagelPlain",
    "Base.Burrito",
    "Base.Chocolate",
    "Base.Cigar",
    "Base.CigarettePack",
    "Base.CigaretteSingle",
    "Base.CardDeck",
    "Base.Cologne",
    "Base.Comb",
    "Base.Cube",
    "Base.DoughnutPlain",
    "Base.HottieZ", -- what a scumbag!
    "Base.Lighter",
    "Base.Lipstick",
    "Base.Lunchbag",
    "Base.MakeupEyeshadow",
    "Base.MakeupFoundation",
    "Base.Paperbag_Jays",
    "Base.Paperbag_Spiffos",
    "Base.Orange",
    "Base.Pop",
    "Base.Pop2",
    "Base.Pop3",
    "Base.Paperback",
    "Base.Paperback_SelfHelp",
    "Base.TVMagazine",
    "Base.WaterBottle",
    "Base.MagazineCrossword",
    "Base.MagazineWordsearch",
    "Base.Yoghurt",
    "Base.LetterOpener",
    "Base.ComicBook_Retail",
    "Base.Gum",
    "Base.Flask", -- it's Friday somewhere
    "Base.Photo_Secret",
    "Base.Pizza",
    "Base.ScratchTicket",
    "Base.Flier",
    "Base.Brochure",
    "Base.Catalog",
}

-- the food that spawns in the ovens of residential kitchens, used for Randomized Residential Buildings
-- the pans that spawn in ovens are loot and are spawned as such
StoryClutter.OvenFoodClutter = {
    "Base.Chicken",
    "Base.FishFillet",
    "Base.MeatPatty",
    "Base.MuttonChop",
    "Base.Pizza", -- a whole pizza is too generous, so just a slice being reheated
    "Base.PorkChop",
    "Base.Salmon",
    "Base.Steak",
    "Base.TVDinner",
}

-- sometimes this will spawn instead of a pillow on the head of the bed in residential bedrooms, used for Randomized Residential Buildings
StoryClutter.PillowClutter = {
    -- note that the spiffo and magical woodland bunch are supposed to be ultra rare collectibles; however this item pool is a quite rare spawn, and we can also add more items to it if too many of these critters are scurrying around
    "Base.Spiffo",
    "Base.BorisBadger",
    "Base.FluffyfootBunny",
    "Base.FreddyFox",
    "Base.FurbertSquirrel",
    "Base.JacquesBeaver",
    "Base.MoleyMole",
    "Base.PancakeHedgehog",
    "Base.Pancho",
    "Base.Plushabug",
    "Base.Pillow_Happyface",
    "Base.Pillow_Heart",
    "Base.Pillow_Star",
    "Base.Doll",
    "Base.ToyBear",
    "Base.Diary2",
    "Base.Dress_SatinNegligee",
    "Base.LetterHandwritten",
    "Base.Paperback_Bible",
    "Base.Paperback_Sexy",
    "Base.PokerChips",
    "Base.PokerChips",
    "Base.Photo_Secret",
    "Base.Revolver_Short", -- kentucky, 1993, just being a responsible homeowner
    "Base.RosePetalsDried", -- ooh lala!
}

-- stuff for the poker night story
-- cards and 1 money are spawned by the story
-- some stories have separate drink and snack tables, and some don't
StoryClutter.PokerNightClutter = {
    "Base.CigaretteSingle",
    "Base.Cigar",
    "Base.Cigar",
    "Base.Crisps",
    "Base.Crisps2",
    "Base.Crisps3",
    "Base.Money",
    "Base.PokerChips",
    "Base.PokerChips",
    "Base.Pop",
    "Base.Pop2",
    "Base.Pop3",
	"Base.Gin",
	"Base.Scotch",
    "Base.Whiskey",
    "Base.Wine",
    "Base.Wine2",
}

-- ground clutter for the rich jerk road story; a briefcase of money automatically spawns
StoryClutter.RichJerkClutter = {
    "Base.Bag_Satchel_Leather",
    "Base.Briefcase",
    "Base.BusinessCard",
    "Base.CreditCard",
    "Base.Flask",
    "Base.Glasses_Cosmetic_Normal",
    "Base.GoldBar",
    "Base.Handbag",
    "Base.Money",
    "Base.MoneyBundle",
    "Base.Purse",
    "Base.SmallGoldBar",
    "Base.StockCertificate",
    "Base.Suitcase",
    "Base.Wallet_Male",
    "Base.Passport",
}

StoryClutter.SadCampsiteClutter = {
	"Base.TinCanEmpty",
	"Base.TinCanEmpty",
	"Base.WaterBottleEmpty",
	"Base.RippedSheetsDirty",
	"Base.BandageDirty",
	"Base.WaterBottleEmpty",
	"Base.TinOpener",
	"Base.GuitarAcoustic",
    "Base.Bag_Schoolbag_Kids",
    "Base.BandageDirty",
    "Base.BandageDirty",
    "Base.Book_Bible",
    "Base.Doll",
    "Base.DoodleKids",
    "Base.Handbag",
    "Base.LetterHandwritten",
    "Base.Locket",
    "Base.Necklace_SilverCrucifix",
    "Base.Photo",
    "Base.Purse",
    "Base.Suitcase",
    "Base.ToyBear",
    "Base.ToyCar",
    "Base.Wallet",
    "Base.Passport",
    "Base.DogTag_Pet",
    "Base.Cooler",
    "Base.Harmonica",
    "Base.ChildsPictureBook",
    "Base.Diary2",
    "Base.KnifePocket",
    "Base.Bag_NormalHikingBag",
    "Base.DogFoodBag",
    "Base.WaterDish",
    "Base.ScoutCookies",
    "Base.PhotoAlbum",
    "Base.Newspaper_Recent",
}

-- sidetables in residential bedrooms, used for Randomized Residential Buildings
StoryClutter.SidetableClutter = {
    "Base.AlarmClock2",
    "Base.Belt2",
    "Base.Book",
    "Base.Book_Bible",
    "Base.Card_Valentine",
    "Base.CDplayer",
    "Base.Chocolate_HeartBox",
    "Base.CigarettePack",
    "Base.CigaretteRollingPapers",
    "Base.CordlessPhone",
    "Base.Diary2",
    "Base.Flask",
    "Base.Glasses_Normal",
    "Base.Glasses_Reading",
    "Base.Harmonica",
    "Base.HottieZ",
    "Base.KeyRing",
    "Base.LetterHandwritten",
    "Base.Lighter",
    "Base.LighterDisposable",
    "Base.Locket",
    "Base.Notebook",
    "Base.Magazine",
    "Base.Money",
    "Base.Necklace_Crucifix",
    "Base.Paperback",
    "Base.Paperback_SelfHelp",
    "Base.Paperback_Scary",
    "Base.Photo",
    "Base.Pocketwatch",
    "Base.Revolver_Short", -- kentucky, 1993, just being a responsible homeowner
    "Base.Ring_Left_RingFinger_Gold",
    "Base.Ring_Left_RingFinger_GoldDiamond",
    "Base.Ring_Left_RingFinger_Silver",
    "Base.Teacup",
    "Base.TissueBox",
    "Base.VideoGame",
    "Base.Wallet",
    "Base.Whiskey",
    "Base.PhotoAlbum",
}

StoryClutter.SurvivalistCampsiteClutter = {
	"Base.TinCanEmpty",
	"Base.TinCanEmpty",
	"Base.WaterBottleEmpty",
	"Base.RippedSheetsDirty",
	"Base.BandageDirty",
	"Base.Lantern_Propane",
	"Base.Crowbar",
	"Base.Machete",
	"Base.Shotgun",
	"Base.HuntingKnife",
	"Base.Matches",
	"Base.WaterBottleEmpty",
	"Base.TinOpener",
	"Base.ShotgunShellsBox",
	"Base.Pistol",
	"Base.WaterDispenserBottle",
	"Base.GuitarAcoustic",
	"Base.HottieZ",
	"Base.MetalCup",
    "Base.Harmonica",
}

StoryClutter.TwiggyClutter = {
	"Base.BeerBottle",
	"Base.BeerImported",
	"Base.Gin",
	"Base.GlassTumbler",
	"Base.GlassTumbler",
	"Base.GlassTumbler",
	"Base.GlassTumbler",
	"Base.GlassTumbler",
	"Base.Rum",
	"Base.Scotch",
	"Base.Tequila",
	"Base.Vermouth",
	"Base.Vodka",
	"Base.Whiskey",
}

-- the tools that can spawn on the road next to a manhole with the utility vehicle road story
StoryClutter.UtilityToolClutter = {
    "Base.Hammer",
    "Base.LeadPipe",
    "Base.PickAxe",
    "Base.PipeWrench",
    "Base.Shovel",
    "Base.Shovel2",
    "Base.Sledgehammer",
    "Base.Sledgehammer2",
}

-- the pool of watches that are sometimes spawned instead of sidetable clutter in residential bedrooms, used for Randomized Residential Buildings
StoryClutter.WatchClutter = {
    "Base.WristWatch_Right_ClassicBlack",
    "Base.WristWatch_Right_ClassicBrown",
    "Base.WristWatch_Right_ClassicGold",
    "Base.WristWatch_Right_DigitalBlack",
    "Base.WristWatch_Right_DigitalDress",
    "Base.WristWatch_Right_DigitalRed",
}

StoryClutter.WoodcraftClutter = {
	"Base.Drawer",
	"Base.Nails",
	"Base.Nails",
	"Base.Plank",
	"Base.Plank",
	"Base.Saw",
}
