require "RandomizedWorldContent/StoryTable_Initialization"

StoryClutter.Init = function()
    print("Initializing Randomized World Tabletop Clutter Tables")

    local RWB = getWorld():getRandomizedWorldBase()
    local javaTable = RWB:getBarnClutter()
    local luaTable = StoryClutter.BarnClutter

    StoryTables.initClutterArray(RWB:getBarnClutter(), StoryClutter.BarnClutter)
    StoryTables.initClutterArray(RWB:getBathroomSinkClutter(), StoryClutter.BathroomSinkClutter)
    StoryTables.initClutterArray(RWB:getBBQClutter(), StoryClutter.BBQClutter)
    StoryTables.initClutterArray(RWB:getBeachPartyClutter(), StoryClutter.BeachPartyClutter)
    StoryTables.initClutterArray(RWB:getBedClutter(), StoryClutter.BedClutter)
	StoryTables.initClutterArray(RWB:getCafeClutter(), StoryClutter.CafeClutter)
    StoryTables.initClutterArray(RWB:getCarpentryToolClutter(), StoryClutter.CarpentryToolClutter)
    StoryTables.initClutterArray(RWB:getDeadEndClutter(), StoryClutter.DeadEndClutter)
    StoryTables.initClutterArray(RWB:getDormClutter(), StoryClutter.DormClutter)
    StoryTables.initClutterArray(RWB:getFarmStorageClutter(), StoryClutter.FarmStorageClutter)
    StoryTables.initClutterArray(RWB:getFootballNightDrinks(), StoryClutter.FootballNightDrinks)
    StoryTables.initClutterArray(RWB:getFootballNightSnacks(), StoryClutter.FootballNightSnacks)
    StoryTables.initClutterArray(RWB:getGarageStorageClutter(), StoryClutter.GarageStorageClutter)
	StoryTables.initClutterArray(RWB:getGigamartClutter(), StoryClutter.GigamartClutter)
	StoryTables.initClutterArray(RWB:getGroceryClutter(), StoryClutter.GroceryClutter)
    StoryTables.initClutterArray(RWB:getHairSalonClutter(), StoryClutter.HairSalonClutter)
    StoryTables.initClutterArray(RWB:getHallClutter(), StoryClutter.HallClutter)
    StoryTables.initClutterArray(RWB:getHenDoDrinks(), StoryClutter.HenDoDrinks)
    StoryTables.initClutterArray(RWB:getHenDoSnacks(), StoryClutter.HenDoSnacks)
    StoryTables.initClutterArray(RWB:getHoedownClutter(), StoryClutter.HoedownClutter)
    StoryTables.initClutterArray(RWB:getHousePartyClutter(), StoryClutter.HousePartyClutter)
	StoryTables.initClutterArray(RWB:getJudgeClutter(), StoryClutter.JudgeClutter)
    StoryTables.initClutterArray(RWB:getKidClutter(), StoryClutter.KidClutter)
    StoryTables.initClutterArray(RWB:getKitchenCounterClutter(), StoryClutter.KitchenCounterClutter)
    StoryTables.initClutterArray(RWB:getKitchenSinkClutter(), StoryClutter.KitchenSinkClutter)
    StoryTables.initClutterArray(RWB:getKitchenStoveClutter(), StoryClutter.KitchenStoveClutter)
    StoryTables.initClutterArray(RWB:getLaundryRoomClutter(), StoryClutter.LaundryRoomClutter)
    StoryTables.initClutterArray(RWB:getLivingroomClutter(), StoryClutter.LivingroomClutter)
    StoryTables.initClutterArray(RWB:getMedicalClutter(), StoryClutter.MedicalClutter)
    StoryTables.initClutterArray(RWB:getMurderSceneClutter(), StoryClutter.MurderSceneClutter)
    StoryTables.initClutterArray(RWB:getNastyMattressClutter(), StoryClutter.NastyMattressClutter)
    StoryTables.initClutterArray(RWB:getOldShelterClutter(), StoryClutter.OldShelterClutter)
	StoryTables.initClutterArray(RWB:getOfficeCarDealerClutter(), StoryClutter.OfficeCarDealerClutter)
    StoryTables.initClutterArray(RWB:getOfficePaperworkClutter(), StoryClutter.OfficePaperworkClutter)
    StoryTables.initClutterArray(RWB:getOfficePenClutter(), StoryClutter.OfficePenClutter)
    StoryTables.initClutterArray(RWB:getOfficeOtherClutter(), StoryClutter.OfficeOtherClutter)
    StoryTables.initClutterArray(RWB:getOfficeTreatClutter(), StoryClutter.OfficeTreatClutter)
    StoryTables.initClutterArray(RWB:getOvenFoodClutter(), StoryClutter.OvenFoodClutter)
    StoryTables.initClutterArray(RWB:getPillowClutter(), StoryClutter.PillowClutter)
    StoryTables.initClutterArray(RWB:getPokerNightClutter(), StoryClutter.PokerNightClutter)
    StoryTables.initClutterArray(RWB:getRichJerkClutter(), StoryClutter.RichJerkClutter)
    StoryTables.initClutterArray(RWB:getSadCampsiteClutter(), StoryClutter.SadCampsiteClutter)
    StoryTables.initClutterArray(RWB:getSidetableClutter(), StoryClutter.SidetableClutter)
    StoryTables.initClutterArray(RWB:getSurvivalistCampsiteClutter(), StoryClutter.SurvivalistCampsiteClutter)
	StoryTables.initClutterArray(RWB:getTwiggyClutter(), StoryClutter.TwiggyClutter)
    StoryTables.initClutterArray(RWB:getUtilityToolClutter(), StoryClutter.UtilityToolClutter)
    StoryTables.initClutterArray(RWB:getVanCampClutter(), StoryClutter.VanCampClutter)
    StoryTables.initClutterArray(RWB:getWatchClutter(), StoryClutter.WatchClutter)
	StoryTables.initClutterArray(RWB:getWoodcraftClutter(), StoryClutter.WoodcraftClutter)
end

-- Events.OnPostDistributionMerge.Add(StoryClutter.Init())
Events.OnLoadedMapZones.Add(StoryClutter.Init())